// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  Car Care Plan
// File:    carcareplan.js
// Period:  Jan–May 2026
// Updated: 31 May 2026
// GENERATED AUTOMATICALLY FROM TrackOps CSV — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {
  "client_name": "Car Care Plan",
  "report_period": "Jan–May 2026",
  "last_updated": "31 May 2026",
  "is_rtc_client": true,
  "total_cases": 5,
  "avg_days_creation_to_update": 0,
  "avg_days_creation_to_update_general": 0,
  "avg_days_stmt_to_report": 6.3,
  "avg_days_stmt_to_report_rtc": 0,
  "avg_days_stmt_to_report_general": 6.3,
  "sla_ack_pct": 100,
  "sla_contact_pct": 100,
  "sla_update_pct": null,
  "sla_report_general_pct": 33,
  "sla_report_rtc_pct": null,
  "has_rtc_cases": true,
  "has_general_cases": true,
  "sla_compliance_pct": 78,
  "sla_met": 1,
  "sla_not_met": 2,
  "avg_fee_rtc": 0,
  "avg_fee_general": 237.5,
  "total_fees_rtc": 0,
  "total_fees_general": 950,
  "rtc_case_count": 1,
  "general_case_count": 4,
  "fees_by_type": [
    {
      "type": "Gap Insurance investigation",
      "is_rtc": false,
      "case_count": 4,
      "total_fees": 950,
      "avg_fee": 237.5
    },
    {
      "type": "RTC",
      "is_rtc": true,
      "case_count": 1,
      "total_fees": 0,
      "avg_fee": 0
    }
  ],
  "total_invoiced_lineitems": 950,
  "total_lineitem_count": 2,
  "fees_by_item": [
    {
      "item": "Stage 1 Investigation",
      "is_rtc": false,
      "count": 1,
      "total": 500,
      "avg": 500
    },
    {
      "item": "Motor Theft Investigation",
      "is_rtc": false,
      "count": 1,
      "total": 450,
      "avg": 450
    }
  ],
  "monthly": [
    {
      "month": "Jan",
      "month_num": 1,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Feb",
      "month_num": 2,
      "case_count": 1,
      "case_count_rtc": 0,
      "case_count_general": 1,
      "total_fees": 450,
      "ave_fees": 450,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 4,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 4,
      "sla_ack_pct": 100,
      "sla_ack_met": 1,
      "sla_ack_n": 1,
      "sla_contact_pct": 100,
      "sla_contact_met": 1,
      "sla_contact_n": 1,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": 0,
      "sla_report_general_met": 0,
      "sla_report_general_n": 1,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 67,
      "sla_met": 0,
      "sla_not_met": 1
    },
    {
      "month": "Mar",
      "month_num": 3,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Apr",
      "month_num": 4,
      "case_count": 1,
      "case_count_rtc": 0,
      "case_count_general": 1,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": 100,
      "sla_ack_met": 1,
      "sla_ack_n": 1,
      "sla_contact_pct": 100,
      "sla_contact_met": 1,
      "sla_contact_n": 1,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 100,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "May",
      "month_num": 5,
      "case_count": 3,
      "case_count_rtc": 1,
      "case_count_general": 2,
      "total_fees": 500,
      "ave_fees": 167,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 7.5,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 7.5,
      "sla_ack_pct": 100,
      "sla_ack_met": 3,
      "sla_ack_n": 3,
      "sla_contact_pct": 100,
      "sla_contact_met": 3,
      "sla_contact_n": 3,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": 50,
      "sla_report_general_met": 1,
      "sla_report_general_n": 2,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 83,
      "sla_met": 1,
      "sla_not_met": 1
    },
    {
      "month": "Jun",
      "month_num": 6,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Jul",
      "month_num": 7,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Aug",
      "month_num": 8,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Sep",
      "month_num": 9,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Oct",
      "month_num": 10,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Nov",
      "month_num": 11,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Dec",
      "month_num": 12,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    }
  ],
  "cases": [
    {
      "ref": "1166205",
      "client_ref": null,
      "type": "RTC",
      "status": "Awaiting further advises",
      "created": "21 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1164105",
      "client_ref": null,
      "type": "Gap Insurance investigation",
      "status": "Invoice Paid",
      "created": "18 May 2026",
      "first_updated": "",
      "stmt_date": "19 May 2026",
      "report_sent": "21 May 2026",
      "days_creation_to_update": null,
      "days_stmt_to_report": 2,
      "invoice": 500,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1161505",
      "client_ref": null,
      "type": "Gap Insurance investigation",
      "status": "Witness stmnt being obtained",
      "created": "6 May 2026",
      "first_updated": "",
      "stmt_date": "15 May 2026",
      "report_sent": "28 May 2026",
      "days_creation_to_update": null,
      "days_stmt_to_report": 13,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1160104",
      "client_ref": null,
      "type": "Gap Insurance investigation",
      "status": "Documents Submitted",
      "created": "29 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1138802",
      "client_ref": null,
      "type": "Gap Insurance investigation",
      "status": "Invoice Paid",
      "created": "17 Feb 2026",
      "first_updated": "",
      "stmt_date": "20 Feb 2026",
      "report_sent": "24 Feb 2026",
      "days_creation_to_update": null,
      "days_stmt_to_report": 4,
      "invoice": 450,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    }
  ]
};
