// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  Meridian Motor Insurance (DEMO)
// File:    demo.js
// Period:  Jan–Dec 2026
// Updated: 21 Jul 2026
// DEMO DATA — for client presentation purposes only
// ============================================================

var DLB_CLIENT_DATA = {

  client_name:                  "Meridian Motor Insurance",
  report_period:                "Jan–Dec 2026",
  last_updated:                 "21 Jul 2026",
  is_rtc_client:                true,
  total_cases:                  76,

  avg_days_creation_to_update:         0.9,
  avg_days_creation_to_update_general: 1.4,
  avg_days_stmt_to_report:             3.1,
  avg_days_stmt_to_report_rtc:         1.2,
  avg_days_stmt_to_report_general:     9.8,

  sla_ack_pct:                  100,
  sla_contact_pct:              100,
  sla_update_pct:               94,
  sla_report_general_pct:       8,
  sla_report_rtc_pct:           92,
  has_rtc_cases:                true,
  has_general_cases:            true,
  sla_compliance_pct:           88,
  sla_met:                      44,
  sla_not_met:                  6,

  avg_fee_rtc:                  160,
  avg_fee_general:              682.14,
  total_fees_rtc:               7680,
  total_fees_general:           19100,
  rtc_case_count:               48,
  general_case_count:           28,
  fees_by_type: [
    { type:"RTC",         is_rtc:true,  case_count:48, total_fees:7680,  avg_fee:160    },
    { type:"Motor Fraud", is_rtc:false, case_count:19, total_fees:11400, avg_fee:600    },
    { type:"Motor Theft", is_rtc:false, case_count:8,  total_fees:7200,  avg_fee:900    },
    { type:"SVA",         is_rtc:false, case_count:1,  total_fees:500,   avg_fee:500    }
  ],

  total_invoiced_lineitems:     26780,
  total_lineitem_count:         94,
  fees_by_item: [
    { item:"RTC",                       is_rtc:true,  count:48, total:7680,  avg:160    },
    { item:"Stage 1 Investigation",     is_rtc:false, count:12, total:5400,  avg:450    },
    { item:"Stage 2 Investigation",     is_rtc:false, count:6,  total:3600,  avg:600    },
    { item:"Motor Theft Investigation", is_rtc:false, count:8,  total:7200,  avg:900    },
    { item:"Cold Calls",                is_rtc:false, count:9,  total:900,   avg:100    },
    { item:"Failed Appointment",        is_rtc:false, count:5,  total:500,   avg:100    },
    { item:"Interpreter (half day)",    is_rtc:false, count:3,  total:450,   avg:150    },
    { item:"Translation services",      is_rtc:false, count:3,  total:1050,  avg:350    }
  ],

  monthly: [
    { month:"Jan", month_num:1,  case_count:6,  case_count_rtc:0,  case_count_general:6,  total_fees:3480, ave_fees:580,   total_fees_rtc:0,    total_fees_general:3480, ave_days_creation_to_update:1.5, ave_days_creation_to_update_general:1.5, ave_days_stmt_to_report:9.8, ave_days_stmt_to_report_rtc:0,   ave_days_stmt_to_report_general:9.8, sla_ack_pct:100, sla_ack_met:6, sla_ack_n:6,  sla_contact_pct:100, sla_contact_met:6, sla_contact_n:6,  sla_update_pct:83,  sla_update_met:5, sla_update_n:6, sla_report_general_pct:0,    sla_report_general_met:0, sla_report_general_n:5, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:14, sla_met:0, sla_not_met:5 },
    { month:"Feb", month_num:2,  case_count:8,  case_count_rtc:2,  case_count_general:6,  total_fees:3920, ave_fees:490,   total_fees_rtc:320,  total_fees_general:3600, ave_days_creation_to_update:1.2, ave_days_creation_to_update_general:1.6, ave_days_stmt_to_report:7.4, ave_days_stmt_to_report_rtc:1.5, ave_days_stmt_to_report_general:9.2, sla_ack_pct:100, sla_ack_met:8, sla_ack_n:8,  sla_contact_pct:100, sla_contact_met:8, sla_contact_n:8,  sla_update_pct:88,  sla_update_met:7, sla_update_n:8, sla_report_general_pct:0,    sla_report_general_met:0, sla_report_general_n:5, sla_report_rtc_pct:100,  sla_report_rtc_met:2, sla_report_rtc_n:2, sla_compliance_pct:29, sla_met:2, sla_not_met:5 },
    { month:"Mar", month_num:3,  case_count:10, case_count_rtc:4,  case_count_general:6,  total_fees:4240, ave_fees:424,   total_fees_rtc:640,  total_fees_general:3600, ave_days_creation_to_update:1.1, ave_days_creation_to_update_general:1.7, ave_days_stmt_to_report:5.6, ave_days_stmt_to_report_rtc:1.3, ave_days_stmt_to_report_general:9.5, sla_ack_pct:100, sla_ack_met:10,sla_ack_n:10, sla_contact_pct:100, sla_contact_met:10,sla_contact_n:10, sla_update_pct:90,  sla_update_met:9, sla_update_n:10,sla_report_general_pct:0,    sla_report_general_met:0, sla_report_general_n:5, sla_report_rtc_pct:100,  sla_report_rtc_met:4, sla_report_rtc_n:4, sla_compliance_pct:44, sla_met:4, sla_not_met:5 },
    { month:"Apr", month_num:4,  case_count:12, case_count_rtc:8,  case_count_general:4,  total_fees:3680, ave_fees:306.7, total_fees_rtc:1280, total_fees_general:2400, ave_days_creation_to_update:0.9, ave_days_creation_to_update_general:1.3, ave_days_stmt_to_report:3.4, ave_days_stmt_to_report_rtc:1.2, ave_days_stmt_to_report_general:8.8, sla_ack_pct:100, sla_ack_met:12,sla_ack_n:12, sla_contact_pct:100, sla_contact_met:12,sla_contact_n:12, sla_update_pct:100, sla_update_met:4, sla_update_n:4, sla_report_general_pct:0,    sla_report_general_met:0, sla_report_general_n:3, sla_report_rtc_pct:88,   sla_report_rtc_met:7, sla_report_rtc_n:8, sla_compliance_pct:70, sla_met:7, sla_not_met:4 },
    { month:"May", month_num:5,  case_count:14, case_count_rtc:11, case_count_general:3,  total_fees:3560, ave_fees:254.3, total_fees_rtc:1760, total_fees_general:1800, ave_days_creation_to_update:0.7, ave_days_creation_to_update_general:1.0, ave_days_stmt_to_report:2.5, ave_days_stmt_to_report_rtc:1.1, ave_days_stmt_to_report_general:9.2, sla_ack_pct:100, sla_ack_met:14,sla_ack_n:14, sla_contact_pct:100, sla_contact_met:14,sla_contact_n:14, sla_update_pct:100, sla_update_met:3, sla_update_n:3, sla_report_general_pct:33,   sla_report_general_met:1, sla_report_general_n:3, sla_report_rtc_pct:91,   sla_report_rtc_met:10,sla_report_rtc_n:11,sla_compliance_pct:79, sla_met:10,sla_not_met:3 },
    { month:"Jun", month_num:6,  case_count:16, case_count_rtc:14, case_count_general:2,  total_fees:3440, ave_fees:215,   total_fees_rtc:2240, total_fees_general:1200, ave_days_creation_to_update:0.6, ave_days_creation_to_update_general:0.5, ave_days_stmt_to_report:1.9, ave_days_stmt_to_report_rtc:1.1, ave_days_stmt_to_report_general:8.5, sla_ack_pct:100, sla_ack_met:16,sla_ack_n:16, sla_contact_pct:100, sla_contact_met:16,sla_contact_n:16, sla_update_pct:100, sla_update_met:2, sla_update_n:2, sla_report_general_pct:0,    sla_report_general_met:0, sla_report_general_n:2, sla_report_rtc_pct:93,   sla_report_rtc_met:13,sla_report_rtc_n:14,sla_compliance_pct:81, sla_met:13,sla_not_met:3 },
    { month:"Jul", month_num:7,  case_count:10, case_count_rtc:9,  case_count_general:1,  total_fees:2000, ave_fees:200,   total_fees_rtc:1440, total_fees_general:560,  ave_days_creation_to_update:0.4, ave_days_creation_to_update_general:0.0, ave_days_stmt_to_report:1.3, ave_days_stmt_to_report_rtc:1.0, ave_days_stmt_to_report_general:5.0, sla_ack_pct:100, sla_ack_met:10,sla_ack_n:10, sla_contact_pct:100, sla_contact_met:10,sla_contact_n:10, sla_update_pct:100, sla_update_met:1, sla_update_n:1, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:89,   sla_report_rtc_met:8, sla_report_rtc_n:9, sla_compliance_pct:89, sla_met:8, sla_not_met:1 },
    { month:"Aug", month_num:8,  case_count:0,  case_count_rtc:0,  case_count_general:0,  total_fees:0,    ave_fees:0,     total_fees_rtc:0,    total_fees_general:0,    ave_days_creation_to_update:0,   ave_days_creation_to_update_general:0,   ave_days_stmt_to_report:0,   ave_days_stmt_to_report_rtc:0,   ave_days_stmt_to_report_general:0,   sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0,  sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0,  sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Sep", month_num:9,  case_count:0,  case_count_rtc:0,  case_count_general:0,  total_fees:0,    ave_fees:0,     total_fees_rtc:0,    total_fees_general:0,    ave_days_creation_to_update:0,   ave_days_creation_to_update_general:0,   ave_days_stmt_to_report:0,   ave_days_stmt_to_report_rtc:0,   ave_days_stmt_to_report_general:0,   sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0,  sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0,  sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Oct", month_num:10, case_count:0,  case_count_rtc:0,  case_count_general:0,  total_fees:0,    ave_fees:0,     total_fees_rtc:0,    total_fees_general:0,    ave_days_creation_to_update:0,   ave_days_creation_to_update_general:0,   ave_days_stmt_to_report:0,   ave_days_stmt_to_report_rtc:0,   ave_days_stmt_to_report_general:0,   sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0,  sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0,  sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Nov", month_num:11, case_count:0,  case_count_rtc:0,  case_count_general:0,  total_fees:0,    ave_fees:0,     total_fees_rtc:0,    total_fees_general:0,    ave_days_creation_to_update:0,   ave_days_creation_to_update_general:0,   ave_days_stmt_to_report:0,   ave_days_stmt_to_report_rtc:0,   ave_days_stmt_to_report_general:0,   sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0,  sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0,  sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Dec", month_num:12, case_count:0,  case_count_rtc:0,  case_count_general:0,  total_fees:0,    ave_fees:0,     total_fees_rtc:0,    total_fees_general:0,    ave_days_creation_to_update:0,   ave_days_creation_to_update_general:0,   ave_days_stmt_to_report:0,   ave_days_stmt_to_report_rtc:0,   ave_days_stmt_to_report_general:0,   sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0,  sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0,  sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 }
  ],

  cases: [
    // ── January 2026 — no RTC yet ──
    { ref:"1300101", client_ref:"MM26/48231", type:"Motor Fraud", status:"Invoice Paid",       created:"5 Jan 2026",  first_updated:"6 Jan 2026",   stmt_date:"14 Jan 2026", report_sent:"23 Jan 2026", days_creation_to_update:1,  days_stmt_to_report:9,  invoice:720,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1300201", client_ref:"MM26/48249", type:"Motor Fraud", status:"Invoice Paid",       created:"7 Jan 2026",  first_updated:"8 Jan 2026",   stmt_date:"16 Jan 2026", report_sent:"24 Jan 2026", days_creation_to_update:1,  days_stmt_to_report:8,  invoice:480,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1300301", client_ref:"MM26/48157", type:"Motor Theft", status:"Invoice Paid",       created:"9 Jan 2026",  first_updated:"12 Jan 2026",  stmt_date:"20 Jan 2026", report_sent:"30 Jan 2026", days_creation_to_update:3,  days_stmt_to_report:10, invoice:1080, is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1300401", client_ref:"MM26/48362", type:"Motor Fraud", status:"Invoice Paid",       created:"13 Jan 2026", first_updated:"13 Jan 2026",  stmt_date:"22 Jan 2026", report_sent:"31 Jan 2026", days_creation_to_update:0,  days_stmt_to_report:9,  invoice:600,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1300501", client_ref:"MM26/48401", type:"Motor Fraud", status:"Invoiced",           created:"16 Jan 2026", first_updated:"17 Jan 2026",  stmt_date:"",            report_sent:"",            days_creation_to_update:1,  days_stmt_to_report:null,invoice:144,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:null,  report_proxy:false, sla_report_target_days:3 },
    { ref:"1300601", client_ref:"MM26/48278", type:"Motor Theft", status:"Invoice Paid",       created:"22 Jan 2026", first_updated:"23 Jan 2026",  stmt_date:"3 Feb 2026",  report_sent:"14 Feb 2026", days_creation_to_update:1,  days_stmt_to_report:11, invoice:1320, is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },

    // ── February 2026 — first 2 RTC cases ──
    { ref:"1301102", client_ref:"MM26/48471", type:"Motor Fraud", status:"Invoice Paid",       created:"3 Feb 2026",  first_updated:"3 Feb 2026",   stmt_date:"12 Feb 2026", report_sent:"22 Feb 2026", days_creation_to_update:0,  days_stmt_to_report:10, invoice:600,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1301202", client_ref:"MM26/48512", type:"Motor Fraud", status:"Invoice Paid",       created:"5 Feb 2026",  first_updated:"6 Feb 2026",   stmt_date:"14 Feb 2026", report_sent:"21 Feb 2026", days_creation_to_update:1,  days_stmt_to_report:7,  invoice:480,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1301302", client_ref:"MM26/48539", type:"Motor Theft", status:"Invoice Paid",       created:"9 Feb 2026",  first_updated:"12 Feb 2026",  stmt_date:"20 Feb 2026", report_sent:"1 Mar 2026",  days_creation_to_update:3,  days_stmt_to_report:9,  invoice:1080, is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1301402", client_ref:"MM26/48561", type:"Motor Fraud", status:"Invoiced",           created:"11 Feb 2026", first_updated:"12 Feb 2026",  stmt_date:"",            report_sent:"",            days_creation_to_update:1,  days_stmt_to_report:null,invoice:144,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:null,  report_proxy:false, sla_report_target_days:3 },
    { ref:"1301502", client_ref:"MM26/48588", type:"Motor Fraud", status:"Invoiced",           created:"14 Feb 2026", first_updated:"15 Feb 2026",  stmt_date:"",            report_sent:"",            days_creation_to_update:1,  days_stmt_to_report:null,invoice:144,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:null,  report_proxy:false, sla_report_target_days:3 },
    { ref:"1301602", client_ref:"MM26/48604", type:"Motor Fraud", status:"Invoiced",           created:"19 Feb 2026", first_updated:"20 Feb 2026",  stmt_date:"",            report_sent:"",            days_creation_to_update:1,  days_stmt_to_report:null,invoice:72,   is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:null,  report_proxy:false, sla_report_target_days:3 },
    { ref:"1301702", client_ref:"MM26/48617", type:"RTC",         status:"Invoice Paid",       created:"24 Feb 2026", first_updated:"24 Feb 2026",  stmt_date:"27 Feb 2026", report_sent:"28 Feb 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1301802", client_ref:"MM26/48628", type:"RTC",         status:"Invoice Paid",       created:"26 Feb 2026", first_updated:"26 Feb 2026",  stmt_date:"28 Feb 2026", report_sent:"1 Mar 2026",  days_creation_to_update:0,  days_stmt_to_report:2,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },

    // ── March 2026 — RTC adoption begins ──
    { ref:"1302103", client_ref:"MM26/48641", type:"Motor Fraud", status:"Invoice Paid",       created:"3 Mar 2026",  first_updated:"4 Mar 2026",   stmt_date:"12 Mar 2026", report_sent:"20 Mar 2026", days_creation_to_update:1,  days_stmt_to_report:8,  invoice:600,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1302203", client_ref:"MM26/48659", type:"Motor Fraud", status:"Invoiced",           created:"5 Mar 2026",  first_updated:"6 Mar 2026",   stmt_date:"",            report_sent:"",            days_creation_to_update:1,  days_stmt_to_report:null,invoice:144,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:null,  report_proxy:false, sla_report_target_days:3 },
    { ref:"1302303", client_ref:"MM26/48672", type:"Motor Theft", status:"Invoice Paid",       created:"7 Mar 2026",  first_updated:"9 Mar 2026",   stmt_date:"18 Mar 2026", report_sent:"29 Mar 2026", days_creation_to_update:2,  days_stmt_to_report:11, invoice:1080, is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1302403", client_ref:"MM26/48685", type:"Motor Fraud", status:"Invoice Paid",       created:"10 Mar 2026", first_updated:"11 Mar 2026",  stmt_date:"20 Mar 2026", report_sent:"29 Mar 2026", days_creation_to_update:1,  days_stmt_to_report:9,  invoice:480,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1302503", client_ref:"MM26/48701", type:"Motor Fraud", status:"Invoiced",           created:"13 Mar 2026", first_updated:"14 Mar 2026",  stmt_date:"",            report_sent:"",            days_creation_to_update:1,  days_stmt_to_report:null,invoice:72,   is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:null,  report_proxy:false, sla_report_target_days:3 },
    { ref:"1302603", client_ref:"MM26/48714", type:"Motor Theft", status:"Invoice Paid",       created:"17 Mar 2026", first_updated:"18 Mar 2026",  stmt_date:"27 Mar 2026", report_sent:"9 Apr 2026",  days_creation_to_update:1,  days_stmt_to_report:13, invoice:1200, is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1302703", client_ref:"MM26/48729", type:"RTC",         status:"Invoice Paid",       created:"19 Mar 2026", first_updated:"19 Mar 2026",  stmt_date:"21 Mar 2026", report_sent:"22 Mar 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1302803", client_ref:"MM26/48741", type:"RTC",         status:"Invoice Paid",       created:"21 Mar 2026", first_updated:"21 Mar 2026",  stmt_date:"24 Mar 2026", report_sent:"25 Mar 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1302903", client_ref:"MM26/48758", type:"RTC",         status:"Invoice Paid",       created:"25 Mar 2026", first_updated:"25 Mar 2026",  stmt_date:"28 Mar 2026", report_sent:"30 Mar 2026", days_creation_to_update:0,  days_stmt_to_report:2,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1303003", client_ref:"MM26/48771", type:"RTC",         status:"Invoiced",           created:"28 Mar 2026", first_updated:"28 Mar 2026",  stmt_date:"31 Mar 2026", report_sent:"2 Apr 2026",  days_creation_to_update:0,  days_stmt_to_report:2,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },

    // ── April 2026 — RTC becomes primary ──
    { ref:"1303504", client_ref:"MM26/48791", type:"RTC",         status:"Invoice Paid",       created:"1 Apr 2026",  first_updated:"1 Apr 2026",   stmt_date:"3 Apr 2026",  report_sent:"4 Apr 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1303604", client_ref:"MM26/48803", type:"RTC",         status:"Invoice Paid",       created:"2 Apr 2026",  first_updated:"2 Apr 2026",   stmt_date:"4 Apr 2026",  report_sent:"5 Apr 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1303704", client_ref:"MM26/48818", type:"RTC",         status:"Invoice Paid",       created:"4 Apr 2026",  first_updated:"4 Apr 2026",   stmt_date:"7 Apr 2026",  report_sent:"8 Apr 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1303804", client_ref:"MM26/48831", type:"RTC",         status:"Invoice Paid",       created:"7 Apr 2026",  first_updated:"7 Apr 2026",   stmt_date:"10 Apr 2026", report_sent:"11 Apr 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1303904", client_ref:"MM26/48844", type:"RTC",         status:"Invoice Paid",       created:"9 Apr 2026",  first_updated:"9 Apr 2026",   stmt_date:"12 Apr 2026", report_sent:"14 Apr 2026", days_creation_to_update:0,  days_stmt_to_report:2,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1304004", client_ref:"MM26/48857", type:"RTC",         status:"Invoice Paid",       created:"11 Apr 2026", first_updated:"11 Apr 2026",  stmt_date:"15 Apr 2026", report_sent:"16 Apr 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1304104", client_ref:"MM26/48869", type:"RTC",         status:"Invoiced",           created:"14 Apr 2026", first_updated:"14 Apr 2026",  stmt_date:"17 Apr 2026", report_sent:"21 Apr 2026", days_creation_to_update:0,  days_stmt_to_report:4,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:false, report_proxy:false, sla_report_target_days:2 },
    { ref:"1304204", client_ref:"MM26/48882", type:"RTC",         status:"Invoice Paid",       created:"16 Apr 2026", first_updated:"16 Apr 2026",  stmt_date:"18 Apr 2026", report_sent:"19 Apr 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1304304", client_ref:"MM26/48895", type:"Motor Fraud", status:"Invoice Paid",       created:"7 Apr 2026",  first_updated:"7 Apr 2026",   stmt_date:"16 Apr 2026", report_sent:"25 Apr 2026", days_creation_to_update:0,  days_stmt_to_report:9,  invoice:600,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1304404", client_ref:"MM26/48908", type:"Motor Fraud", status:"Invoice Paid",       created:"10 Apr 2026", first_updated:"11 Apr 2026",  stmt_date:"20 Apr 2026", report_sent:"30 Apr 2026", days_creation_to_update:1,  days_stmt_to_report:10, invoice:600,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1304504", client_ref:"MM26/48921", type:"Motor Theft", status:"Invoice Paid",       created:"15 Apr 2026", first_updated:"15 Apr 2026",  stmt_date:"25 Apr 2026", report_sent:"7 May 2026",  days_creation_to_update:0,  days_stmt_to_report:12, invoice:1200, is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1304604", client_ref:"MM26/48934", type:"Motor Fraud", status:"Invoiced",           created:"22 Apr 2026", first_updated:"23 Apr 2026",  stmt_date:"",            report_sent:"",            days_creation_to_update:1,  days_stmt_to_report:null,invoice:144,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:null,  report_proxy:false, sla_report_target_days:3 },

    // ── May 2026 — RTC dominant ──
    { ref:"1305205", client_ref:"MM26/48951", type:"RTC",         status:"Invoice Paid",       created:"1 May 2026",  first_updated:"1 May 2026",   stmt_date:"3 May 2026",  report_sent:"4 May 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1305305", client_ref:"MM26/48964", type:"RTC",         status:"Invoice Paid",       created:"2 May 2026",  first_updated:"2 May 2026",   stmt_date:"5 May 2026",  report_sent:"5 May 2026",  days_creation_to_update:0,  days_stmt_to_report:0,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1305405", client_ref:"MM26/48977", type:"RTC",         status:"Invoice Paid",       created:"5 May 2026",  first_updated:"5 May 2026",   stmt_date:"7 May 2026",  report_sent:"8 May 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1305505", client_ref:"MM26/48990", type:"RTC",         status:"Invoice Paid",       created:"7 May 2026",  first_updated:"7 May 2026",   stmt_date:"9 May 2026",  report_sent:"10 May 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1305605", client_ref:"MM26/49003", type:"RTC",         status:"Invoice Paid",       created:"9 May 2026",  first_updated:"9 May 2026",   stmt_date:"12 May 2026", report_sent:"13 May 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1305705", client_ref:"MM26/49016", type:"RTC",         status:"Invoice Paid",       created:"12 May 2026", first_updated:"12 May 2026",  stmt_date:"14 May 2026", report_sent:"15 May 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1305805", client_ref:"MM26/49029", type:"RTC",         status:"Invoice Paid",       created:"14 May 2026", first_updated:"14 May 2026",  stmt_date:"17 May 2026", report_sent:"19 May 2026", days_creation_to_update:0,  days_stmt_to_report:2,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1305905", client_ref:"MM26/49041", type:"RTC",         status:"Invoice Paid",       created:"16 May 2026", first_updated:"16 May 2026",  stmt_date:"19 May 2026", report_sent:"20 May 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1306005", client_ref:"MM26/49054", type:"RTC",         status:"Invoice Paid",       created:"19 May 2026", first_updated:"19 May 2026",  stmt_date:"21 May 2026", report_sent:"23 May 2026", days_creation_to_update:0,  days_stmt_to_report:2,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1306105", client_ref:"MM26/49067", type:"RTC",         status:"Invoice Paid",       created:"21 May 2026", first_updated:"21 May 2026",  stmt_date:"26 May 2026", report_sent:"29 May 2026", days_creation_to_update:0,  days_stmt_to_report:3,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:false, report_proxy:false, sla_report_target_days:2 },
    { ref:"1306205", client_ref:"MM26/49079", type:"RTC",         status:"Invoiced",           created:"27 May 2026", first_updated:"27 May 2026",  stmt_date:"29 May 2026", report_sent:"30 May 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1306305", client_ref:"MM26/49091", type:"Motor Fraud", status:"Invoice Paid",       created:"5 May 2026",  first_updated:"5 May 2026",   stmt_date:"14 May 2026", report_sent:"23 May 2026", days_creation_to_update:0,  days_stmt_to_report:9,  invoice:600,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1306405", client_ref:"MM26/49104", type:"Motor Fraud", status:"Invoice Paid",       created:"15 May 2026", first_updated:"15 May 2026",  stmt_date:"24 May 2026", report_sent:"3 Jun 2026",  days_creation_to_update:0,  days_stmt_to_report:10, invoice:600,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1306505", client_ref:"MM26/49117", type:"Motor Fraud", status:"Invoice Paid",       created:"22 May 2026", first_updated:"22 May 2026",  stmt_date:"31 May 2026", report_sent:"1 Jun 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:600,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:true,  report_proxy:false, sla_report_target_days:3 },

    // ── June 2026 — full RTC operation ──
    { ref:"1307106", client_ref:"MM26/49131", type:"RTC",         status:"Invoice Paid",       created:"1 Jun 2026",  first_updated:"1 Jun 2026",   stmt_date:"3 Jun 2026",  report_sent:"4 Jun 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1307206", client_ref:"MM26/49143", type:"RTC",         status:"Invoice Paid",       created:"2 Jun 2026",  first_updated:"2 Jun 2026",   stmt_date:"4 Jun 2026",  report_sent:"5 Jun 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1307306", client_ref:"MM26/49156", type:"RTC",         status:"Invoice Paid",       created:"4 Jun 2026",  first_updated:"4 Jun 2026",   stmt_date:"6 Jun 2026",  report_sent:"7 Jun 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1307406", client_ref:"MM26/49169", type:"RTC",         status:"Invoice Paid",       created:"5 Jun 2026",  first_updated:"5 Jun 2026",   stmt_date:"7 Jun 2026",  report_sent:"8 Jun 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1307506", client_ref:"MM26/49182", type:"RTC",         status:"Invoice Paid",       created:"7 Jun 2026",  first_updated:"7 Jun 2026",   stmt_date:"10 Jun 2026", report_sent:"11 Jun 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1307606", client_ref:"MM26/49195", type:"RTC",         status:"Invoice Paid",       created:"9 Jun 2026",  first_updated:"9 Jun 2026",   stmt_date:"11 Jun 2026", report_sent:"12 Jun 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1307706", client_ref:"MM26/49208", type:"RTC",         status:"Invoice Paid",       created:"11 Jun 2026", first_updated:"11 Jun 2026",  stmt_date:"13 Jun 2026", report_sent:"14 Jun 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1307806", client_ref:"MM26/49221", type:"RTC",         status:"Invoice Paid",       created:"13 Jun 2026", first_updated:"13 Jun 2026",  stmt_date:"15 Jun 2026", report_sent:"16 Jun 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1307906", client_ref:"MM26/49234", type:"RTC",         status:"Invoice Paid",       created:"15 Jun 2026", first_updated:"15 Jun 2026",  stmt_date:"17 Jun 2026", report_sent:"18 Jun 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1308006", client_ref:"MM26/49247", type:"RTC",         status:"Invoice Paid",       created:"17 Jun 2026", first_updated:"17 Jun 2026",  stmt_date:"20 Jun 2026", report_sent:"21 Jun 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1308106", client_ref:"MM26/49259", type:"RTC",         status:"Invoice Paid",       created:"19 Jun 2026", first_updated:"19 Jun 2026",  stmt_date:"21 Jun 2026", report_sent:"23 Jun 2026", days_creation_to_update:0,  days_stmt_to_report:2,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1308206", client_ref:"MM26/49272", type:"RTC",         status:"Invoice Paid",       created:"21 Jun 2026", first_updated:"21 Jun 2026",  stmt_date:"24 Jun 2026", report_sent:"26 Jun 2026", days_creation_to_update:0,  days_stmt_to_report:2,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1308306", client_ref:"MM26/49285", type:"RTC",         status:"Invoice Paid",       created:"23 Jun 2026", first_updated:"23 Jun 2026",  stmt_date:"25 Jun 2026", report_sent:"26 Jun 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1308406", client_ref:"MM26/49298", type:"RTC",         status:"Invoiced",           created:"25 Jun 2026", first_updated:"25 Jun 2026",  stmt_date:"28 Jun 2026", report_sent:"30 Jun 2026", days_creation_to_update:0,  days_stmt_to_report:2,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1308506", client_ref:"MM26/49311", type:"RTC",         status:"Invoiced",           created:"27 Jun 2026", first_updated:"27 Jun 2026",  stmt_date:"30 Jun 2026", report_sent:"4 Jul 2026",  days_creation_to_update:0,  days_stmt_to_report:4,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:false, report_proxy:false, sla_report_target_days:2 },
    { ref:"1308606", client_ref:"MM26/49324", type:"Motor Fraud", status:"Invoice Paid",       created:"4 Jun 2026",  first_updated:"4 Jun 2026",   stmt_date:"13 Jun 2026", report_sent:"24 Jun 2026", days_creation_to_update:0,  days_stmt_to_report:11, invoice:600,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1308706", client_ref:"MM26/49337", type:"Motor Theft", status:"Invoice Paid",       created:"12 Jun 2026", first_updated:"12 Jun 2026",  stmt_date:"22 Jun 2026", report_sent:"2 Jul 2026",  days_creation_to_update:0,  days_stmt_to_report:10, invoice:1200, is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:false, report_proxy:false, sla_report_target_days:3 },

    // ── July 2026 (to 21st) ──
    { ref:"1309207", client_ref:"MM26/49351", type:"RTC",         status:"Invoice Paid",       created:"1 Jul 2026",  first_updated:"1 Jul 2026",   stmt_date:"3 Jul 2026",  report_sent:"4 Jul 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1309307", client_ref:"MM26/49364", type:"RTC",         status:"Invoice Paid",       created:"2 Jul 2026",  first_updated:"2 Jul 2026",   stmt_date:"4 Jul 2026",  report_sent:"5 Jul 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1309407", client_ref:"MM26/49377", type:"RTC",         status:"Invoice Paid",       created:"4 Jul 2026",  first_updated:"4 Jul 2026",   stmt_date:"6 Jul 2026",  report_sent:"7 Jul 2026",  days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1309507", client_ref:"MM26/49390", type:"RTC",         status:"Invoice Paid",       created:"7 Jul 2026",  first_updated:"7 Jul 2026",   stmt_date:"9 Jul 2026",  report_sent:"10 Jul 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1309607", client_ref:"MM26/49403", type:"RTC",         status:"Invoice Paid",       created:"9 Jul 2026",  first_updated:"9 Jul 2026",   stmt_date:"11 Jul 2026", report_sent:"12 Jul 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1309707", client_ref:"MM26/49415", type:"RTC",         status:"Invoice Paid",       created:"11 Jul 2026", first_updated:"11 Jul 2026",  stmt_date:"13 Jul 2026", report_sent:"14 Jul 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1309807", client_ref:"MM26/49428", type:"RTC",         status:"Invoice Paid",       created:"14 Jul 2026", first_updated:"14 Jul 2026",  stmt_date:"16 Jul 2026", report_sent:"17 Jul 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1309907", client_ref:"MM26/49441", type:"RTC",         status:"Invoice Paid",       created:"16 Jul 2026", first_updated:"16 Jul 2026",  stmt_date:"18 Jul 2026", report_sent:"19 Jul 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1310007", client_ref:"MM26/49454", type:"RTC",         status:"Invoiced",           created:"18 Jul 2026", first_updated:"18 Jul 2026",  stmt_date:"20 Jul 2026", report_sent:"21 Jul 2026", days_creation_to_update:0,  days_stmt_to_report:1,  invoice:160,  is_rtc_case:true,  sla_ack:true,  sla_contact:true,  sla_update:null,  sla_report:true,  report_proxy:false, sla_report_target_days:2 },
    { ref:"1310107", client_ref:"MM26/49467", type:"Motor Fraud", status:"Invoiced",           created:"8 Jul 2026",  first_updated:"8 Jul 2026",   stmt_date:"17 Jul 2026", report_sent:"",            days_creation_to_update:0,  days_stmt_to_report:null,invoice:560,  is_rtc_case:false, sla_ack:true,  sla_contact:true,  sla_update:true,  sla_report:null,  report_proxy:false, sla_report_target_days:3 }
  ]
};
