// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  DWF LLP
// File:    dwf.js
// Period:  Jan–May 2026
// Updated: 31 May 2026
// GENERATED AUTOMATICALLY FROM TrackOps CSV — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {
  "client_name": "DWF LLP",
  "report_period": "Jan–May 2026",
  "last_updated": "31 May 2026",
  "is_rtc_client": false,
  "total_cases": 32,
  "avg_days_creation_to_update": 1.5,
  "avg_days_creation_to_update_general": 1.5,
  "avg_days_stmt_to_report": 3.9,
  "avg_days_stmt_to_report_rtc": 0,
  "avg_days_stmt_to_report_general": 3.9,
  "sla_ack_pct": 100,
  "sla_contact_pct": 100,
  "sla_update_pct": 91,
  "sla_report_general_pct": 47,
  "sla_report_rtc_pct": null,
  "has_rtc_cases": false,
  "has_general_cases": true,
  "sla_compliance_pct": 85,
  "sla_met": 9,
  "sla_not_met": 10,
  "avg_fee_rtc": 0,
  "avg_fee_general": 309.76,
  "total_fees_rtc": 0,
  "total_fees_general": 9912.4,
  "rtc_case_count": 0,
  "general_case_count": 32,
  "fees_by_type": [
    {
      "type": "Motor Liability",
      "is_rtc": false,
      "case_count": 21,
      "total_fees": 5849.18,
      "avg_fee": 278.53
    },
    {
      "type": "Motor Fraud",
      "is_rtc": false,
      "case_count": 10,
      "total_fees": 3963.22,
      "avg_fee": 396.32
    },
    {
      "type": "Fatality",
      "is_rtc": false,
      "case_count": 1,
      "total_fees": 100,
      "avg_fee": 100
    }
  ],
  "total_invoiced_lineitems": 9912.4,
  "total_lineitem_count": 32,
  "fees_by_item": [
    {
      "item": "Motor Liability Investigation",
      "is_rtc": false,
      "count": 16,
      "total": 4800,
      "avg": 300
    },
    {
      "item": "Stage 1 Investigation",
      "is_rtc": false,
      "count": 7,
      "total": 3450,
      "avg": 492.86
    },
    {
      "item": "Translation services",
      "is_rtc": false,
      "count": 2,
      "total": 457.4,
      "avg": 228.7
    },
    {
      "item": "Interpreter (1/2 day)",
      "is_rtc": false,
      "count": 2,
      "total": 400,
      "avg": 200
    },
    {
      "item": "Interpreter (full day)",
      "is_rtc": false,
      "count": 1,
      "total": 350,
      "avg": 350
    },
    {
      "item": "Stage 2 Investigation",
      "is_rtc": false,
      "count": 1,
      "total": 200,
      "avg": 200
    },
    {
      "item": "Locus Report",
      "is_rtc": false,
      "count": 1,
      "total": 100,
      "avg": 100
    },
    {
      "item": "Cold Calls",
      "is_rtc": false,
      "count": 1,
      "total": 80,
      "avg": 80
    },
    {
      "item": "Failed Appointment",
      "is_rtc": false,
      "count": 1,
      "total": 75,
      "avg": 75
    }
  ],
  "monthly": [
    {
      "month": "Jan",
      "month_num": 1,
      "case_count": 5,
      "case_count_rtc": 0,
      "case_count_general": 5,
      "total_fees": 1800,
      "ave_fees": 360,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0.8,
      "ave_days_creation_to_update_general": 0.8,
      "ave_days_stmt_to_report": 2.8,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 2.8,
      "sla_ack_pct": 100,
      "sla_ack_met": 5,
      "sla_ack_n": 5,
      "sla_contact_pct": 100,
      "sla_contact_met": 5,
      "sla_contact_n": 5,
      "sla_update_pct": 100,
      "sla_update_met": 4,
      "sla_update_n": 4,
      "sla_report_general_pct": 50,
      "sla_report_general_met": 2,
      "sla_report_general_n": 4,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 88,
      "sla_met": 2,
      "sla_not_met": 2
    },
    {
      "month": "Feb",
      "month_num": 2,
      "case_count": 4,
      "case_count_rtc": 0,
      "case_count_general": 4,
      "total_fees": 2407.4,
      "ave_fees": 602,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 1,
      "ave_days_creation_to_update_general": 1,
      "ave_days_stmt_to_report": 3.8,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 3.8,
      "sla_ack_pct": 100,
      "sla_ack_met": 4,
      "sla_ack_n": 4,
      "sla_contact_pct": 100,
      "sla_contact_met": 4,
      "sla_contact_n": 4,
      "sla_update_pct": 100,
      "sla_update_met": 4,
      "sla_update_n": 4,
      "sla_report_general_pct": 50,
      "sla_report_general_met": 2,
      "sla_report_general_n": 4,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 88,
      "sla_met": 2,
      "sla_not_met": 2
    },
    {
      "month": "Mar",
      "month_num": 3,
      "case_count": 12,
      "case_count_rtc": 0,
      "case_count_general": 12,
      "total_fees": 2255,
      "ave_fees": 188,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 2.8,
      "ave_days_creation_to_update_general": 2.8,
      "ave_days_stmt_to_report": 3.6,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 3.6,
      "sla_ack_pct": 100,
      "sla_ack_met": 12,
      "sla_ack_n": 12,
      "sla_contact_pct": 100,
      "sla_contact_met": 12,
      "sla_contact_n": 12,
      "sla_update_pct": 75,
      "sla_update_met": 6,
      "sla_update_n": 8,
      "sla_report_general_pct": 60,
      "sla_report_general_met": 3,
      "sla_report_general_n": 5,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 84,
      "sla_met": 3,
      "sla_not_met": 2
    },
    {
      "month": "Apr",
      "month_num": 4,
      "case_count": 7,
      "case_count_rtc": 0,
      "case_count_general": 7,
      "total_fees": 2850,
      "ave_fees": 407,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 1,
      "ave_days_creation_to_update_general": 1,
      "ave_days_stmt_to_report": 6,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 6,
      "sla_ack_pct": 100,
      "sla_ack_met": 7,
      "sla_ack_n": 7,
      "sla_contact_pct": 100,
      "sla_contact_met": 7,
      "sla_contact_n": 7,
      "sla_update_pct": 100,
      "sla_update_met": 5,
      "sla_update_n": 5,
      "sla_report_general_pct": 20,
      "sla_report_general_met": 1,
      "sla_report_general_n": 5,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 80,
      "sla_met": 1,
      "sla_not_met": 4
    },
    {
      "month": "May",
      "month_num": 5,
      "case_count": 4,
      "case_count_rtc": 0,
      "case_count_general": 4,
      "total_fees": 600,
      "ave_fees": 150,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0.5,
      "ave_days_creation_to_update_general": 0.5,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": 100,
      "sla_ack_met": 4,
      "sla_ack_n": 4,
      "sla_contact_pct": 100,
      "sla_contact_met": 4,
      "sla_contact_n": 4,
      "sla_update_pct": 100,
      "sla_update_met": 2,
      "sla_update_n": 2,
      "sla_report_general_pct": 100,
      "sla_report_general_met": 1,
      "sla_report_general_n": 1,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 100,
      "sla_met": 1,
      "sla_not_met": 0
    },
    {
      "month": "Jun",
      "month_num": 6,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Jul",
      "month_num": 7,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Aug",
      "month_num": 8,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Sep",
      "month_num": 9,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Oct",
      "month_num": 10,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Nov",
      "month_num": 11,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Dec",
      "month_num": 12,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    }
  ],
  "cases": [
    {
      "ref": "1165605",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Interview date / time TBC",
      "created": "20 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1165005",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "19 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1164205",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Await PH response / HUB done",
      "created": "18 May 2026",
      "first_updated": "19 May 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 1,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1161405",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "6 May 2026",
      "first_updated": "6 May 2026",
      "stmt_date": "14 May 2026",
      "report_sent": "14 May 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 0,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1158804",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "24 Apr 2026",
      "first_updated": "27 Apr 2026",
      "stmt_date": "12 May 2026",
      "report_sent": "20 May 2026",
      "days_creation_to_update": 3,
      "days_stmt_to_report": 8,
      "invoice": 600,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1157504",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "20 Apr 2026",
      "first_updated": "20 Apr 2026",
      "stmt_date": "27 Apr 2026",
      "report_sent": "8 May 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 11,
      "invoice": 350,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1156004",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "15 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1155004",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "13 Apr 2026",
      "first_updated": "14 Apr 2026",
      "stmt_date": "23 Apr 2026",
      "report_sent": "27 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 4,
      "invoice": 600,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1154804",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "13 Apr 2026",
      "first_updated": "13 Apr 2026",
      "stmt_date": "15 Apr 2026",
      "report_sent": "21 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 6,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1151204",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "7 Apr 2026",
      "first_updated": "8 Apr 2026",
      "stmt_date": "27 Apr 2026",
      "report_sent": "28 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 1,
      "invoice": 600,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1149804",
      "client_ref": null,
      "type": "Fatality",
      "status": "Invoiced",
      "created": "1 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 100,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1149003",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "30 Mar 2026",
      "first_updated": "8 Apr 2026",
      "stmt_date": "13 Apr 2026",
      "report_sent": "22 Apr 2026",
      "days_creation_to_update": 9,
      "days_stmt_to_report": 9,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1148703",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Statement obtained",
      "created": "27 Mar 2026",
      "first_updated": "27 Mar 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 0,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1148603",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "27 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 80,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1148403",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "26 Mar 2026",
      "first_updated": "28 Mar 2026",
      "stmt_date": "11 Apr 2026",
      "report_sent": "14 Apr 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 3,
      "invoice": 600,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1148003",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "25 Mar 2026",
      "first_updated": "27 Mar 2026",
      "stmt_date": "13 May 2026",
      "report_sent": "13 May 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 0,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1147803",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Closed",
      "created": "25 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1145703",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Closed",
      "created": "18 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1144103",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "11 Mar 2026",
      "first_updated": "17 Mar 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 6,
      "days_stmt_to_report": null,
      "invoice": 75,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1143903",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "11 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1143803",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "10 Mar 2026",
      "first_updated": "11 Mar 2026",
      "stmt_date": "17 Mar 2026",
      "report_sent": "19 Mar 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 2,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1143603",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "10 Mar 2026",
      "first_updated": "11 Mar 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 1,
      "days_stmt_to_report": null,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1142203",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "4 Mar 2026",
      "first_updated": "5 Mar 2026",
      "stmt_date": "6 Mar 2026",
      "report_sent": "10 Mar 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 4,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1140502",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "23 Feb 2026",
      "first_updated": "23 Feb 2026",
      "stmt_date": "26 Feb 2026",
      "report_sent": "2 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 4,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1136002",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "6 Feb 2026",
      "first_updated": "9 Feb 2026",
      "stmt_date": "21 Apr 2026",
      "report_sent": "23 Apr 2026",
      "days_creation_to_update": 3,
      "days_stmt_to_report": 2,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1135302",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "4 Feb 2026",
      "first_updated": "5 Feb 2026",
      "stmt_date": "10 Feb 2026",
      "report_sent": "13 Feb 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 3,
      "invoice": 1069.18,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1135202",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "4 Feb 2026",
      "first_updated": "4 Feb 2026",
      "stmt_date": "12 Feb 2026",
      "report_sent": "18 Feb 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 6,
      "invoice": 738.22,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1132301",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "20 Jan 2026",
      "first_updated": "20 Jan 2026",
      "stmt_date": "22 Jan 2026",
      "report_sent": "26 Jan 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 4,
      "invoice": 400,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1132201",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "19 Jan 2026",
      "first_updated": "20 Jan 2026",
      "stmt_date": "23 Jan 2026",
      "report_sent": "27 Jan 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 4,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1131501",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "14 Jan 2026",
      "first_updated": "14 Jan 2026",
      "stmt_date": "22 Jan 2026",
      "report_sent": "23 Jan 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 1,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1130701",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "12 Jan 2026",
      "first_updated": "14 Jan 2026",
      "stmt_date": "21 Jan 2026",
      "report_sent": "23 Jan 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 2,
      "invoice": 500,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1130401",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "12 Jan 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    }
  ]
};
