// Converted from cases_2026-01-01_-_2026-02-28_1772791276.csv
// Rows: 9

const cases = [
  {
    "Case Number": "1140502",
    "Reference No.": "2043474-4913",
    "Reference No. 2": "",
    "Reference No. 3": "",
    "Case Status": "Reviewed, signed off & sent",
    "Last Status Change": "2026-03-02 13:37:56",
    "Referral": "",
    "Subject": ", Care Today (Childrens Services) Ltd",
    "Company Location": "",
    "Client": "DWF LLP",
    "Client Location": "Liverpool Office",
    "Primary Client Contact": "Akate, Ayishetu",
    "Primary Investigator": "Wood, Andy",
    "Primary Case Manager": "Richardson, Emily",
    "Primary Salesperson": "Booker, David",
    "Case Type": "Motor Liability",
    "Case Type (Tag)": "ML",
    "Case Region": "Local",
    "Case Country": "GB",
    "Case State": "",
    "Case Location": "Stockport SK2",
    "Budget (Hours)": "0.00",
    "Budget (Money)": "0.00",
    "Expense Hours": "0.00",
    "Expense Total": "0.00",
    "Invoice Estimate": "0.00",
    "Invoice Total": "0.00",
    "Services": "Motor Liability",
    "Flags": "URGENT, Motor Liability",
    "Due Date": "2026-02-27",
    "Scheduling Notes": "We would be grateful if you could please secure Chantelle Braham's liability statement by 03/03/2026.",
    "Admin Notes": "",
    "Date Created": "2026-02-23",
    "Date Created (System)": "2026-02-23 11:02:35",
    "Date Opened": "opened_at",
    "Date Completed": "completed_at",
    "Date Closed": "closed_at",
    "Date Updated": "2026-03-02 13:37:56",
    "Last Case Update": "2026-03-02 13:37:50",
    "Avg. Rating": "",
    "Notes/Instructions": "urgent liab statement - if cannot do face to face video will suffice in view of time constraints \r\n\r\nany cctv/dash-cam footage?",
    "Ambulance attended": "N/A",
    "Claimant Name": "",
    "Client Reference": "",
    "Date client first updated?": "2026-02-23",
    "Date of Surveillance": "",
    "Date Report sent to client?": "2026-03-02",
    "Date statement obtained": "2026-02-26",
    "Incident Circumstances": "TP took bend too quickly collided with PHV",
    "Incident Date": "2025-07-16",
    "Incident Location": "unnamed country road, near Meerbrook, Leek",
    "Incident Time": "14.30",
    "Insured Name": "",
    "Insurer": "Allianz",
    "Insurer Brand": "Allianz",
    "Police Attendance": "N/A"
  },
  {
    "Case Number": "1136002",
    "Reference No.": "2046205-35/7703519(99050883)",
    "Reference No. 2": "",
    "Reference No. 3": "",
    "Case Status": "Await PH response / HUB done",
    "Last Status Change": "2026-02-27 10:20:28",
    "Referral": "",
    "Subject": ", P.C. Howard Limited",
    "Company Location": "",
    "Client": "DWF LLP",
    "Client Location": "Liverpool Office",
    "Primary Client Contact": "Patel, Nitisha",
    "Primary Investigator": "Dargan, Jeremy",
    "Primary Case Manager": "Richardson, Emily",
    "Primary Salesperson": "Booker, David",
    "Case Type": "Motor Liability",
    "Case Type (Tag)": "ML",
    "Case Region": "Out of Area",
    "Case Country": "GB",
    "Case State": "",
    "Case Location": "Northampton",
    "Budget (Hours)": "0.00",
    "Budget (Money)": "0.00",
    "Expense Hours": "0.00",
    "Expense Total": "0.00",
    "Invoice Estimate": "0.00",
    "Invoice Total": "0.00",
    "Services": "Motor Liability",
    "Flags": "Motor Liability",
    "Due Date": "",
    "Scheduling Notes": "We would be grateful if you could please secure Mr Townsend liability statement which must be filed at Court by 27/03/2026.",
    "Admin Notes": "",
    "Date Created": "2026-02-06",
    "Date Created (System)": "2026-02-06 15:45:49",
    "Date Opened": "opened_at",
    "Date Completed": "completed_at",
    "Date Closed": "closed_at",
    "Date Updated": "2026-03-05 09:04:48",
    "Last Case Update": "2026-03-05 09:04:48",
    "Avg. Rating": "",
    "Notes/Instructions": "liab statement",
    "Ambulance attended": "N/A",
    "Claimant Name": "",
    "Client Reference": "",
    "Date client first updated?": "",
    "Date of Surveillance": "",
    "Date Report sent to client?": "",
    "Date statement obtained": "",
    "Incident Circumstances": "RAB changing lanes collision",
    "Incident Date": "2025-04-09",
    "Incident Location": "Weedon Road Northampton rab",
    "Incident Time": "16.12",
    "Insured Name": "",
    "Insurer": "QBE",
    "Insurer Brand": "QBE",
    "Police Attendance": "N/A"
  },
  {
    "Case Number": "1135302",
    "Reference No.": "2005740-20053",
    "Reference No. 2": "",
    "Reference No. 3": "",
    "Case Status": "Invoiced",
    "Last Status Change": "2026-02-18 17:25:21",
    "Referral": "",
    "Subject": "Hussain, Mazhar",
    "Company Location": "Halifax",
    "Client": "DWF LLP",
    "Client Location": "Liverpool Office",
    "Primary Client Contact": "Essilfie, Paa",
    "Primary Investigator": "Wood, Andy",
    "Primary Case Manager": "Richardson, Emily",
    "Primary Salesperson": "Booker, David",
    "Case Type": "Motor Liability",
    "Case Type (Tag)": "ML",
    "Case Region": "Local",
    "Case Country": "GB",
    "Case State": "",
    "Case Location": "Oldham  OL4",
    "Budget (Hours)": "0.00",
    "Budget (Money)": "0.00",
    "Expense Hours": "0.00",
    "Expense Total": "208.10",
    "Invoice Estimate": "1496.12",
    "Invoice Total": "1043.02",
    "Services": "Motor Liability",
    "Flags": "URGENT, Motor Liability",
    "Due Date": "",
    "Scheduling Notes": "We are writing to formally instruct you to take a liability in dispute witness statement from Mr Mazhar Hussain, relation to the road traffic accident involving the his motor vehicle, registration number, SY65XMR",
    "Admin Notes": "The Witness evidence is due on 16th February 2026\r\nCourt Hearing is on 8th January 2026.",
    "Date Created": "2026-02-04",
    "Date Created (System)": "2026-02-04 17:07:07",
    "Date Opened": "opened_at",
    "Date Completed": "completed_at",
    "Date Closed": "closed_at",
    "Date Updated": "2026-02-18 17:25:57",
    "Last Case Update": "2026-02-18 17:25:57",
    "Avg. Rating": "",
    "Notes/Instructions": "liab statement\r\ntranslator will be required",
    "Ambulance attended": "N/A",
    "Claimant Name": "",
    "Client Reference": "",
    "Date client first updated?": "2026-02-05",
    "Date of Surveillance": "",
    "Date Report sent to client?": "2026-02-13",
    "Date statement obtained": "2026-02-10",
    "Incident Circumstances": "PH collided with TP parked vehicle",
    "Incident Date": "2023-10-21",
    "Incident Location": "Manchester Road, Oldham, OL9 7PG",
    "Incident Time": "16.33",
    "Insured Name": "",
    "Insurer": "West Bay Insurance PLC",
    "Insurer Brand": "West Bay Insurance PLC",
    "Police Attendance": "N/A"
  },
  {
    "Case Number": "1135202",
    "Reference No.": "2019226-1557",
    "Reference No. 2": "",
    "Reference No. 3": "",
    "Case Status": "Invoiced",
    "Last Status Change": "2026-02-18 17:21:01",
    "Referral": "",
    "Subject": "SGK Distribution",
    "Company Location": "Halifax",
    "Client": "DWF LLP",
    "Client Location": "Manchester office",
    "Primary Client Contact": "McIntyre, Sarah",
    "Primary Investigator": "Lawless, Jim",
    "Primary Case Manager": "Richardson, Emily",
    "Primary Salesperson": "Booker, David",
    "Case Type": "Motor Fraud",
    "Case Type (Tag)": "MO",
    "Case Region": "Out of Area",
    "Case Country": "GB",
    "Case State": "",
    "Case Location": "B67?",
    "Budget (Hours)": "0.00",
    "Budget (Money)": "0.00",
    "Expense Hours": "0.00",
    "Expense Total": "187.20",
    "Invoice Estimate": "1203.06",
    "Invoice Total": "885.86",
    "Services": "Full Investigation",
    "Flags": "Suspected Fraud",
    "Due Date": "",
    "Scheduling Notes": "Please would you arrange to interview and obtain a CPR Compliant witness statement from Mr Prahlad Singh with the assistance of a translator.\r\n\r\nEnglish is not Mr Singh's first language and a Punjabi interpreter will be required.\r\n\r\nMr Singh is employed by SGK Distribution, who are the Insured in this claim and they have agreed to facilitate the appointment/interview with him.\r\n\r\nPlease would you contact Deep Karra – head of driver compliance at SGK. Can you contact initially by email and he has confirmed he will call you back.\r\n\r\nEmail:  deep@sgkdistribution.co.uk\r\n\r\nIn the alternative his mobile phone number is: 07572285645",
    "Admin Notes": "Liability is denied.  The Insured driver has stated he was turning right and stopped to turn onto Windmill from Hernes and the bike RV25 LZX drove into the back of the van, damaging the back door and his bike.  Claimant is to blame for accident.\r\n\r\nClaimant is a Brazilian Motorcycle Courier and is represented by Bond Turner !",
    "Date Created": "2026-02-04",
    "Date Created (System)": "2026-02-04 15:00:59",
    "Date Opened": "opened_at",
    "Date Completed": "completed_at",
    "Date Closed": "closed_at",
    "Date Updated": "2026-02-26 17:26:52",
    "Last Case Update": "2026-02-18 17:21:42",
    "Avg. Rating": "",
    "Notes/Instructions": "*WITNESS EXCHANGE IS 26 FEB*\r\n\r\nstatement from PH driver",
    "Ambulance attended": "N/A",
    "Claimant Name": "",
    "Client Reference": "",
    "Date client first updated?": "2026-02-04",
    "Date of Surveillance": "",
    "Date Report sent to client?": "2026-02-18",
    "Date statement obtained": "2026-02-12",
    "Incident Circumstances": "TP motorcyclist drove into rear of PH driver when stationary",
    "Incident Date": "2025-03-17",
    "Incident Location": "Windmill from Hernes Way Welwyn Garden City",
    "Incident Time": "14.30",
    "Insured Name": "",
    "Insurer": "Direct Commercial Ltd",
    "Insurer Brand": "Direct Commercial Ltd",
    "Police Attendance": "N/A"
  },
  {
    "Case Number": "1132301",
    "Reference No.": "2043474-2869/9904554(9904451)",
    "Reference No. 2": "",
    "Reference No. 3": "",
    "Case Status": "Invoiced",
    "Last Status Change": "2026-01-26 11:51:43",
    "Referral": "",
    "Subject": "Holmes, Garry",
    "Company Location": "Chelmsford",
    "Client": "DWF LLP",
    "Client Location": "Liverpool Office",
    "Primary Client Contact": "Akate, Ayishetu",
    "Primary Investigator": "Hayes, Ivan",
    "Primary Case Manager": "Richardson, Emily",
    "Primary Salesperson": "Booker, David",
    "Case Type": "Motor Fraud",
    "Case Type (Tag)": "MO",
    "Case Region": "Out of Area",
    "Case Country": "GB",
    "Case State": "",
    "Case Location": "BUXTON, SK17",
    "Budget (Hours)": "0.00",
    "Budget (Money)": "0.00",
    "Expense Hours": "0.00",
    "Expense Total": "100.00",
    "Invoice Estimate": "780.00",
    "Invoice Total": "480.00",
    "Services": "Full Investigation",
    "Flags": "URGENT, Suspected Fraud",
    "Due Date": "2026-01-23",
    "Scheduling Notes": "Driver has no idea of the alleged accident. \r\nThe Defendant denies involvement in the accident which is the subject\r\nmatter of this claim. The Defendant has no knowledge of the accident or\r\nthe circumstances and cannot respond to the Particulars of Negligence,\r\nwhich are denied in their entirety",
    "Admin Notes": "IH video interview - case to be back before 23/1/26",
    "Date Created": "2026-01-20",
    "Date Created (System)": "2026-01-20 11:06:41",
    "Date Opened": "opened_at",
    "Date Completed": "completed_at",
    "Date Closed": "closed_at",
    "Date Updated": "2026-02-10 13:13:06",
    "Last Case Update": "2026-01-30 15:48:43",
    "Avg. Rating": "",
    "Notes/Instructions": "statement from PH\r\nWe would be grateful if you could please secure Garry Holmes liability statement by \r\nPlease obtain any footage/CCTV from the driver if there is any",
    "Ambulance attended": "N/A",
    "Claimant Name": "",
    "Client Reference": "",
    "Date client first updated?": "2026-01-20",
    "Date of Surveillance": "",
    "Date Report sent to client?": "2026-01-26",
    "Date statement obtained": "2026-01-22",
    "Incident Circumstances": "PH driver collided with TPV - driver denies",
    "Incident Date": "2024-10-07",
    "Incident Location": "117, Buxton Road, Disley, Stockport, Cheshire, SK122HA",
    "Incident Time": "00:00hrs",
    "Insured Name": "",
    "Insurer": "Allianz",
    "Insurer Brand": "Allianz",
    "Police Attendance": "N/A"
  },
  {
    "Case Number": "1132201",
    "Reference No.": "2042977-2432/9904554(9904451)",
    "Reference No. 2": "",
    "Reference No. 3": "",
    "Case Status": "Invoiced",
    "Last Status Change": "2026-01-28 16:32:55",
    "Referral": "",
    "Subject": "Woods, Elliot",
    "Company Location": "Salisbury",
    "Client": "DWF LLP",
    "Client Location": "Liverpool Office",
    "Primary Client Contact": "Akate, Ayishetu",
    "Primary Investigator": "Hunter, Mick",
    "Primary Case Manager": "Richardson, Emily",
    "Primary Salesperson": "Booker, David",
    "Case Type": "Motor Liability",
    "Case Type (Tag)": "ML",
    "Case Region": "Local",
    "Case Country": "GB",
    "Case State": "",
    "Case Location": "SOUTHAMPTON SO17",
    "Budget (Hours)": "0.00",
    "Budget (Money)": "0.00",
    "Expense Hours": "0.00",
    "Expense Total": "120.00",
    "Invoice Estimate": "660.00",
    "Invoice Total": "360.00",
    "Services": "Motor Liability",
    "Flags": "Motor Liability",
    "Due Date": "",
    "Scheduling Notes": "We would be grateful if you could please secure Elliot Woods liability statement by 29/01/2026.\r\nPlease obtain any footage/CCTV from the driver if there is any.",
    "Admin Notes": "",
    "Date Created": "2026-01-19",
    "Date Created (System)": "2026-01-19 17:13:24",
    "Date Opened": "opened_at",
    "Date Completed": "completed_at",
    "Date Closed": "closed_at",
    "Date Updated": "2026-01-28 16:33:26",
    "Last Case Update": "2026-01-28 16:33:26",
    "Avg. Rating": "",
    "Notes/Instructions": "liab statement",
    "Ambulance attended": "N/A",
    "Claimant Name": "",
    "Client Reference": "",
    "Date client first updated?": "2026-01-20",
    "Date of Surveillance": "",
    "Date Report sent to client?": "2026-01-27",
    "Date statement obtained": "2026-01-23",
    "Incident Circumstances": "PH turning right in right only lane TP collided with rear of PHV",
    "Incident Date": "2024-04-23",
    "Incident Location": "Thomas Lewis Way & Saint Denys Road, A3035 Southampton",
    "Incident Time": "00:00hrs",
    "Insured Name": "",
    "Insurer": "Direct Line",
    "Insurer Brand": "Direct Line",
    "Police Attendance": "N/A"
  },
  {
    "Case Number": "1131501",
    "Reference No.": "2041764-2697",
    "Reference No. 2": "",
    "Reference No. 3": "",
    "Case Status": "Invoiced",
    "Last Status Change": "2026-01-23 16:58:40",
    "Referral": "",
    "Subject": "Abdalqadir, Rawand",
    "Company Location": "Salisbury",
    "Client": "DWF LLP",
    "Client Location": "Liverpool Office",
    "Primary Client Contact": "Essilfie, Paa",
    "Primary Investigator": "Hunter, Mick",
    "Primary Case Manager": "Richardson, Emily",
    "Primary Salesperson": "Booker, David",
    "Case Type": "Motor Liability",
    "Case Type (Tag)": "ML",
    "Case Region": "Out of Area",
    "Case Country": "GB",
    "Case State": "",
    "Case Location": "Cardiff, CF11",
    "Budget (Hours)": "0.00",
    "Budget (Money)": "0.00",
    "Expense Hours": "0.00",
    "Expense Total": "120.00",
    "Invoice Estimate": "660.00",
    "Invoice Total": "360.00",
    "Services": "Motor Liability",
    "Flags": "URGENT, Motor Liability",
    "Due Date": "2026-01-21",
    "Scheduling Notes": "Witness statement due 28th January",
    "Admin Notes": "",
    "Date Created": "2026-01-14",
    "Date Created (System)": "2026-01-14 11:43:49",
    "Date Opened": "opened_at",
    "Date Completed": "completed_at",
    "Date Closed": "closed_at",
    "Date Updated": "2026-02-05 16:40:32",
    "Last Case Update": "2026-01-23 16:59:13",
    "Avg. Rating": "100.00",
    "Notes/Instructions": "​&lt;DWFhsq/@@E23@@/&gt; Good Morning,\r\n\r\nWe are writing to formally instruct you to take a liability in dispute witness statement from Mr Rawand Abdalqadir, relation to the road traffic accident involving the his motor vehicle,  Ford B-Mx Zetec, registration number, PF14OKG.\r\n\r\n\r\nClaimant's Version of Events\r\n\r\nThe Claimant claims within the particulars of claim that they were driving along a narrow lane on Maes-Y-Bryn Road, Pontprennau Cardiff, When the Defendant collided with the Claimant's correctly proceeding vehicle.\r\n\r\n\r\nDefendant's Version of Events\r\n\r\nThe Defendant's denies that the collision occurred as alleged within the Particulars of Claim and will aver that the Defendant was correctly proceeding on a narrow road when the Claimant approached without due caution and collided with the Defendant's vehicle.\r\n\r\n\r\nContact Details:\r\n\r\nrawandmhamad422@gmail.com&lt;mailto:rawandmhamad422@gmail.com&gt;\r\n\r\n07918155651\r\n\r\n224 Ninian Park Road, Cardiff, CF11 6JG, Cardiff, GB\r\n\r\nPlease ensure that the witness statements are comprehensive and cover all relevant details of the incident.\r\n\r\n\r\n\r\n\r\nPaa Essilfie Paralegal\r\nFraud, Credit Hire & Motor\r\nD +44 151 907 3089 E 683089\r\n\r\nDWF Law LLP\r\n5 St Paul's Square Old Hall Street Liverpool L3 9AE\r\nT +44 333 320 2220 F +44 333 320 4440\r\n\r\nWe care about the environment - please think before you print \r\n\r\nIMPORTANT PLEASE READ: This email and its contents are confidential and may be legally privileged. Only access \r\nby the intended recipient is authorised. If you are not the intended recipient, please notify the sender \r\nimmediately and destroy this email and any attachments.  Any unauthorised copying, disclosure or distribution \r\nof the material in this email and any attachments is strictly forbidden.  Any liability (in negligence, contract \r\nor otherwise) arising from any third party taking action or refraining from acting on the basis of any information \r\ncontained in this e-mail or its attachments is hereby excluded.  Copyright in this e-mail (and any attachments \r\ncreated by DWF Law LLP), belongs to DWF Law LLP.  DWF Law LLP does not accept service of documents by e-mail, \r\nand the use of e-mail does not imply that it is willing to do so, unless otherwise expressly agreed.\r\n\r\nDATA PROTECTION: whilst interacting with you, it may be necessary for DWF to collect and process personal data that is about you. \r\nIn order to obtain detailed information on the purposes and principles of personal data processing as well as your data subject rights \r\nresulting from it, please refer to our Privacy Policy at https://dwfgroup.com/en/notices/dwf-privacy-notice.\r\n \r\nDWF Law LLP is a limited liability partnership registered in England and Wales (registered number OC423384) with \r\nits registered office at 1 Scott Place, 2 Hardman Street, Manchester M3 3AA. DWF Law LLP is authorised and regulated \r\nby the Solicitors Regulation Authority as an Alternative Business Structure. Our professional code of conduct can \r\nbe accessed at http://www.sra.org.uk. DWF Law LLP is listed on the Financial Services Register as an Exempt Professional \r\nFirm, able to carry out certain insurance mediation activities (regulated by the Solicitors Regulation Authority). \r\nThe term 'Partner' is used to refer to a Member of DWF Law LLP or an employee or consultant with equivalent standing \r\nand qualification. A list of the Members of DWF Law LLP and of the Non-Members who are designated as Partners is open \r\nto inspection at our registered office, 1 Scott Place, 2 Hardman Street, Manchester M3 3AA. The recipient of this \r\ne-mail will, at all times, be dealing with DWF Law LLP unless it is clear from the context or specifically attributed \r\nto another DWF group entity.",
    "Ambulance attended": "N/A",
    "Claimant Name": "",
    "Client Reference": "",
    "Date client first updated?": "2026-01-14",
    "Date of Surveillance": "",
    "Date Report sent to client?": "2026-01-23",
    "Date statement obtained": "2026-01-22",
    "Incident Circumstances": "Narrow Road Collision",
    "Incident Date": "2024-01-26",
    "Incident Location": "Maes-Y-Bryn Road, Pontprennau Cardiff",
    "Incident Time": "00:00hrs",
    "Insured Name": "",
    "Insurer": "Marshmallow",
    "Insurer Brand": "TBC",
    "Police Attendance": "N/A"
  },
  {
    "Case Number": "1130701",
    "Reference No.": "2041214-6007",
    "Reference No. 2": "",
    "Reference No. 3": "",
    "Case Status": "Invoiced",
    "Last Status Change": "2026-01-23 16:43:09",
    "Referral": "",
    "Subject": "Lammy, Jaleesa",
    "Company Location": "Salisbury",
    "Client": "DWF LLP",
    "Client Location": "Birmingham",
    "Primary Client Contact": "Jevons, Gavin",
    "Primary Investigator": "Hunter, Mick",
    "Primary Case Manager": "Richardson, Emily",
    "Primary Salesperson": "Booker, David",
    "Case Type": "Motor Liability",
    "Case Type (Tag)": "ML",
    "Case Region": "Out of Area",
    "Case Country": "GB",
    "Case State": "",
    "Case Location": "Newport, Gwent, NP19",
    "Budget (Hours)": "0.00",
    "Budget (Money)": "0.00",
    "Expense Hours": "0.00",
    "Expense Total": "220.00",
    "Invoice Estimate": "1100.00",
    "Invoice Total": "600.00",
    "Services": "Motor Liability",
    "Flags": "URGENT, Motor Liability",
    "Due Date": "",
    "Scheduling Notes": "Our primary aim to investigate liability to ascertain whether we should continue defending the\r\nClaimant's claim on the basis this was a rear end shunt (and the Claimant was therefore the author\r\nof her own misfortune), or, whether there is merit to the Claimant's contention that the insured pulled\r\nin front of her at the last minute causing the collision.",
    "Admin Notes": "Please can you look to establish contact with the insured driver to ascertain whether she would be\r\nprepared to provide a CPR compliant statement in support of liability\r\nIf you cannot establish contact, please can you document any attempts made at contact.",
    "Date Created": "2026-01-12",
    "Date Created (System)": "2026-01-12 11:33:06",
    "Date Opened": "opened_at",
    "Date Completed": "completed_at",
    "Date Closed": "closed_at",
    "Date Updated": "2026-01-23 16:44:09",
    "Last Case Update": "2026-01-23 16:44:09",
    "Avg. Rating": "",
    "Notes/Instructions": "liab statement",
    "Ambulance attended": "N/A",
    "Claimant Name": "",
    "Client Reference": "",
    "Date client first updated?": "2026-01-14",
    "Date of Surveillance": "",
    "Date Report sent to client?": "2026-01-23",
    "Date statement obtained": "2026-01-21",
    "Incident Circumstances": "4 car concertina collision",
    "Incident Date": "2023-11-09",
    "Incident Location": "A48 in Cardiff",
    "Incident Time": "00:00hrs",
    "Insured Name": "",
    "Insurer": "Aviva",
    "Insurer Brand": "Aviva",
    "Police Attendance": "N/A"
  },
  {
    "Case Number": "1130401",
    "Reference No.": "2041672-2853/16815(GRP)",
    "Reference No. 2": "",
    "Reference No. 3": "",
    "Case Status": "Invoiced",
    "Last Status Change": "2026-01-28 16:35:24",
    "Referral": "",
    "Subject": "Hughes, Trefor",
    "Company Location": "Head Office",
    "Client": "DWF LLP",
    "Client Location": "Liverpool Office",
    "Primary Client Contact": "Nikolaisen, Zoe",
    "Primary Investigator": "Booker, David",
    "Primary Case Manager": "Mitchell, Kate",
    "Primary Salesperson": "Booker, David",
    "Case Type": "Motor Liability",
    "Case Type (Tag)": "ML",
    "Case Region": "Local",
    "Case Country": "GB",
    "Case State": "",
    "Case Location": "Northampton, NN4",
    "Budget (Hours)": "0.00",
    "Budget (Money)": "0.00",
    "Expense Hours": "0.00",
    "Expense Total": "0.00",
    "Invoice Estimate": "360.00",
    "Invoice Total": "360.00",
    "Services": "Motor Liability",
    "Flags": "URGENT, Motor Liability",
    "Due Date": "2026-01-16",
    "Scheduling Notes": "Would you kindly obtain a CPR compliant signed and dated liability statement from Mrs Krista Carr in relation to the above matter. If you are able to obtain contact details for the driver of the vehicle at the front (ahead of the Claimant's vehicle) from Mrs Carr, please let us know.",
    "Admin Notes": "Liability for the collision is disputed. The Claimant alleges that Mr Trefor Hughes (driver of the vehicle Mrs Carr was travelling in) failed to maintain a safe braking distance causing the collision. The pleadings are brief, but from pre-issue correspondence we can see that the Claimant alleges that we have shunted them into a vehicle in front.\r\n\r\n \r\n\r\nMr Trefor Hughes, asserts that the Claimant’s vehicle abruptly cut in front of his own and then braked suddenly due to a stationary vehicle directly ahead, thereby reducing the available stopping distance. Mr Hughes has provided a statement previously which is why we are not asking you to obtain one from him also.",
    "Date Created": "2026-01-12",
    "Date Created (System)": "2026-01-12 10:25:57",
    "Date Opened": "opened_at",
    "Date Completed": "completed_at",
    "Date Closed": "closed_at",
    "Date Updated": "2026-02-05 15:59:52",
    "Last Case Update": "2026-01-26 14:27:44",
    "Avg. Rating": "100.00",
    "Notes/Instructions": "URGENT statement from passenger",
    "Ambulance attended": "N/A",
    "Claimant Name": "",
    "Client Reference": "",
    "Date client first updated?": "",
    "Date of Surveillance": "",
    "Date Report sent to client?": "",
    "Date statement obtained": "",
    "Incident Circumstances": "PH hit rear of TPV",
    "Incident Date": "2025-02-07",
    "Incident Location": "Nene Valley Way Hardingstone",
    "Incident Time": "00:00hrs",
    "Insured Name": "",
    "Insurer": "Tesco",
    "Insurer Brand": "Tesco",
    "Police Attendance": "N/A"
  }
];

export default cases;
