// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  First Central Insurance
// File:    firstcentral.js
// Period:  Jan–Dec 2026
// Updated: 4 Aug 2026
// GENERATED AUTOMATICALLY — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {

  client_name:                  "First Central Insurance",
  report_period:                "Jan–Dec 2026",
  last_updated:                 "4 Aug 2026",
  is_rtc_client:                true,
  total_cases:                  53,

  avg_days_creation_to_update:         1,
  avg_days_creation_to_update_general: 1.5,
  avg_days_stmt_to_report:             6.5,
  avg_days_stmt_to_report_rtc:         0.9,
  avg_days_stmt_to_report_general:     18.9,

  sla_ack_pct:                  100,
  sla_contact_pct:              100,
  sla_update_pct:               100,
  sla_report_general_pct:       17,
  sla_report_rtc_pct:           91,
  has_rtc_cases:                true,
  has_general_cases:            true,
  sla_compliance_pct:           91,
  sla_met:                      22,
  sla_not_met:                  12,

  avg_fee_rtc:                  158.76,
  avg_fee_general:              456,
  total_fees_rtc:               4762.8,
  total_fees_general:           10488,
  rtc_case_count:               30,
  general_case_count:           23,
  fees_by_type: [
    { type:"Motor Fraud", is_rtc:false, case_count:19, total_fees:9276, avg_fee:488.21 },
    { type:"RTC", is_rtc:true, case_count:30, total_fees:4762.8, avg_fee:158.76 },
    { type:"Motor Theft", is_rtc:false, case_count:4, total_fees:1212, avg_fee:303 }
  ],

  // Line-item-driven revenue (from TrackOps invoice details export)
  total_invoiced_lineitems:     14279,
  total_lineitem_count:         64,
  fees_by_item: [
    { item:"Stage 1 Investigation", is_rtc:false, count:13, total:6100, avg:469.23 },
    { item:"RTC", is_rtc:true, count:27, total:3969, avg:147 },
    { item:"Cold Calls", is_rtc:false, count:12, total:1620, avg:135 },
    { item:"Motor Theft Investigation", is_rtc:false, count:2, total:950, avg:475 },
    { item:"Stage 2 Investigation", is_rtc:false, count:3, total:600, avg:200 },
    { item:"Interpreter (1/2 day)", is_rtc:false, count:3, total:460, avg:153.33 },
    { item:"Interpreter (full day)", is_rtc:false, count:1, total:350, avg:350 },
    { item:"Failed Appointment", is_rtc:false, count:2, total:170, avg:85 },
    { item:"Miscellanoeus", is_rtc:false, count:1, total:60, avg:60 }
  ],

  monthly: [
    { month:"Jan", month_num:1, case_count:1, case_count_rtc:0, case_count_general:1, total_fees:144, ave_fees:144, total_fees_rtc:0, total_fees_general:144, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Feb", month_num:2, case_count:7, case_count_rtc:0, case_count_general:7, total_fees:3864, ave_fees:552, total_fees_rtc:0, total_fees_general:3864, ave_days_creation_to_update:1.3, ave_days_creation_to_update_general:1.3, ave_days_stmt_to_report:15, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:15, sla_ack_pct:100, sla_ack_met:6, sla_ack_n:6, sla_contact_pct:100, sla_contact_met:6, sla_contact_n:6, sla_update_pct:100, sla_update_met:6, sla_update_n:6, sla_report_general_pct:50, sla_report_general_met:2, sla_report_general_n:4, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:91, sla_met:2, sla_not_met:2 },
    { month:"Mar", month_num:3, case_count:1, case_count_rtc:0, case_count_general:1, total_fees:72, ave_fees:72, total_fees_rtc:0, total_fees_general:72, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Apr", month_num:4, case_count:20, case_count_rtc:17, case_count_general:3, total_fees:3786, ave_fees:189.3, total_fees_rtc:2646, total_fees_general:1140, ave_days_creation_to_update:0.7, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:2.1, ave_days_stmt_to_report_rtc:1, ave_days_stmt_to_report_general:9.5, sla_ack_pct:100, sla_ack_met:19, sla_ack_n:19, sla_contact_pct:100, sla_contact_met:19, sla_contact_n:19, sla_update_pct:100, sla_update_met:2, sla_update_n:2, sla_report_general_pct:0, sla_report_general_met:0, sla_report_general_n:2, sla_report_rtc_pct:86, sla_report_rtc_met:12, sla_report_rtc_n:14, sla_compliance_pct:93, sla_met:12, sla_not_met:4 },
    { month:"May", month_num:5, case_count:6, case_count_rtc:2, case_count_general:4, total_fees:2056.8, ave_fees:342.8, total_fees_rtc:352.8, total_fees_general:1704, ave_days_creation_to_update:2, ave_days_creation_to_update_general:2.7, ave_days_stmt_to_report:14.7, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:44, sla_ack_pct:100, sla_ack_met:5, sla_ack_n:5, sla_contact_pct:100, sla_contact_met:5, sla_contact_n:5, sla_update_pct:100, sla_update_met:3, sla_update_n:3, sla_report_general_pct:0, sla_report_general_met:0, sla_report_general_n:3, sla_report_rtc_pct:100, sla_report_rtc_met:2, sla_report_rtc_n:2, sla_compliance_pct:83, sla_met:2, sla_not_met:3 },
    { month:"Jun", month_num:6, case_count:8, case_count_rtc:4, case_count_general:4, total_fees:3249.6, ave_fees:406.2, total_fees_rtc:705.6, total_fees_general:2544, ave_days_creation_to_update:0.6, ave_days_creation_to_update_general:0.7, ave_days_stmt_to_report:12.2, ave_days_stmt_to_report_rtc:1.3, ave_days_stmt_to_report_general:28.5, sla_ack_pct:100, sla_ack_met:6, sla_ack_n:6, sla_contact_pct:100, sla_contact_met:6, sla_contact_n:6, sla_update_pct:100, sla_update_met:3, sla_update_n:3, sla_report_general_pct:0, sla_report_general_met:0, sla_report_general_n:2, sla_report_rtc_pct:100, sla_report_rtc_met:3, sla_report_rtc_n:3, sla_compliance_pct:90, sla_met:3, sla_not_met:2 },
    { month:"Jul", month_num:7, case_count:10, case_count_rtc:7, case_count_general:3, total_fees:2078.4, ave_fees:207.84, total_fees_rtc:1058.4, total_fees_general:1020, ave_days_creation_to_update:1.3, ave_days_creation_to_update_general:5, ave_days_stmt_to_report:2.5, ave_days_stmt_to_report_rtc:0.3, ave_days_stmt_to_report_general:9, sla_ack_pct:100, sla_ack_met:5, sla_ack_n:5, sla_contact_pct:100, sla_contact_met:5, sla_contact_n:5, sla_update_pct:100, sla_update_met:1, sla_update_n:1, sla_report_general_pct:0, sla_report_general_met:0, sla_report_general_n:1, sla_report_rtc_pct:100, sla_report_rtc_met:3, sla_report_rtc_n:3, sla_compliance_pct:93, sla_met:3, sla_not_met:1 },
    { month:"Aug", month_num:8, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Sep", month_num:9, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Oct", month_num:10, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Nov", month_num:11, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Dec", month_num:12, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 }
  ],

  cases: [
    { ref:"1132601", client_ref:"FC/901468570", type:"Motor Fraud", status:"Invoice Paid", created:"21 Jan 2026", first_updated:"1 Sep 2025", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:144, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:5 },
    { ref:"1136602", client_ref:"FC/901514109", type:"Motor Fraud", status:"Invoice Paid", created:"10 Feb 2026", first_updated:"10 Feb 2026", stmt_date:"15 Feb 2026", report_sent:"19 Feb 2026", days_creation_to_update:0, days_stmt_to_report:4, invoice:1056, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:5 },
    { ref:"1137202", client_ref:"FC/901500992", type:"Motor Fraud", status:"Awaiting further advises", created:"11 Feb 2026", first_updated:"15 Feb 2026", stmt_date:"", report_sent:"", days_creation_to_update:4, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:null, report_proxy:false, sla_report_target_days:5 },
    { ref:"1137402", client_ref:"FC/901474836", type:"Motor Fraud", status:"Invoice Paid", created:"12 Feb 2026", first_updated:"15 Feb 2026", stmt_date:"24 Feb 2026", report_sent:"25 Mar 2026", days_creation_to_update:3, days_stmt_to_report:29, invoice:912, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:5 },
    { ref:"1137502", client_ref:"FC/901486653", type:"Motor Fraud", status:"Invoice Paid", created:"12 Feb 2026", first_updated:"12 Feb 2026", stmt_date:"", report_sent:"", days_creation_to_update:0, days_stmt_to_report:null, invoice:672, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:null, report_proxy:false, sla_report_target_days:5 },
    { ref:"1139602", client_ref:"FC/901522926", type:"Motor Fraud", status:"Invoice Paid", created:"19 Feb 2026", first_updated:"20 Feb 2026", stmt_date:"6 Mar 2026", report_sent:"11 Mar 2026", days_creation_to_update:1, days_stmt_to_report:5, invoice:408, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:5 },
    { ref:"1141002", client_ref:"FC/901535625", type:"Motor Fraud", status:"Invoice Paid", created:"25 Feb 2026", first_updated:"25 Feb 2026", stmt_date:"4 Mar 2026", report_sent:"26 Mar 2026", days_creation_to_update:0, days_stmt_to_report:22, invoice:816, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:5 },
    { ref:"1141202", client_ref:"FC/901515505", type:"Motor Fraud", status:"Invoice Paid", created:"26 Feb 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:5 },
    { ref:"1145003", client_ref:"FC/901473263", type:"Motor Fraud", status:"Invoice Paid", created:"13 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:72, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:5 },
    { ref:"1149604", client_ref:"FC/901566941", type:"Motor Theft", status:"Invoice Paid", created:"1 Apr 2026", first_updated:"1 Apr 2026", stmt_date:"8 Apr 2026", report_sent:"16 Apr 2026", days_creation_to_update:0, days_stmt_to_report:8, invoice:570, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:5 },
    { ref:"1149704", client_ref:"FC/901567482", type:"Motor Theft", status:"Invoice Paid", created:"1 Apr 2026", first_updated:"1 Apr 2026", stmt_date:"9 Apr 2026", report_sent:"20 Apr 2026", days_creation_to_update:0, days_stmt_to_report:11, invoice:570, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:5 },
    { ref:"1151404", client_ref:"FC/901569926", type:"RTC", status:"Invoice Paid", created:"7 Apr 2026", first_updated:"7 Apr 2026", stmt_date:"14 Apr 2026", report_sent:"17 Apr 2026", days_creation_to_update:0, days_stmt_to_report:3, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:2 },
    { ref:"1151504", client_ref:"FC/901570498", type:"RTC", status:"Invoice Paid", created:"7 Apr 2026", first_updated:"9 Apr 2026", stmt_date:"22 Apr 2026", report_sent:"23 Apr 2026", days_creation_to_update:2, days_stmt_to_report:1, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1151604", client_ref:"FC/901568025", type:"RTC", status:"Invoice Paid", created:"7 Apr 2026", first_updated:"9 Apr 2026", stmt_date:"22 Apr 2026", report_sent:"23 Apr 2026", days_creation_to_update:2, days_stmt_to_report:1, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1151704", client_ref:"FC/901567446", type:"Motor Theft", status:"Invoice Paid", created:"7 Apr 2026", first_updated:"7 Apr 2026", stmt_date:"", report_sent:"", days_creation_to_update:0, days_stmt_to_report:null, invoice:0, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1151804", client_ref:"FC/901567406", type:"Motor Theft", status:"Invoice Paid", created:"7 Apr 2026", first_updated:"7 Apr 2026", stmt_date:"8 Apr 2026", report_sent:"8 Apr 2026", days_creation_to_update:0, days_stmt_to_report:0, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1151904", client_ref:"FC/901569719", type:"RTC", status:"Invoice Paid", created:"7 Apr 2026", first_updated:"7 Apr 2026", stmt_date:"15 Apr 2026", report_sent:"20 Apr 2026", days_creation_to_update:0, days_stmt_to_report:5, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:2 },
    { ref:"1153104", client_ref:"FC/901571032", type:"RTC", status:"Invoice Paid", created:"8 Apr 2026", first_updated:"8 Apr 2026", stmt_date:"10 Apr 2026", report_sent:"10 Apr 2026", days_creation_to_update:0, days_stmt_to_report:0, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1153204", client_ref:"FC/901570798", type:"RTC", status:"Invoice Paid", created:"8 Apr 2026", first_updated:"8 Apr 2026", stmt_date:"", report_sent:"", days_creation_to_update:0, days_stmt_to_report:null, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1153304", client_ref:"FC/901568473", type:"RTC", status:"Invoice Paid", created:"8 Apr 2026", first_updated:"8 Apr 2026", stmt_date:"11 Apr 2026", report_sent:"11 Apr 2026", days_creation_to_update:0, days_stmt_to_report:0, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1153504", client_ref:"FC/901570931", type:"RTC", status:"Invoice Paid", created:"8 Apr 2026", first_updated:"8 Apr 2026", stmt_date:"9 Apr 2026", report_sent:"9 Apr 2026", days_creation_to_update:0, days_stmt_to_report:0, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1153704", client_ref:"FC/901567641", type:"RTC", status:"Invoice Paid", created:"9 Apr 2026", first_updated:"28 Mar 2026", stmt_date:"15 Apr 2026", report_sent:"16 Apr 2026", days_creation_to_update:null, days_stmt_to_report:1, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1153804", client_ref:"FC/901563566", type:"RTC", status:"Invoice Paid", created:"9 Apr 2026", first_updated:"14 Apr 2026", stmt_date:"", report_sent:"", days_creation_to_update:5, days_stmt_to_report:null, invoice:0, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1154104", client_ref:"FC/901572769", type:"RTC", status:"Invoice Paid", created:"10 Apr 2026", first_updated:"9 Apr 2026", stmt_date:"15 Apr 2026", report_sent:"15 Apr 2026", days_creation_to_update:null, days_stmt_to_report:0, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1155204", client_ref:"FC/901573224", type:"RTC", status:"Invoice Paid", created:"14 Apr 2026", first_updated:"14 Apr 2026", stmt_date:"16 Apr 2026", report_sent:"17 Apr 2026", days_creation_to_update:0, days_stmt_to_report:1, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1155704", client_ref:"FC/901571090", type:"RTC", status:"Invoice Paid", created:"14 Apr 2026", first_updated:"15 Apr 2026", stmt_date:"28 Apr 2026", report_sent:"29 Apr 2026", days_creation_to_update:1, days_stmt_to_report:1, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1156104", client_ref:"FC/901441239", type:"RTC", status:"Invoice Paid", created:"15 Apr 2026", first_updated:"15 Apr 2026", stmt_date:"22 Apr 2026", report_sent:"23 Apr 2026", days_creation_to_update:0, days_stmt_to_report:1, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1157004", client_ref:"FC/901534927", type:"Motor Fraud", status:"Invoice Paid", created:"17 Apr 2026", first_updated:"22 Jan 2026", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:5 },
    { ref:"1157904", client_ref:"FC/901573865", type:"RTC", status:"Invoice Paid", created:"21 Apr 2026", first_updated:"23 Apr 2026", stmt_date:"27 Apr 2026", report_sent:"27 Apr 2026", days_creation_to_update:2, days_stmt_to_report:0, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1161905", client_ref:"FC/901454318", type:"Motor Fraud", status:"Awaiting further advises", created:"8 May 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:5 },
    { ref:"1162005", client_ref:"FC/901352162", type:"Motor Fraud", status:"Invoiced", created:"8 May 2026", first_updated:"12 May 2026", stmt_date:"", report_sent:"29 May 2026", days_creation_to_update:4, days_stmt_to_report:null, invoice:576, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:true, sla_report_target_days:5 },
    { ref:"1162205", client_ref:"FC/901460466", type:"Motor Fraud", status:"Invoiced", created:"8 May 2026", first_updated:"12 May 2026", stmt_date:"3 Jun 2026", report_sent:"17 Jul 2026", days_creation_to_update:4, days_stmt_to_report:44, invoice:1056, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:5 },
    { ref:"1164905", client_ref:"FC/901364796", type:"Motor Theft", status:"Invoice Paid", created:"19 May 2026", first_updated:"19 May 2026", stmt_date:"", report_sent:"2 Jun 2026", days_creation_to_update:0, days_stmt_to_report:null, invoice:72, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:true, sla_report_target_days:5 },
    { ref:"1165705", client_ref:"FC/901542337", type:"RTC", status:"Invoice Paid", created:"20 May 2026", first_updated:"20 May 2026", stmt_date:"26 May 2026", report_sent:"26 May 2026", days_creation_to_update:0, days_stmt_to_report:0, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1166105", client_ref:"FC/901557080", type:"RTC", status:"Invoice Paid", created:"21 May 2026", first_updated:"20 May 2026", stmt_date:"21 May 2026", report_sent:"21 May 2026", days_creation_to_update:null, days_stmt_to_report:0, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1170406", client_ref:"FC/901595823", type:"Motor Fraud", status:"Invoice Paid", created:"8 Jun 2026", first_updated:"27 May 2026", stmt_date:"23 Jun 2026", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:600, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:5 },
    { ref:"1172306", client_ref:"FC/901591677", type:"Motor Fraud", status:"Invoiced", created:"15 Jun 2026", first_updated:"16 Jun 2026", stmt_date:"26 Jun 2026", report_sent:"23 Jul 2026", days_creation_to_update:1, days_stmt_to_report:27, invoice:744, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:5 },
    { ref:"1172506", client_ref:"FC/901594008", type:"Motor Fraud", status:"Invoice Paid", created:"16 Jun 2026", first_updated:"17 Jun 2026", stmt_date:"23 Jun 2026", report_sent:"", days_creation_to_update:1, days_stmt_to_report:null, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:null, report_proxy:false, sla_report_target_days:5 },
    { ref:"1173106", client_ref:"FC/901551653", type:"Motor Fraud", status:"Invoice Paid", created:"18 Jun 2026", first_updated:"18 Jun 2026", stmt_date:"22 Jun 2026", report_sent:"22 Jul 2026", days_creation_to_update:0, days_stmt_to_report:30, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:5 },
    { ref:"1173206", client_ref:"FC/901598570", type:"RTC", status:"Invoiced", created:"18 Jun 2026", first_updated:"18 Jun 2026", stmt_date:"24 Jun 2026", report_sent:"25 Jun 2026", days_creation_to_update:0, days_stmt_to_report:1, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1173906", client_ref:"FC/901608693", type:"RTC", status:"Invoice Paid", created:"23 Jun 2026", first_updated:"22 Jun 2026", stmt_date:"24 Jun 2026", report_sent:"25 Jun 2026", days_creation_to_update:null, days_stmt_to_report:1, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1174706", client_ref:"FC/901607224", type:"RTC", status:"Invoiced", created:"26 Jun 2026", first_updated:"25 Jun 2026", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:176.4, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1175206", client_ref:"FC/901610996", type:"RTC", status:"Invoice Paid", created:"29 Jun 2026", first_updated:"30 Jun 2026", stmt_date:"6 Jul 2026", report_sent:"8 Jul 2026", days_creation_to_update:1, days_stmt_to_report:2, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1176407", client_ref:"FC/901612506", type:"RTC", status:"Invoiced", created:"2 Jul 2026", first_updated:"2 Jul 2026", stmt_date:"", report_sent:"", days_creation_to_update:0, days_stmt_to_report:null, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1176507", client_ref:"FC/901612499", type:"RTC", status:"Invoiced", created:"2 Jul 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:176.4, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1177007", client_ref:"FC/901521896", type:"Motor Fraud", status:"Invoice Paid", created:"3 Jul 2026", first_updated:"8 Jul 2026", stmt_date:"14 Jul 2026", report_sent:"23 Jul 2026", days_creation_to_update:5, days_stmt_to_report:9, invoice:1020, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:5 },
    { ref:"1179607", client_ref:"FC/901615664", type:"Motor Theft", status:"Closed", created:"13 Jul 2026", first_updated:"3 Jul 2026", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:5 },
    { ref:"1180507", client_ref:"FC/901615096", type:"RTC", status:"Invoice Paid", created:"14 Jul 2026", first_updated:"13 Jul 2026", stmt_date:"21 Jul 2026", report_sent:"22 Jul 2026", days_creation_to_update:null, days_stmt_to_report:1, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1180907", client_ref:"FC/901619249", type:"RTC", status:"Invoice Paid", created:"15 Jul 2026", first_updated:"15 Jul 2026", stmt_date:"16 Jul 2026", report_sent:"16 Jul 2026", days_creation_to_update:0, days_stmt_to_report:0, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1182607", client_ref:"FC/901620091", type:"RTC", status:"Invoiced", created:"16 Jul 2026", first_updated:"15 Jul 2026", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:176.4, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1182807", client_ref:"FC/901580837", type:"Motor Fraud", status:"Invoice Paid", created:"17 Jul 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:5 },
    { ref:"1186707", client_ref:"fc/901616074", type:"RTC", status:"Statement obtained", created:"24 Jul 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1188907", client_ref:"FC/901619919", type:"RTC", status:"Invoiced", created:"30 Jul 2026", first_updated:"30 Jul 2026", stmt_date:"31 Jul 2026", report_sent:"31 Jul 2026", days_creation_to_update:0, days_stmt_to_report:0, invoice:176.4, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 }
  ]

};
