// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  First Central Insurance
// File:    firstcentral.js
// Period:  Jan–May 2026
// Updated: 31 May 2026
// GENERATED AUTOMATICALLY FROM TrackOps CSV — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {
  "client_name": "First Central Insurance",
  "report_period": "Jan–May 2026",
  "last_updated": "31 May 2026",
  "is_rtc_client": true,
  "total_cases": 35,
  "avg_days_creation_to_update": -8.1,
  "avg_days_creation_to_update_general": -16.8,
  "avg_days_stmt_to_report": 5.6,
  "avg_days_stmt_to_report_rtc": 1.3,
  "avg_days_stmt_to_report_general": 11.6,
  "sla_ack_pct": 100,
  "sla_contact_pct": 100,
  "sla_update_pct": 100,
  "sla_report_general_pct": 12,
  "sla_report_rtc_pct": 82,
  "has_rtc_cases": true,
  "has_general_cases": true,
  "sla_compliance_pct": 79,
  "sla_met": 10,
  "sla_not_met": 9,
  "avg_fee_rtc": 138.35,
  "avg_fee_general": 252.61,
  "total_fees_rtc": 2352,
  "total_fees_general": 4547,
  "rtc_case_count": 17,
  "general_case_count": 18,
  "fees_by_type": [
    {
      "type": "Motor Fraud",
      "is_rtc": false,
      "case_count": 13,
      "total_fees": 3450,
      "avg_fee": 265.38
    },
    {
      "type": "RTC",
      "is_rtc": true,
      "case_count": 17,
      "total_fees": 2352,
      "avg_fee": 138.35
    },
    {
      "type": "Motor Theft",
      "is_rtc": false,
      "case_count": 5,
      "total_fees": 1097,
      "avg_fee": 219.4
    }
  ],
  "total_invoiced_lineitems": 6899,
  "total_lineitem_count": 34,
  "fees_by_item": [
    {
      "item": "RTC",
      "is_rtc": true,
      "count": 17,
      "total": 2499,
      "avg": 147
    },
    {
      "item": "Stage 1 Investigation",
      "is_rtc": false,
      "count": 5,
      "total": 2300,
      "avg": 460
    },
    {
      "item": "Motor Theft Investigation",
      "is_rtc": false,
      "count": 2,
      "total": 950,
      "avg": 475
    },
    {
      "item": "Cold Calls",
      "is_rtc": false,
      "count": 6,
      "total": 600,
      "avg": 100
    },
    {
      "item": "Stage 2 Investigation",
      "is_rtc": false,
      "count": 2,
      "total": 400,
      "avg": 200
    },
    {
      "item": "Failed Appointment",
      "is_rtc": false,
      "count": 1,
      "total": 90,
      "avg": 90
    },
    {
      "item": "Miscellanoeus",
      "is_rtc": false,
      "count": 1,
      "total": 60,
      "avg": 60
    }
  ],
  "monthly": [
    {
      "month": "Jan",
      "month_num": 1,
      "case_count": 1,
      "case_count_rtc": 0,
      "case_count_general": 1,
      "total_fees": 120,
      "ave_fees": 120,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": -142,
      "ave_days_creation_to_update_general": -142,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": 100,
      "sla_ack_met": 1,
      "sla_ack_n": 1,
      "sla_contact_pct": 100,
      "sla_contact_met": 1,
      "sla_contact_n": 1,
      "sla_update_pct": 100,
      "sla_update_met": 1,
      "sla_update_n": 1,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 100,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Feb",
      "month_num": 2,
      "case_count": 7,
      "case_count_rtc": 0,
      "case_count_general": 7,
      "total_fees": 3270,
      "ave_fees": 467,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 1.3,
      "ave_days_creation_to_update_general": 1.3,
      "ave_days_stmt_to_report": 15,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 15,
      "sla_ack_pct": 100,
      "sla_ack_met": 7,
      "sla_ack_n": 7,
      "sla_contact_pct": 100,
      "sla_contact_met": 7,
      "sla_contact_n": 7,
      "sla_update_pct": 100,
      "sla_update_met": 6,
      "sla_update_n": 6,
      "sla_report_general_pct": 0,
      "sla_report_general_met": 0,
      "sla_report_general_n": 4,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 75,
      "sla_met": 0,
      "sla_not_met": 4
    },
    {
      "month": "Mar",
      "month_num": 3,
      "case_count": 1,
      "case_count_rtc": 0,
      "case_count_general": 1,
      "total_fees": 60,
      "ave_fees": 60,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": 100,
      "sla_ack_met": 1,
      "sla_ack_n": 1,
      "sla_contact_pct": 100,
      "sla_contact_met": 1,
      "sla_contact_n": 1,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 100,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Apr",
      "month_num": 4,
      "case_count": 20,
      "case_count_rtc": 15,
      "case_count_general": 5,
      "total_fees": 3155,
      "ave_fees": 158,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": -4.5,
      "ave_days_creation_to_update_general": -4.5,
      "ave_days_stmt_to_report": 2.4,
      "ave_days_stmt_to_report_rtc": 1.3,
      "ave_days_stmt_to_report_general": 6.3,
      "sla_ack_pct": 100,
      "sla_ack_met": 20,
      "sla_ack_n": 20,
      "sla_contact_pct": 100,
      "sla_contact_met": 20,
      "sla_contact_n": 20,
      "sla_update_pct": 100,
      "sla_update_met": 5,
      "sla_update_n": 5,
      "sla_report_general_pct": 33,
      "sla_report_general_met": 1,
      "sla_report_general_n": 3,
      "sla_report_rtc_pct": 82,
      "sla_report_rtc_met": 9,
      "sla_report_rtc_n": 11,
      "sla_compliance_pct": 83,
      "sla_met": 10,
      "sla_not_met": 4
    },
    {
      "month": "May",
      "month_num": 5,
      "case_count": 6,
      "case_count_rtc": 2,
      "case_count_general": 4,
      "total_fees": 294,
      "ave_fees": 49,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 14,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 14,
      "sla_ack_pct": 100,
      "sla_ack_met": 6,
      "sla_ack_n": 6,
      "sla_contact_pct": 100,
      "sla_contact_met": 6,
      "sla_contact_n": 6,
      "sla_update_pct": 100,
      "sla_update_met": 1,
      "sla_update_n": 1,
      "sla_report_general_pct": 0,
      "sla_report_general_met": 0,
      "sla_report_general_n": 1,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 75,
      "sla_met": 0,
      "sla_not_met": 1
    },
    {
      "month": "Jun",
      "month_num": 6,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Jul",
      "month_num": 7,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Aug",
      "month_num": 8,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Sep",
      "month_num": 9,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Oct",
      "month_num": 10,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Nov",
      "month_num": 11,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Dec",
      "month_num": 12,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    }
  ],
  "cases": [
    {
      "ref": "1166105",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "21 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1165705",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "20 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1164905",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoiced",
      "created": "19 May 2026",
      "first_updated": "19 May 2026",
      "stmt_date": "",
      "report_sent": "2 Jun 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 14,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": true,
      "sla_report_target_days": 3
    },
    {
      "ref": "1162205",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Awaiting further advises",
      "created": "8 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1162005",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "8 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1161905",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Await PH response / HUB done",
      "created": "8 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1157904",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "21 Apr 2026",
      "first_updated": "23 Apr 2026",
      "stmt_date": "27 Apr 2026",
      "report_sent": "27 Apr 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 0,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1157004",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "17 Apr 2026",
      "first_updated": "22 Jan 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": -85,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1156104",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "15 Apr 2026",
      "first_updated": "15 Apr 2026",
      "stmt_date": "22 Apr 2026",
      "report_sent": "23 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 1,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1155704",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "14 Apr 2026",
      "first_updated": "15 Apr 2026",
      "stmt_date": "28 Apr 2026",
      "report_sent": "29 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 1,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1155204",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "14 Apr 2026",
      "first_updated": "14 Apr 2026",
      "stmt_date": "16 Apr 2026",
      "report_sent": "17 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 1,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1154104",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "10 Apr 2026",
      "first_updated": "9 Apr 2026",
      "stmt_date": "15 Apr 2026",
      "report_sent": "15 Apr 2026",
      "days_creation_to_update": -1,
      "days_stmt_to_report": 0,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1153804",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "9 Apr 2026",
      "first_updated": "14 Apr 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 5,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1153704",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "9 Apr 2026",
      "first_updated": "28 Mar 2026",
      "stmt_date": "15 Apr 2026",
      "report_sent": "16 Apr 2026",
      "days_creation_to_update": -12,
      "days_stmt_to_report": 1,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1153504",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "8 Apr 2026",
      "first_updated": "8 Apr 2026",
      "stmt_date": "9 Apr 2026",
      "report_sent": "9 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 0,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1153304",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "8 Apr 2026",
      "first_updated": "8 Apr 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 0,
      "days_stmt_to_report": null,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1153204",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "8 Apr 2026",
      "first_updated": "8 Apr 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 0,
      "days_stmt_to_report": null,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1153104",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "8 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1151904",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "7 Apr 2026",
      "first_updated": "7 Apr 2026",
      "stmt_date": "15 Apr 2026",
      "report_sent": "20 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 5,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1151804",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "7 Apr 2026",
      "first_updated": "7 Apr 2026",
      "stmt_date": "8 Apr 2026",
      "report_sent": "8 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 0,
      "invoice": 147,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1151704",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "7 Apr 2026",
      "first_updated": "7 Apr 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 0,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1151604",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "7 Apr 2026",
      "first_updated": "9 Apr 2026",
      "stmt_date": "22 Apr 2026",
      "report_sent": "23 Apr 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 1,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1151504",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "7 Apr 2026",
      "first_updated": "9 Apr 2026",
      "stmt_date": "22 Apr 2026",
      "report_sent": "23 Apr 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 1,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1151404",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "7 Apr 2026",
      "first_updated": "7 Apr 2026",
      "stmt_date": "14 Apr 2026",
      "report_sent": "17 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 3,
      "invoice": 147,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1149704",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "1 Apr 2026",
      "first_updated": "1 Apr 2026",
      "stmt_date": "9 Apr 2026",
      "report_sent": "20 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 11,
      "invoice": 475,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1149604",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "1 Apr 2026",
      "first_updated": "1 Apr 2026",
      "stmt_date": "8 Apr 2026",
      "report_sent": "16 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 8,
      "invoice": 475,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1145003",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "13 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 60,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1141202",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "26 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1141002",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "25 Feb 2026",
      "first_updated": "25 Feb 2026",
      "stmt_date": "4 Mar 2026",
      "report_sent": "26 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 22,
      "invoice": 680,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1139602",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "19 Feb 2026",
      "first_updated": "20 Feb 2026",
      "stmt_date": "6 Mar 2026",
      "report_sent": "11 Mar 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 5,
      "invoice": 390,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1137502",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "12 Feb 2026",
      "first_updated": "12 Feb 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 0,
      "days_stmt_to_report": null,
      "invoice": 560,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1137402",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "12 Feb 2026",
      "first_updated": "15 Feb 2026",
      "stmt_date": "24 Feb 2026",
      "report_sent": "25 Mar 2026",
      "days_creation_to_update": 3,
      "days_stmt_to_report": 29,
      "invoice": 760,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1137202",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Awaiting further advises",
      "created": "11 Feb 2026",
      "first_updated": "15 Feb 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 4,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1136602",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "10 Feb 2026",
      "first_updated": "10 Feb 2026",
      "stmt_date": "15 Feb 2026",
      "report_sent": "19 Feb 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 4,
      "invoice": 880,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1132601",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "21 Jan 2026",
      "first_updated": "1 Sep 2025",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": -142,
      "days_stmt_to_report": null,
      "invoice": 120,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    }
  ]
};
