// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  Inshur
// File:    inshur.js
// Period:  Jan–May 2026
// Updated: 3 Jun 2026
// GENERATED AUTOMATICALLY FROM TrackOps CSV — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {
  "client_name": "Inshur",
  "report_period": "Jan–May 2026",
  "last_updated": "3 Jun 2026",
  "is_rtc_client": false,
  "total_cases": 69,
  "avg_days_creation_to_update": 2.5,
  "avg_days_creation_to_update_general": 2.5,
  "avg_days_stmt_to_report": 9.1,
  "avg_days_stmt_to_report_rtc": 0,
  "avg_days_stmt_to_report_general": 9.1,
  "sla_ack_pct": 100,
  "sla_contact_pct": 100,
  "sla_update_pct": 89,
  "sla_report_general_pct": 17,
  "sla_report_rtc_pct": null,
  "has_rtc_cases": false,
  "has_general_cases": true,
  "sla_compliance_pct": 77,
  "sla_met": 9,
  "sla_not_met": 43,
  "avg_fee_rtc": 0,
  "avg_fee_general": 391.87,
  "total_fees_rtc": 0,
  "total_fees_general": 27039.1,
  "rtc_case_count": 0,
  "general_case_count": 69,
  "fees_by_type": [
    {
      "type": "Large Loss",
      "is_rtc": false,
      "case_count": 39,
      "total_fees": 14350.8,
      "avg_fee": 367.97
    },
    {
      "type": "Motor Theft",
      "is_rtc": false,
      "case_count": 14,
      "total_fees": 6954,
      "avg_fee": 496.71
    },
    {
      "type": "Motor Fraud",
      "is_rtc": false,
      "case_count": 10,
      "total_fees": 3960,
      "avg_fee": 396
    },
    {
      "type": "Motor Liability",
      "is_rtc": false,
      "case_count": 5,
      "total_fees": 1294.3,
      "avg_fee": 258.86
    },
    {
      "type": "Motor Fire",
      "is_rtc": false,
      "case_count": 1,
      "total_fees": 480,
      "avg_fee": 480
    }
  ],
  "total_invoiced_lineitems": 21919,
  "total_lineitem_count": 82,
  "fees_by_item": [
    {
      "item": "Large Loss Investigation",
      "is_rtc": false,
      "count": 25,
      "total": 8750,
      "avg": 350
    },
    {
      "item": "Motor Theft Investigation",
      "is_rtc": false,
      "count": 12,
      "total": 4800,
      "avg": 400
    },
    {
      "item": "Stage 1 Investigation",
      "is_rtc": false,
      "count": 6,
      "total": 2700,
      "avg": 450
    },
    {
      "item": "Interpreter (full day)",
      "is_rtc": false,
      "count": 4,
      "total": 1200,
      "avg": 300
    },
    {
      "item": "Miscellanoeus",
      "is_rtc": false,
      "count": 7,
      "total": 804,
      "avg": 114.86
    },
    {
      "item": "Cold Calls",
      "is_rtc": false,
      "count": 9,
      "total": 780,
      "avg": 86.67
    },
    {
      "item": "Interpreter (1/2 day)",
      "is_rtc": false,
      "count": 4,
      "total": 740,
      "avg": 185
    },
    {
      "item": "Motor Liability Investigation",
      "is_rtc": false,
      "count": 3,
      "total": 610,
      "avg": 203.33
    },
    {
      "item": "Stage 2 Investigation",
      "is_rtc": false,
      "count": 3,
      "total": 425,
      "avg": 141.67
    },
    {
      "item": "Police Report",
      "is_rtc": false,
      "count": 2,
      "total": 422.3,
      "avg": 211.15
    },
    {
      "item": "Motor Fire Investigation",
      "is_rtc": false,
      "count": 1,
      "total": 400,
      "avg": 400
    },
    {
      "item": "Failed Appointment",
      "is_rtc": false,
      "count": 2,
      "total": 160,
      "avg": 80
    },
    {
      "item": "Police reference request",
      "is_rtc": false,
      "count": 4,
      "total": 127.7,
      "avg": 31.93
    }
  ],
  "monthly": [
    {
      "month": "Jan",
      "month_num": 1,
      "case_count": 12,
      "case_count_rtc": 0,
      "case_count_general": 12,
      "total_fees": 5671.3,
      "ave_fees": 473,
      "total_fees_rtc": 0,
      "total_fees_general": 5671.3,
      "ave_days_creation_to_update": 1.1,
      "ave_days_creation_to_update_general": 1.1,
      "ave_days_stmt_to_report": 9.3,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 9.3,
      "sla_ack_pct": 100,
      "sla_ack_met": 12,
      "sla_ack_n": 12,
      "sla_contact_pct": 100,
      "sla_contact_met": 12,
      "sla_contact_n": 12,
      "sla_update_pct": 100,
      "sla_update_met": 11,
      "sla_update_n": 11,
      "sla_report_general_pct": 20,
      "sla_report_general_met": 2,
      "sla_report_general_n": 10,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 80,
      "sla_met": 2,
      "sla_not_met": 8
    },
    {
      "month": "Feb",
      "month_num": 2,
      "case_count": 13,
      "case_count_rtc": 0,
      "case_count_general": 13,
      "total_fees": 6953.6,
      "ave_fees": 535,
      "total_fees_rtc": 0,
      "total_fees_general": 6953.6,
      "ave_days_creation_to_update": 3.5,
      "ave_days_creation_to_update_general": 3.5,
      "ave_days_stmt_to_report": 11.3,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 11.3,
      "sla_ack_pct": 100,
      "sla_ack_met": 13,
      "sla_ack_n": 13,
      "sla_contact_pct": 100,
      "sla_contact_met": 13,
      "sla_contact_n": 13,
      "sla_update_pct": 83,
      "sla_update_met": 10,
      "sla_update_n": 12,
      "sla_report_general_pct": 25,
      "sla_report_general_met": 3,
      "sla_report_general_n": 12,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 77,
      "sla_met": 3,
      "sla_not_met": 9
    },
    {
      "month": "Mar",
      "month_num": 3,
      "case_count": 16,
      "case_count_rtc": 0,
      "case_count_general": 16,
      "total_fees": 6254.2,
      "ave_fees": 391,
      "total_fees_rtc": 0,
      "total_fees_general": 6254.2,
      "ave_days_creation_to_update": 1.4,
      "ave_days_creation_to_update_general": 1.4,
      "ave_days_stmt_to_report": 8.6,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 8.6,
      "sla_ack_pct": 100,
      "sla_ack_met": 16,
      "sla_ack_n": 16,
      "sla_contact_pct": 100,
      "sla_contact_met": 16,
      "sla_contact_n": 16,
      "sla_update_pct": 86,
      "sla_update_met": 12,
      "sla_update_n": 14,
      "sla_report_general_pct": 14,
      "sla_report_general_met": 2,
      "sla_report_general_n": 14,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 75,
      "sla_met": 2,
      "sla_not_met": 12
    },
    {
      "month": "Apr",
      "month_num": 4,
      "case_count": 15,
      "case_count_rtc": 0,
      "case_count_general": 15,
      "total_fees": 6006,
      "ave_fees": 400,
      "total_fees_rtc": 0,
      "total_fees_general": 6006,
      "ave_days_creation_to_update": 4.8,
      "ave_days_creation_to_update_general": 4.8,
      "ave_days_stmt_to_report": 8.8,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 8.8,
      "sla_ack_pct": 100,
      "sla_ack_met": 15,
      "sla_ack_n": 15,
      "sla_contact_pct": 100,
      "sla_contact_met": 15,
      "sla_contact_n": 15,
      "sla_update_pct": 85,
      "sla_update_met": 11,
      "sla_update_n": 13,
      "sla_report_general_pct": 8,
      "sla_report_general_met": 1,
      "sla_report_general_n": 12,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 73,
      "sla_met": 1,
      "sla_not_met": 11
    },
    {
      "month": "May",
      "month_num": 5,
      "case_count": 13,
      "case_count_rtc": 0,
      "case_count_general": 13,
      "total_fees": 2154,
      "ave_fees": 166,
      "total_fees_rtc": 0,
      "total_fees_general": 2154,
      "ave_days_creation_to_update": 0.3,
      "ave_days_creation_to_update_general": 0.3,
      "ave_days_stmt_to_report": 4.8,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 4.8,
      "sla_ack_pct": 100,
      "sla_ack_met": 13,
      "sla_ack_n": 13,
      "sla_contact_pct": 100,
      "sla_contact_met": 13,
      "sla_contact_n": 13,
      "sla_update_pct": 100,
      "sla_update_met": 4,
      "sla_update_n": 4,
      "sla_report_general_pct": 25,
      "sla_report_general_met": 1,
      "sla_report_general_n": 4,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 81,
      "sla_met": 1,
      "sla_not_met": 3
    },
    {
      "month": "Jun",
      "month_num": 6,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Jul",
      "month_num": 7,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Aug",
      "month_num": 8,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Sep",
      "month_num": 9,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Oct",
      "month_num": 10,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Nov",
      "month_num": 11,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Dec",
      "month_num": 12,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    }
  ],
  "cases": [
    {
      "ref": "1167305",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Appointment made",
      "created": "27 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1166605",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Awaiting further advises",
      "created": "26 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1166305",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Statement obtained",
      "created": "21 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1165805",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Documents Submitted",
      "created": "20 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1164805",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Await PH response / HUB done",
      "created": "19 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1164705",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoiced",
      "created": "18 May 2026",
      "first_updated": "19 May 2026",
      "stmt_date": "21 May 2026",
      "report_sent": "28 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 7,
      "invoice": 480,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1164605",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Appointment made",
      "created": "18 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1164505",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Awaiting further advises",
      "created": "18 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1164405",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoiced",
      "created": "18 May 2026",
      "first_updated": "18 May 2026",
      "stmt_date": "21 May 2026",
      "report_sent": "26 May 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 5,
      "invoice": 480,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1164305",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Await PH response / HUB done",
      "created": "18 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1162305",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoiced",
      "created": "11 May 2026",
      "first_updated": "11 May 2026",
      "stmt_date": "12 May 2026",
      "report_sent": "15 May 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 3,
      "invoice": 714,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1161705",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Awaiting further advises",
      "created": "7 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1161605",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "7 May 2026",
      "first_updated": "7 May 2026",
      "stmt_date": "11 May 2026",
      "report_sent": "15 May 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 4,
      "invoice": 480,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1160004",
      "client_ref": null,
      "type": "Large Loss",
      "status": "PH unresponsive",
      "created": "29 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1159004",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Cold Calls being undertaken",
      "created": "28 Apr 2026",
      "first_updated": "28 Apr 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 0,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1158304",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "23 Apr 2026",
      "first_updated": "24 Apr 2026",
      "stmt_date": "5 May 2026",
      "report_sent": "12 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 7,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1158204",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Enquiries ongoing",
      "created": "23 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1158004",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "21 Apr 2026",
      "first_updated": "21 Apr 2026",
      "stmt_date": "28 Apr 2026",
      "report_sent": "7 May 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 9,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1157604",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Forensic Key analysis",
      "created": "20 Apr 2026",
      "first_updated": "27 May 2026",
      "stmt_date": "28 Apr 2026",
      "report_sent": "8 May 2026",
      "days_creation_to_update": 37,
      "days_stmt_to_report": 10,
      "invoice": 762,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1157204",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "17 Apr 2026",
      "first_updated": "17 Apr 2026",
      "stmt_date": "21 Apr 2026",
      "report_sent": "24 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 3,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1156804",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "16 Apr 2026",
      "first_updated": "18 Apr 2026",
      "stmt_date": "22 Apr 2026",
      "report_sent": "6 May 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 14,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1156704",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "16 Apr 2026",
      "first_updated": "18 Apr 2026",
      "stmt_date": "11 May 2026",
      "report_sent": "19 May 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 8,
      "invoice": 492,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1156604",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoiced",
      "created": "16 Apr 2026",
      "first_updated": "21 Apr 2026",
      "stmt_date": "22 Apr 2026",
      "report_sent": "1 May 2026",
      "days_creation_to_update": 5,
      "days_stmt_to_report": 9,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1155804",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "15 Apr 2026",
      "first_updated": "20 Apr 2026",
      "stmt_date": "21 Apr 2026",
      "report_sent": "30 Apr 2026",
      "days_creation_to_update": 5,
      "days_stmt_to_report": 9,
      "invoice": 480,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1155604",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "14 Apr 2026",
      "first_updated": "23 Apr 2026",
      "stmt_date": "25 Apr 2026",
      "report_sent": "30 Apr 2026",
      "days_creation_to_update": 9,
      "days_stmt_to_report": 5,
      "invoice": 690,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1152004",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "7 Apr 2026",
      "first_updated": "8 Apr 2026",
      "stmt_date": "17 Apr 2026",
      "report_sent": "7 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 20,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1151104",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "7 Apr 2026",
      "first_updated": "7 Apr 2026",
      "stmt_date": "14 Apr 2026",
      "report_sent": "20 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 6,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1149904",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "1 Apr 2026",
      "first_updated": "2 Apr 2026",
      "stmt_date": "23 Apr 2026",
      "report_sent": "28 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 5,
      "invoice": 642,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1149203",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "31 Mar 2026",
      "first_updated": "31 Mar 2026",
      "stmt_date": "10 Apr 2026",
      "report_sent": "24 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 14,
      "invoice": 452.2,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1148203",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "26 Mar 2026",
      "first_updated": "26 Mar 2026",
      "stmt_date": "28 Mar 2026",
      "report_sent": "2 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 5,
      "invoice": 480,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1148103",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "26 Mar 2026",
      "first_updated": "27 Mar 2026",
      "stmt_date": "1 Apr 2026",
      "report_sent": "7 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 6,
      "invoice": 480,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1147503",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "25 Mar 2026",
      "first_updated": "25 Mar 2026",
      "stmt_date": "2 Apr 2026",
      "report_sent": "7 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 5,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1147403",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "23 Mar 2026",
      "first_updated": "24 Mar 2026",
      "stmt_date": "31 Mar 2026",
      "report_sent": "2 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 2,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1147203",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Reviewed, signed off & sent",
      "created": "23 Mar 2026",
      "first_updated": "24 Mar 2026",
      "stmt_date": "",
      "report_sent": "15 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 22,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": true,
      "sla_report_target_days": 3
    },
    {
      "ref": "1146803",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "23 Mar 2026",
      "first_updated": "23 Mar 2026",
      "stmt_date": "25 Mar 2026",
      "report_sent": "14 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 20,
      "invoice": 780,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1146703",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Awaiting Police Report",
      "created": "23 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1146103",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "19 Mar 2026",
      "first_updated": "19 Mar 2026",
      "stmt_date": "23 Mar 2026",
      "report_sent": "31 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 8,
      "invoice": 612,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1145403",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Awaiting further advises",
      "created": "16 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1144403",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "12 Mar 2026",
      "first_updated": "12 Mar 2026",
      "stmt_date": "16 Mar 2026",
      "report_sent": "23 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 7,
      "invoice": 480,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1143403",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "10 Mar 2026",
      "first_updated": "16 Mar 2026",
      "stmt_date": "9 Apr 2026",
      "report_sent": "15 Apr 2026",
      "days_creation_to_update": 6,
      "days_stmt_to_report": 6,
      "invoice": 642,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1142903",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "6 Mar 2026",
      "first_updated": "6 Mar 2026",
      "stmt_date": "12 Mar 2026",
      "report_sent": "18 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 6,
      "invoice": 480,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1142603",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "5 Mar 2026",
      "first_updated": "12 Mar 2026",
      "stmt_date": "18 Mar 2026",
      "report_sent": "20 Mar 2026",
      "days_creation_to_update": 7,
      "days_stmt_to_report": 2,
      "invoice": 270,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1142303",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "4 Mar 2026",
      "first_updated": "6 Mar 2026",
      "stmt_date": "",
      "report_sent": "17 Mar 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 11,
      "invoice": 318,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": true,
      "sla_report_target_days": 3
    },
    {
      "ref": "1141903",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "3 Mar 2026",
      "first_updated": "4 Mar 2026",
      "stmt_date": "12 Mar 2026",
      "report_sent": "18 Mar 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 6,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1141302",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "26 Feb 2026",
      "first_updated": "2 Mar 2026",
      "stmt_date": "3 Mar 2026",
      "report_sent": "5 Mar 2026",
      "days_creation_to_update": 4,
      "days_stmt_to_report": 2,
      "invoice": 540,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1140902",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "23 Feb 2026",
      "first_updated": "25 Feb 2026",
      "stmt_date": "14 Apr 2026",
      "report_sent": "16 Apr 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 2,
      "invoice": 684,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1139802",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "19 Feb 2026",
      "first_updated": "19 Feb 2026",
      "stmt_date": "23 Feb 2026",
      "report_sent": "25 Feb 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 2,
      "invoice": 480,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1139702",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "19 Feb 2026",
      "first_updated": "20 Feb 2026",
      "stmt_date": "20 Feb 2026",
      "report_sent": "4 Mar 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 12,
      "invoice": 480,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1139202",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "18 Feb 2026",
      "first_updated": "18 Feb 2026",
      "stmt_date": "25 Feb 2026",
      "report_sent": "16 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 19,
      "invoice": 492,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1138702",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "17 Feb 2026",
      "first_updated": "17 Feb 2026",
      "stmt_date": "",
      "report_sent": "13 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 24,
      "invoice": 180,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": true,
      "sla_report_target_days": 3
    },
    {
      "ref": "1137302",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "12 Feb 2026",
      "first_updated": "12 Feb 2026",
      "stmt_date": "17 Feb 2026",
      "report_sent": "25 Feb 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 8,
      "invoice": 630,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1136802",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Awaiting Police Report",
      "created": "10 Feb 2026",
      "first_updated": "10 Mar 2026",
      "stmt_date": "13 Feb 2026",
      "report_sent": "12 Mar 2026",
      "days_creation_to_update": 28,
      "days_stmt_to_report": 27,
      "invoice": 1099.3,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1136402",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "9 Feb 2026",
      "first_updated": "9 Feb 2026",
      "stmt_date": "19 Feb 2026",
      "report_sent": "23 Feb 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 4,
      "invoice": 780,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1134802",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Awaiting Police Report",
      "created": "3 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 238.3,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1134602",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "3 Feb 2026",
      "first_updated": "3 Feb 2026",
      "stmt_date": "7 Mar 2026",
      "report_sent": "30 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 23,
      "invoice": 516,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1134502",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "3 Feb 2026",
      "first_updated": "3 Feb 2026",
      "stmt_date": "6 Feb 2026",
      "report_sent": "11 Feb 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 5,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1134302",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "2 Feb 2026",
      "first_updated": "9 Feb 2026",
      "stmt_date": "9 Mar 2026",
      "report_sent": "16 Mar 2026",
      "days_creation_to_update": 7,
      "days_stmt_to_report": 7,
      "invoice": 414,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1134201",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "30 Jan 2026",
      "first_updated": "31 Jan 2026",
      "stmt_date": "7 Feb 2026",
      "report_sent": "11 Feb 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 4,
      "invoice": 420,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1133101",
      "client_ref": null,
      "type": "Motor Fire",
      "status": "Invoice Paid",
      "created": "23 Jan 2026",
      "first_updated": "23 Jan 2026",
      "stmt_date": "28 Jan 2026",
      "report_sent": "2 Feb 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 5,
      "invoice": 480,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1132901",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "22 Jan 2026",
      "first_updated": "23 Jan 2026",
      "stmt_date": "",
      "report_sent": "18 Feb 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 26,
      "invoice": 288,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": true,
      "sla_report_target_days": 3
    },
    {
      "ref": "1132801",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "21 Jan 2026",
      "first_updated": "",
      "stmt_date": "28 Jan 2026",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 612,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1132101",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "19 Jan 2026",
      "first_updated": "20 Jan 2026",
      "stmt_date": "24 Jan 2026",
      "report_sent": "29 Jan 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 5,
      "invoice": 540,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1132001",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "19 Jan 2026",
      "first_updated": "19 Jan 2026",
      "stmt_date": "21 Jan 2026",
      "report_sent": "23 Jan 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 2,
      "invoice": 900,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1130201",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoiced",
      "created": "8 Jan 2026",
      "first_updated": "8 Jan 2026",
      "stmt_date": "18 Feb 2026",
      "report_sent": "5 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 15,
      "invoice": 757.3,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1129901",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "8 Jan 2026",
      "first_updated": "12 Jan 2026",
      "stmt_date": "27 Jan 2026",
      "report_sent": "29 Jan 2026",
      "days_creation_to_update": 4,
      "days_stmt_to_report": 2,
      "invoice": 702,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1129601",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "6 Jan 2026",
      "first_updated": "8 Jan 2026",
      "stmt_date": "13 Jan 2026",
      "report_sent": "",
      "days_creation_to_update": 2,
      "days_stmt_to_report": null,
      "invoice": 192,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1129501",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "6 Jan 2026",
      "first_updated": "7 Jan 2026",
      "stmt_date": "14 Jan 2026",
      "report_sent": "19 Jan 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 5,
      "invoice": 492,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1129401",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "6 Jan 2026",
      "first_updated": "6 Jan 2026",
      "stmt_date": "",
      "report_sent": "20 Jan 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 14,
      "invoice": 216,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": true,
      "sla_report_target_days": 3
    },
    {
      "ref": "1129001",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "2 Jan 2026",
      "first_updated": "4 Jan 2026",
      "stmt_date": "",
      "report_sent": "19 Jan 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 15,
      "invoice": 72,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": true,
      "sla_report_target_days": 3
    }
  ]
};
