// ============================================================
// DLB INVESTIGATIONS LTD — CLIENT DATA FILE
// Client:       Inshur
// Access Code:  INSHUR26
// Last Updated: 6 March 2026
// AUTO-GENERATED — do not edit manually
// ============================================================

var DLB_CLIENT_DATA = {
  client_name:   "Inshur",
  report_period: "2026 Full Year",
  last_updated:  "6 March 2026",

  monthly: [
    { month:"Jan", month_num:1, total_fees:5424, ave_fees:452, ave_days:5.4, case_count:12, sla_compliance_pct:86, sla1_compliance_pct:100, sla2_compliance_pct:86 },
    { month:"Feb", month_num:2, total_fees:3361.1, ave_fees:258.55, ave_days:5.5, case_count:13, sla_compliance_pct:83, sla1_compliance_pct:100, sla2_compliance_pct:83 },
    { month:"Mar", month_num:3, total_fees:0, ave_fees:0, ave_days:0, case_count:4, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Apr", month_num:4, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"May", month_num:5, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Jun", month_num:6, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Jul", month_num:7, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Aug", month_num:8, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Sep", month_num:9, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Oct", month_num:10, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Nov", month_num:11, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Dec", month_num:12, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 }
  ],

  cases: [
    { month:"Mar", case_number:"1142903", reference:"UV-26-01434", case_type:"Motor Theft", case_status:"Await HUB & response from PH", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"06/03/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Wellington, Phil" },
    { month:"Mar", case_number:"1142603", reference:"WA-24-00836", case_type:"Motor Liability", case_status:"Await PH response / HUB done", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"05/03/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Booker, David" },
    { month:"Mar", case_number:"1142303", reference:"UC-26-01352", case_type:"Large Loss", case_status:"Interview date / time TBC", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"04/03/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hayes, Ivan" },
    { month:"Mar", case_number:"1141903", reference:"UT-26-01332", case_type:"Large Loss", case_status:"Appointment made", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"03/03/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Douglas, Bill" },
    { month:"Feb", case_number:"1141302", reference:"UT-26-01059", case_type:"Motor Fraud", case_status:"Invoiced", invoice_total:540, total_days:2, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"26/02/2026", date_first_update:"02/03/2026", date_statement:"03/03/2026", date_report:"05/03/2026", sla1_days:4, sla1_pass:true, sla2_days:2, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hayes, Ivan" },
    { month:"Feb", case_number:"1140902", reference:"UV-26-00660", case_type:"Motor Fraud", case_status:"Interview date / time TBC", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"23/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hayes, Ivan" },
    { month:"Feb", case_number:"1139802", reference:"UT-26-01083", case_type:"Motor Theft", case_status:"Invoiced", invoice_total:480, total_days:2, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"19/02/2026", date_first_update:"19/02/2026", date_statement:"23/02/2026", date_report:"25/02/2026", sla1_days:0, sla1_pass:true, sla2_days:2, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Feb", case_number:"1139702", reference:"UT-26-01077", case_type:"Motor Theft", case_status:"Invoiced", invoice_total:480, total_days:12, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"19/02/2026", date_first_update:"20/02/2026", date_statement:"20/02/2026", date_report:"04/03/2026", sla1_days:1, sla1_pass:true, sla2_days:12, sla2_pass:false, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Phillips, Andrew" },
    { month:"Feb", case_number:"1139202", reference:"UT-26-00980", case_type:"Large Loss", case_status:"Statement obtained", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"18/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Feb", case_number:"1138702", reference:"UT-26-00621", case_type:"Motor Liability", case_status:"Reviewed, signed off & sent", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"17/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Feb", case_number:"1137302", reference:"UT-26-00937", case_type:"Large Loss", case_status:"Invoiced", invoice_total:630, total_days:8, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"12/02/2026", date_first_update:"12/02/2026", date_statement:"17/02/2026", date_report:"25/02/2026", sla1_days:0, sla1_pass:true, sla2_days:8, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Wellington, Phil" },
    { month:"Feb", case_number:"1136802", reference:"UC-26-00893", case_type:"Large Loss", case_status:"Statement obtained", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"10/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Feb", case_number:"1136402", reference:"UA-26-00819", case_type:"Large Loss", case_status:"Invoiced", invoice_total:780, total_days:4, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"09/02/2026", date_first_update:"09/02/2026", date_statement:"19/02/2026", date_report:"23/02/2026", sla1_days:0, sla1_pass:true, sla2_days:4, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hayes, Ivan" },
    { month:"Feb", case_number:"1134802", reference:"UA-26-00688", case_type:"Motor Liability", case_status:"Cold Calls being undertaken", invoice_total:31.1, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"03/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Feb", case_number:"1134602", reference:"UA-26-00705", case_type:"Large Loss", case_status:"Await PH response / HUB done", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"03/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Phillips, Andrew" },
    { month:"Feb", case_number:"1134502", reference:"UC-26-00694", case_type:"Large Loss", case_status:"Invoice Paid", invoice_total:420, total_days:5, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"03/02/2026", date_first_update:"03/02/2026", date_statement:"06/02/2026", date_report:"11/02/2026", sla1_days:0, sla1_pass:true, sla2_days:5, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Feb", case_number:"1134302", reference:"UA-26-00641", case_type:"Motor Liability", case_status:"Appointment made", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"02/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Booker, David" },
    { month:"Jan", case_number:"1134201", reference:"UC-26-00639", case_type:"Large Loss", case_status:"Invoice Paid", invoice_total:420, total_days:4, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"30/01/2026", date_first_update:"31/01/2026", date_statement:"07/02/2026", date_report:"11/02/2026", sla1_days:1, sla1_pass:true, sla2_days:4, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hayes, Ivan" },
    { month:"Jan", case_number:"1133101", reference:"UT-26-00454", case_type:"Motor Fire", case_status:"Invoice Paid", invoice_total:480, total_days:5, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"23/01/2026", date_first_update:"23/01/2026", date_statement:"28/01/2026", date_report:"02/02/2026", sla1_days:0, sla1_pass:true, sla2_days:5, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Jan", case_number:"1132901", reference:"WK-25-06711", case_type:"Large Loss", case_status:"Invoiced", invoice_total:288, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"22/01/2026", date_first_update:"23/01/2026", date_statement:"", date_report:"18/02/2026", sla1_days:1, sla1_pass:true, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hunter, Mick" },
    { month:"Jan", case_number:"1132801", reference:"UA-25-05338", case_type:"Motor Fraud", case_status:"Invoice Paid", invoice_total:612, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"21/01/2026", date_first_update:"", date_statement:"28/01/2026", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Lawless, Jim" },
    { month:"Jan", case_number:"1132101", reference:"UV-25-07290", case_type:"Motor Fraud", case_status:"Invoice Paid", invoice_total:540, total_days:5, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"19/01/2026", date_first_update:"20/01/2026", date_statement:"24/01/2026", date_report:"29/01/2026", sla1_days:1, sla1_pass:true, sla2_days:5, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hayes, Ivan" },
    { month:"Jan", case_number:"1132001", reference:"UC-26-00260", case_type:"Motor Fraud", case_status:"Invoice Paid", invoice_total:900, total_days:2, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"19/01/2026", date_first_update:"19/01/2026", date_statement:"21/01/2026", date_report:"23/01/2026", sla1_days:0, sla1_pass:true, sla2_days:2, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hayes, Ivan" },
    { month:"Jan", case_number:"1130201", reference:"UT-26-00139", case_type:"Large Loss", case_status:"Invoiced", invoice_total:510, total_days:15, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"08/01/2026", date_first_update:"08/01/2026", date_statement:"18/02/2026", date_report:"05/03/2026", sla1_days:0, sla1_pass:true, sla2_days:15, sla2_pass:false, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Phillips, Andrew" },
    { month:"Jan", case_number:"1129901", reference:"UC-26-00126", case_type:"Motor Theft", case_status:"Invoice Paid", invoice_total:702, total_days:2, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"08/01/2026", date_first_update:"12/01/2026", date_statement:"27/01/2026", date_report:"29/01/2026", sla1_days:4, sla1_pass:true, sla2_days:2, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Lawless, Jim" },
    { month:"Jan", case_number:"1129601", reference:"UT-25-07662", case_type:"Motor Liability", case_status:"Invoiced", invoice_total:192, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"06/01/2026", date_first_update:"08/01/2026", date_statement:"13/01/2026", date_report:"", sla1_days:2, sla1_pass:true, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Lawless, Jim" },
    { month:"Jan", case_number:"1129501", reference:"UA-26-00007", case_type:"Large Loss", case_status:"Invoice Paid", invoice_total:492, total_days:5, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"06/01/2026", date_first_update:"07/01/2026", date_statement:"14/01/2026", date_report:"19/01/2026", sla1_days:1, sla1_pass:true, sla2_days:5, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Jan", case_number:"1129401", reference:"UA-25-03336", case_type:"Large Loss", case_status:"Invoice Paid", invoice_total:216, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"06/01/2026", date_first_update:"06/01/2026", date_statement:"", date_report:"20/01/2026", sla1_days:0, sla1_pass:true, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Douglas, Bill" },
    { month:"Jan", case_number:"1129001", reference:"UT-25-05977", case_type:"Motor Fraud", case_status:"Invoice Paid", invoice_total:72, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"02/01/2026", date_first_update:"04/01/2026", date_statement:"", date_report:"19/01/2026", sla1_days:2, sla1_pass:true, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Douglas, Bill" }
  ]
};
