// ============================================================
// DLB INVESTIGATIONS LTD — CLIENT DATA FILE
// Client:       ITB
// Access Code:  ITB26
// Last Updated: 6 March 2026
// AUTO-GENERATED — do not edit manually
// ============================================================

var DLB_CLIENT_DATA = {
  client_name:   "ITB",
  report_period: "2026 Full Year",
  last_updated:  "6 March 2026",

  monthly: [
    { month:"Jan", month_num:1, total_fees:6474, ave_fees:498, ave_days:6.3, case_count:13, sla_compliance_pct:86, sla1_compliance_pct:75, sla2_compliance_pct:86 },
    { month:"Feb", month_num:2, total_fees:3064.25, ave_fees:255.35, ave_days:5.3, case_count:12, sla_compliance_pct:100, sla1_compliance_pct:67, sla2_compliance_pct:100 },
    { month:"Mar", month_num:3, total_fees:0, ave_fees:0, ave_days:0, case_count:2, sla_compliance_pct:0, sla1_compliance_pct:100, sla2_compliance_pct:0 },
    { month:"Apr", month_num:4, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"May", month_num:5, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Jun", month_num:6, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Jul", month_num:7, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Aug", month_num:8, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Sep", month_num:9, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Oct", month_num:10, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Nov", month_num:11, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Dec", month_num:12, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 }
  ],

  cases: [
    { month:"Mar", case_number:"1142703", reference:"300110774", case_type:"Large Loss", case_status:"Await PH response / HUB done", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"05/03/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Douglas, Bill" },
    { month:"Mar", case_number:"1142403", reference:"300112274", case_type:"Motor Fraud", case_status:"Appointment made", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"04/03/2026", date_first_update:"04/03/2026", date_statement:"", date_report:"", sla1_days:0, sla1_pass:true, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Phillips, Andrew" },
    { month:"Feb", case_number:"1141602", reference:"300112029", case_type:"Motor Theft", case_status:"Documents Submitted", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"27/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Douglas, Bill" },
    { month:"Feb", case_number:"1140402", reference:"300110494", case_type:"Motor Fraud", case_status:"Documents Submitted", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"20/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hayes, Ivan" },
    { month:"Feb", case_number:"1140302", reference:"300110800", case_type:"Motor Fraud", case_status:"Awaiting further advises", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"19/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Feb", case_number:"1139902", reference:"300109982", case_type:"Motor Fraud", case_status:"Statement obtained", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"19/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hunter, Mick" },
    { month:"Feb", case_number:"1139402", reference:"300102603", case_type:"Motor Fraud", case_status:"Awaiting signed statements", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"18/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Lawless, Jim" },
    { month:"Feb", case_number:"1139102", reference:"300108654", case_type:"Motor Fraud", case_status:"Documents Submitted", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"18/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Feb", case_number:"1139002", reference:"300111102", case_type:"Motor Fraud", case_status:"Statement obtained", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"18/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Phillips, Andrew" },
    { month:"Feb", case_number:"1138002", reference:"300111166", case_type:"Motor Fraud", case_status:"CCTV enquiries", invoice_total:765, total_days:7, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"13/02/2026", date_first_update:"16/02/2026", date_statement:"17/02/2026", date_report:"24/02/2026", sla1_days:3, sla1_pass:true, sla2_days:7, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Lawless, Jim" },
    { month:"Feb", case_number:"1136702", reference:"300102977", case_type:"Motor Fraud", case_status:"Appointment made", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"10/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Feb", case_number:"1136202", reference:"300110924", case_type:"Motor Fraud", case_status:"Invoice Paid", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"06/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hunter, Mick" },
    { month:"Feb", case_number:"1135102", reference:"300107668", case_type:"Motor Fraud", case_status:"Invoiced", invoice_total:786, total_days:2, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"04/02/2026", date_first_update:"08/02/2026", date_statement:"08/02/2026", date_report:"10/02/2026", sla1_days:4, sla1_pass:true, sla2_days:2, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Douglas, Bill" },
    { month:"Feb", case_number:"1134702", reference:"300110169", case_type:"Motor Fraud", case_status:"Invoiced", invoice_total:1513.25, total_days:7, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"03/02/2026", date_first_update:"09/02/2026", date_statement:"13/02/2026", date_report:"20/02/2026", sla1_days:6, sla1_pass:false, sla2_days:7, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Booker, David" },
    { month:"Jan", case_number:"1133901", reference:"300109984", case_type:"Motor Fraud", case_status:"Interview date / time TBC", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"29/01/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Booker, David" },
    { month:"Jan", case_number:"1133801", reference:"300109707", case_type:"Motor Fraud", case_status:"Interview date / time TBC", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"28/01/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Phillips, Andrew" },
    { month:"Jan", case_number:"1133301", reference:"300109297", case_type:"Motor Fraud", case_status:"Awaiting further advises", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"23/01/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Phillips, Andrew" },
    { month:"Jan", case_number:"1133001", reference:"300109996", case_type:"Large Loss", case_status:"Stage 2 Investigations", invoice_total:780, total_days:8, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"22/01/2026", date_first_update:"30/01/2026", date_statement:"04/02/2026", date_report:"12/02/2026", sla1_days:8, sla1_pass:false, sla2_days:8, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dargan, Jeremy" },
    { month:"Jan", case_number:"1132701", reference:"300105397", case_type:"Motor Fraud", case_status:"Witness stmnt being obtained", invoice_total:882, total_days:13, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"21/01/2026", date_first_update:"22/01/2026", date_statement:"07/02/2026", date_report:"20/02/2026", sla1_days:1, sla1_pass:true, sla2_days:13, sla2_pass:false, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Phillips, Andrew" },
    { month:"Jan", case_number:"1131901", reference:"300047377", case_type:"Intelligence Report", case_status:"Invoice Paid", invoice_total:144, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"16/01/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Jan", case_number:"1131801", reference:"300108802", case_type:"Motor Fraud", case_status:"Await PH response / HUB done", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"15/01/2026", date_first_update:"16/01/2026", date_statement:"", date_report:"", sla1_days:1, sla1_pass:true, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Lawless, Jim" },
    { month:"Jan", case_number:"1131701", reference:"300109130", case_type:"Motor Theft", case_status:"Invoiced", invoice_total:810, total_days:7, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"15/01/2026", date_first_update:"26/02/2026", date_statement:"28/01/2026", date_report:"04/02/2026", sla1_days:42, sla1_pass:false, sla2_days:7, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Wood, Andy" },
    { month:"Jan", case_number:"1131301", reference:"300109146", case_type:"Motor Fraud", case_status:"Invoice Paid", invoice_total:690, total_days:1, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"13/01/2026", date_first_update:"15/01/2026", date_statement:"09/02/2026", date_report:"10/02/2026", sla1_days:2, sla1_pass:true, sla2_days:1, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Booker, David" },
    { month:"Jan", case_number:"1130801", reference:"300109201", case_type:"Motor Theft", case_status:"Invoice Paid", invoice_total:540, total_days:6, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"12/01/2026", date_first_update:"12/01/2026", date_statement:"20/01/2026", date_report:"26/01/2026", sla1_days:0, sla1_pass:true, sla2_days:6, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Lawless, Jim" },
    { month:"Jan", case_number:"1129801", reference:"300108191", case_type:"Motor Fraud", case_status:"Invoice Paid", invoice_total:786, total_days:6, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"07/01/2026", date_first_update:"08/01/2026", date_statement:"13/01/2026", date_report:"19/01/2026", sla1_days:1, sla1_pass:true, sla2_days:6, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Hayes, Ivan" },
    { month:"Jan", case_number:"1129701", reference:"300108575", case_type:"Motor Fraud", case_status:"Invoice Paid", invoice_total:786, total_days:3, within_10_days:true, offer_appt_3_days:true, contact_within_3_days:true, date_created:"06/01/2026", date_first_update:"06/01/2026", date_statement:"13/01/2026", date_report:"16/01/2026", sla1_days:0, sla1_pass:true, sla2_days:3, sla2_pass:true, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Douglas, Bill" },
    { month:"Jan", case_number:"1129101", reference:"300102821", case_type:"Large Loss", case_status:"Invoice Paid", invoice_total:960, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"02/01/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Booker, David" }
  ]
};
