// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  And-E
// File:    itb.js
// Period:  Jan–Dec 2026
// Updated: 11 May 2026
// GENERATED AUTOMATICALLY — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {

  client_name:                  "And-E",
  report_period:                "Jan–Dec 2026",
  last_updated:                 "11 May 2026",
  is_rtc_client:                false,
  total_cases:                  51,

  avg_days_creation_to_update:         3.8,
  avg_days_creation_to_update_general: 3.8,
  avg_days_stmt_to_report:             9.6,
  avg_days_stmt_to_report_rtc:         0,
  avg_days_stmt_to_report_general:     9.6,

  sla_ack_pct:                  100,
  sla_contact_pct:              100,
  sla_update_pct:               76,
  sla_report_general_pct:       18,
  sla_report_rtc_pct:           null,
  has_rtc_cases:                false,
  has_general_cases:            true,
  sla_compliance_pct:           74,
  sla_met:                      6,
  sla_not_met:                  28,

  avg_fee_rtc:                  0,
  avg_fee_general:              595.25,
  total_fees_rtc:               0,
  total_fees_general:           30357.87,
  rtc_case_count:               0,
  general_case_count:           51,
  fees_by_type: [
    { type:"Motor Fraud", is_rtc:false, case_count:34, total_fees:21261.87, avg_fee:625.35 },
    { type:"Large Loss", is_rtc:false, case_count:11, total_fees:6192, avg_fee:562.91 },
    { type:"Motor Theft", is_rtc:false, case_count:3, total_fees:2160, avg_fee:720 },
    { type:"Motor Liability", is_rtc:false, case_count:2, total_fees:600, avg_fee:300 },
    { type:"Intelligence Report", is_rtc:false, case_count:1, total_fees:144, avg_fee:144 }
  ],

  monthly: [
    { month:"Jan", month_num:1, case_count:16, case_count_rtc:0, case_count_general:16, total_fees:10031.62, ave_fees:626.98, total_fees_rtc:0, total_fees_general:10031.62, ave_days_creation_to_update:6.1, ave_days_creation_to_update_general:6.1, ave_days_stmt_to_report:7.2, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:7.2, sla_ack_pct:100, sla_ack_met:12, sla_ack_n:12, sla_contact_pct:100, sla_contact_met:12, sla_contact_n:12, sla_update_pct:67, sla_update_met:8, sla_update_n:12, sla_report_general_pct:20, sla_report_general_met:2, sla_report_general_n:10, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:74, sla_met:2, sla_not_met:8 },
    { month:"Feb", month_num:2, case_count:13, case_count_rtc:0, case_count_general:13, total_fees:8992.25, ave_fees:691.71, total_fees_rtc:0, total_fees_general:8992.25, ave_days_creation_to_update:2.1, ave_days_creation_to_update_general:2.1, ave_days_stmt_to_report:9.2, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:9.2, sla_ack_pct:100, sla_ack_met:10, sla_ack_n:10, sla_contact_pct:100, sla_contact_met:10, sla_contact_n:10, sla_update_pct:90, sla_update_met:9, sla_update_n:10, sla_report_general_pct:20, sla_report_general_met:2, sla_report_general_n:10, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:78, sla_met:2, sla_not_met:8 },
    { month:"Mar", month_num:3, case_count:14, case_count_rtc:0, case_count_general:14, total_fees:9804, ave_fees:700.29, total_fees_rtc:0, total_fees_general:9804, ave_days_creation_to_update:3.3, ave_days_creation_to_update_general:3.3, ave_days_stmt_to_report:13.1, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:13.1, sla_ack_pct:100, sla_ack_met:12, sla_ack_n:12, sla_contact_pct:100, sla_contact_met:12, sla_contact_n:12, sla_update_pct:75, sla_update_met:9, sla_update_n:12, sla_report_general_pct:18, sla_report_general_met:2, sla_report_general_n:11, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:74, sla_met:2, sla_not_met:9 },
    { month:"Apr", month_num:4, case_count:8, case_count_rtc:0, case_count_general:8, total_fees:1530, ave_fees:191.25, total_fees_rtc:0, total_fees_general:1530, ave_days_creation_to_update:2.7, ave_days_creation_to_update_general:2.7, ave_days_stmt_to_report:6.7, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:6.7, sla_ack_pct:100, sla_ack_met:3, sla_ack_n:3, sla_contact_pct:100, sla_contact_met:3, sla_contact_n:3, sla_update_pct:67, sla_update_met:2, sla_update_n:3, sla_report_general_pct:0, sla_report_general_met:0, sla_report_general_n:3, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:67, sla_met:0, sla_not_met:3 },
    { month:"May", month_num:5, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Jun", month_num:6, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Jul", month_num:7, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Aug", month_num:8, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Sep", month_num:9, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Oct", month_num:10, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Nov", month_num:11, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Dec", month_num:12, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 }
  ],

  cases: [
    { ref:"1129101", client_ref:"300102821", type:"Large Loss", status:"Interview date / time TBC", created:"2 Jan 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:960, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1129301", client_ref:"SWI0358781", type:"Motor Fraud", status:"Invoiced", created:"6 Jan 2026", first_updated:"8 Jan 2026", stmt_date:"", report_sent:"", days_creation_to_update:2, days_stmt_to_report:null, invoice:786, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1129701", client_ref:"300108575", type:"Motor Fraud", status:"Invoice Paid", created:"6 Jan 2026", first_updated:"6 Jan 2026", stmt_date:"13 Jan 2026", report_sent:"16 Jan 2026", days_creation_to_update:0, days_stmt_to_report:3, invoice:786, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1129801", client_ref:"300108191", type:"Motor Fraud", status:"Invoice Paid", created:"7 Jan 2026", first_updated:"8 Jan 2026", stmt_date:"13 Jan 2026", report_sent:"19 Jan 2026", days_creation_to_update:1, days_stmt_to_report:6, invoice:786, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1130101", client_ref:"300109328", type:"Motor Liability", status:"Invoice Paid", created:"8 Jan 2026", first_updated:"15 Jan 2026", stmt_date:"19 Jan 2026", report_sent:"2 Feb 2026", days_creation_to_update:7, days_stmt_to_report:14, invoice:300, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1130801", client_ref:"300109201", type:"Motor Theft", status:"Invoice Paid", created:"12 Jan 2026", first_updated:"12 Jan 2026", stmt_date:"20 Jan 2026", report_sent:"26 Jan 2026", days_creation_to_update:0, days_stmt_to_report:6, invoice:540, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1131301", client_ref:"300109146", type:"Motor Fraud", status:"Invoice Paid", created:"13 Jan 2026", first_updated:"15 Jan 2026", stmt_date:"9 Feb 2026", report_sent:"10 Feb 2026", days_creation_to_update:2, days_stmt_to_report:1, invoice:690, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1131701", client_ref:"300109130", type:"Motor Theft", status:"Invoice Paid", created:"15 Jan 2026", first_updated:"26 Feb 2026", stmt_date:"28 Jan 2026", report_sent:"4 Feb 2026", days_creation_to_update:42, days_stmt_to_report:7, invoice:810, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1131801", client_ref:"300108802", type:"Motor Fraud", status:"Appointment made", created:"15 Jan 2026", first_updated:"16 Jan 2026", stmt_date:"", report_sent:"", days_creation_to_update:1, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1131901", client_ref:"300047377", type:"Intelligence Report", status:"Invoice Paid", created:"16 Jan 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:144, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1132401", client_ref:"300104447", type:"Large Loss", status:"Invoice Paid", created:"20 Jan 2026", first_updated:"21 Jan 2026", stmt_date:"23 Jan 2026", report_sent:"29 Jan 2026", days_creation_to_update:1, days_stmt_to_report:6, invoice:780, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1132701", client_ref:"300105397", type:"Motor Fraud", status:"Witness stmnt being obtained", created:"21 Jan 2026", first_updated:"22 Jan 2026", stmt_date:"7 Feb 2026", report_sent:"20 Feb 2026", days_creation_to_update:1, days_stmt_to_report:13, invoice:882, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1133001", client_ref:"300109996", type:"Large Loss", status:"Cold Calls being undertaken", created:"22 Jan 2026", first_updated:"30 Jan 2026", stmt_date:"4 Feb 2026", report_sent:"12 Feb 2026", days_creation_to_update:8, days_stmt_to_report:8, invoice:780, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1133301", client_ref:"300109297", type:"Motor Fraud", status:"Invoice Paid", created:"23 Jan 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:96, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1133801", client_ref:"300109707", type:"Motor Fraud", status:"Interview date / time TBC", created:"28 Jan 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:96, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1133901", client_ref:"300109984", type:"Motor Fraud", status:"Invoice Paid", created:"29 Jan 2026", first_updated:"6 Feb 2026", stmt_date:"17 Mar 2026", report_sent:"25 Mar 2026", days_creation_to_update:8, days_stmt_to_report:8, invoice:1595.62, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1134702", client_ref:"300110169", type:"Motor Fraud", status:"Invoice Paid", created:"3 Feb 2026", first_updated:"9 Feb 2026", stmt_date:"13 Feb 2026", report_sent:"20 Feb 2026", days_creation_to_update:6, days_stmt_to_report:7, invoice:1513.25, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1135102", client_ref:"300107668", type:"Motor Fraud", status:"Invoice Paid", created:"4 Feb 2026", first_updated:"8 Feb 2026", stmt_date:"8 Feb 2026", report_sent:"10 Feb 2026", days_creation_to_update:4, days_stmt_to_report:2, invoice:786, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1136202", client_ref:"300110924", type:"Motor Fraud", status:"Invoice Paid", created:"6 Feb 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1136702", client_ref:"300102977", type:"Motor Fraud", status:"Invoice Paid", created:"10 Feb 2026", first_updated:"10 Feb 2026", stmt_date:"6 Mar 2026", report_sent:"17 Mar 2026", days_creation_to_update:0, days_stmt_to_report:11, invoice:690, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1138002", client_ref:"300111166", type:"Motor Fraud", status:"Invoiced", created:"13 Feb 2026", first_updated:"16 Feb 2026", stmt_date:"17 Feb 2026", report_sent:"24 Feb 2026", days_creation_to_update:3, days_stmt_to_report:7, invoice:861, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1138902", client_ref:"300112045", type:"Large Loss", status:"Invoice Paid", created:"18 Feb 2026", first_updated:"18 Feb 2026", stmt_date:"26 Feb 2026", report_sent:"5 Mar 2026", days_creation_to_update:0, days_stmt_to_report:7, invoice:636, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1139002", client_ref:"300111102", type:"Motor Fraud", status:"Invoice Paid", created:"18 Feb 2026", first_updated:"18 Feb 2026", stmt_date:"27 Feb 2026", report_sent:"16 Mar 2026", days_creation_to_update:0, days_stmt_to_report:17, invoice:690, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1139102", client_ref:"300108654", type:"Motor Fraud", status:"Invoice Paid", created:"18 Feb 2026", first_updated:"18 Feb 2026", stmt_date:"3 Mar 2026", report_sent:"13 Mar 2026", days_creation_to_update:0, days_stmt_to_report:10, invoice:738, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1139402", client_ref:"300102603", type:"Motor Fraud", status:"Invoice Paid", created:"18 Feb 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:360, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1139902", client_ref:"300109982", type:"Motor Fraud", status:"Invoice Paid", created:"19 Feb 2026", first_updated:"19 Feb 2026", stmt_date:"3 Mar 2026", report_sent:"9 Mar 2026", days_creation_to_update:0, days_stmt_to_report:6, invoice:690, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1140302", client_ref:"300110800", type:"Motor Fraud", status:"Invoice Paid", created:"19 Feb 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:192, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1140402", client_ref:"300110494", type:"Motor Fraud", status:"Invoice Paid", created:"20 Feb 2026", first_updated:"25 Feb 2026", stmt_date:"3 Mar 2026", report_sent:"6 Mar 2026", days_creation_to_update:5, days_stmt_to_report:3, invoice:1026, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1141602", client_ref:"300112029", type:"Motor Theft", status:"Invoice Paid", created:"27 Feb 2026", first_updated:"2 Mar 2026", stmt_date:"3 Mar 2026", report_sent:"25 Mar 2026", days_creation_to_update:3, days_stmt_to_report:22, invoice:810, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1142403", client_ref:"300112274", type:"Motor Fraud", status:"Invoice Paid", created:"4 Mar 2026", first_updated:"4 Mar 2026", stmt_date:"12 Mar 2026", report_sent:"31 Mar 2026", days_creation_to_update:0, days_stmt_to_report:19, invoice:1122, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1142703", client_ref:"300110774", type:"Large Loss", status:"Invoice Paid", created:"5 Mar 2026", first_updated:"6 Mar 2026", stmt_date:"17 Mar 2026", report_sent:"23 Mar 2026", days_creation_to_update:1, days_stmt_to_report:6, invoice:540, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1143003", client_ref:"300112978", type:"Large Loss", status:"HELIX TRIAGE", created:"6 Mar 2026", first_updated:"12 Mar 2026", stmt_date:"24 Mar 2026", report_sent:"30 Mar 2026", days_creation_to_update:6, days_stmt_to_report:6, invoice:636, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1144203", client_ref:"300112756", type:"Large Loss", status:"Documents Submitted", created:"12 Mar 2026", first_updated:"12 Mar 2026", stmt_date:"18 Mar 2026", report_sent:"20 Mar 2026", days_creation_to_update:0, days_stmt_to_report:2, invoice:540, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1144803", client_ref:"300112137", type:"Motor Fraud", status:"Invoice Paid", created:"12 Mar 2026", first_updated:"23 Mar 2026", stmt_date:"25 Mar 2026", report_sent:"23 Apr 2026", days_creation_to_update:11, days_stmt_to_report:29, invoice:978, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1145803", client_ref:"300113045", type:"Large Loss", status:"Invoiced", created:"19 Mar 2026", first_updated:"19 Mar 2026", stmt_date:"24 Mar 2026", report_sent:"1 Apr 2026", days_creation_to_update:0, days_stmt_to_report:8, invoice:540, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1145903", client_ref:"300110661", type:"Large Loss", status:"Invoice Paid", created:"19 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:240, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1146203", client_ref:"300112197", type:"Motor Fraud", status:"Invoiced", created:"23 Mar 2026", first_updated:"25 Mar 2026", stmt_date:"7 Apr 2026", report_sent:"10 Apr 2026", days_creation_to_update:2, days_stmt_to_report:3, invoice:1206, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1146303", client_ref:"AND-324506", type:"Motor Fraud", status:"Invoiced", created:"23 Mar 2026", first_updated:"23 Mar 2026", stmt_date:"30 Mar 2026", report_sent:"7 Apr 2026", days_creation_to_update:0, days_stmt_to_report:8, invoice:930, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1147003", client_ref:"300112937", type:"Motor Fraud", status:"Invoice Paid", created:"23 Mar 2026", first_updated:"25 Mar 2026", stmt_date:"7 Apr 2026", report_sent:"22 Apr 2026", days_creation_to_update:2, days_stmt_to_report:15, invoice:690, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1148303", client_ref:"300113259", type:"Motor Fraud", status:"Await PH response / HUB done", created:"26 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1148503", client_ref:"300078612", type:"Motor Fraud", status:"Invoiced", created:"27 Mar 2026", first_updated:"30 Mar 2026", stmt_date:"20 Apr 2026", report_sent:"1 May 2026", days_creation_to_update:3, days_stmt_to_report:11, invoice:882, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1148803", client_ref:"300113891", type:"Motor Fraud", status:"Invoice Paid", created:"30 Mar 2026", first_updated:"31 Mar 2026", stmt_date:"", report_sent:"", days_creation_to_update:1, days_stmt_to_report:null, invoice:690, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1148903", client_ref:"300114409", type:"Motor Fraud", status:"Invoice Paid", created:"30 Mar 2026", first_updated:"13 Apr 2026", stmt_date:"21 Mar 2026", report_sent:"27 Apr 2026", days_creation_to_update:14, days_stmt_to_report:37, invoice:810, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1150604", client_ref:"300113486", type:"Motor Liability", status:"Invoiced", created:"2 Apr 2026", first_updated:"9 Apr 2026", stmt_date:"10 Apr 2026", report_sent:"15 Apr 2026", days_creation_to_update:7, days_stmt_to_report:5, invoice:300, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1152104", client_ref:"300114781", type:"Large Loss", status:"Invoice Paid", created:"8 Apr 2026", first_updated:"8 Apr 2026", stmt_date:"10 Apr 2026", report_sent:"14 Apr 2026", days_creation_to_update:0, days_stmt_to_report:4, invoice:540, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1152704", client_ref:"300114712", type:"Large Loss", status:"Awaiting further advises", created:"8 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1155404", client_ref:"300115529", type:"Motor Fraud", status:"Documents Submitted", created:"14 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1155504", client_ref:"300115057", type:"Motor Fraud", status:"Invoiced", created:"14 Apr 2026", first_updated:"15 Apr 2026", stmt_date:"20 Apr 2026", report_sent:"1 May 2026", days_creation_to_update:1, days_stmt_to_report:11, invoice:690, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1157304", client_ref:"300114794", type:"Motor Fraud", status:"Documents Submitted", created:"17 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1158104", client_ref:"300109402", type:"Motor Fraud", status:"Await PH response / HUB done", created:"21 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1159804", client_ref:"300115578", type:"Motor Fraud", status:"Await PH response / HUB done", created:"28 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 }
  ]

};
