// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  And-E
// File:    ande.js
// Period:  Jan–May 2026
// Updated: 31 May 2026
// GENERATED AUTOMATICALLY FROM TrackOps CSV — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {
  "client_name": "And-E",
  "report_period": "Jan–May 2026",
  "last_updated": "31 May 2026",
  "is_rtc_client": false,
  "total_cases": 52,
  "avg_days_creation_to_update": 6.1,
  "avg_days_creation_to_update_general": 6.1,
  "avg_days_stmt_to_report": 10.1,
  "avg_days_stmt_to_report_rtc": 0,
  "avg_days_stmt_to_report_general": 10.1,
  "sla_ack_pct": 100,
  "sla_contact_pct": 100,
  "sla_update_pct": 70,
  "sla_report_general_pct": 18,
  "sla_report_rtc_pct": null,
  "has_rtc_cases": false,
  "has_general_cases": true,
  "sla_compliance_pct": 72,
  "sla_met": 6,
  "sla_not_met": 28,
  "avg_fee_rtc": 0,
  "avg_fee_general": 501.65,
  "total_fees_rtc": 0,
  "total_fees_general": 26085.72,
  "rtc_case_count": 0,
  "general_case_count": 52,
  "fees_by_type": [
    {
      "type": "Motor Fraud",
      "is_rtc": false,
      "case_count": 39,
      "total_fees": 21005.72,
      "avg_fee": 538.61
    },
    {
      "type": "Large Loss",
      "is_rtc": false,
      "case_count": 9,
      "total_fees": 3160,
      "avg_fee": 351.11
    },
    {
      "type": "Motor Theft",
      "is_rtc": false,
      "case_count": 3,
      "total_fees": 1800,
      "avg_fee": 600
    },
    {
      "type": "Intelligence Report",
      "is_rtc": false,
      "case_count": 1,
      "total_fees": 120,
      "avg_fee": 120
    }
  ],
  "total_invoiced_lineitems": 26085.72,
  "total_lineitem_count": 80,
  "fees_by_item": [
    {
      "item": "Stage 1 Investigation",
      "is_rtc": false,
      "count": 29,
      "total": 16100,
      "avg": 555.17
    },
    {
      "item": "Large Loss Investigation",
      "is_rtc": false,
      "count": 5,
      "total": 2250,
      "avg": 450
    },
    {
      "item": "Stage 2 Investigation",
      "is_rtc": false,
      "count": 11,
      "total": 2050,
      "avg": 186.36
    },
    {
      "item": "Cold Calls",
      "is_rtc": false,
      "count": 13,
      "total": 1520,
      "avg": 116.92
    },
    {
      "item": "Motor Theft Investigation",
      "is_rtc": false,
      "count": 3,
      "total": 1400,
      "avg": 466.67
    },
    {
      "item": "Interpreter (full day)",
      "is_rtc": false,
      "count": 2,
      "total": 650,
      "avg": 325
    },
    {
      "item": "Miscellanoeus",
      "is_rtc": false,
      "count": 6,
      "total": 635,
      "avg": 105.83
    },
    {
      "item": "Translation services",
      "is_rtc": false,
      "count": 2,
      "total": 550.72,
      "avg": 275.36
    },
    {
      "item": "Interpreter (1/2 day)",
      "is_rtc": false,
      "count": 2,
      "total": 370,
      "avg": 185
    },
    {
      "item": "Failed Appointment",
      "is_rtc": false,
      "count": 4,
      "total": 280,
      "avg": 70
    },
    {
      "item": "Helix  (Triage only)",
      "is_rtc": false,
      "count": 2,
      "total": 160,
      "avg": 80
    },
    {
      "item": "Intelligence Report Only",
      "is_rtc": false,
      "count": 1,
      "total": 120,
      "avg": 120
    }
  ],
  "monthly": [
    {
      "month": "Jan",
      "month_num": 1,
      "case_count": 13,
      "case_count_rtc": 0,
      "case_count_general": 13,
      "total_fees": 7539.68,
      "ave_fees": 580,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 7,
      "ave_days_creation_to_update_general": 7,
      "ave_days_stmt_to_report": 6.6,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 6.6,
      "sla_ack_pct": 100,
      "sla_ack_met": 13,
      "sla_ack_n": 13,
      "sla_contact_pct": 100,
      "sla_contact_met": 13,
      "sla_contact_n": 13,
      "sla_update_pct": 67,
      "sla_update_met": 6,
      "sla_update_n": 9,
      "sla_report_general_pct": 22,
      "sla_report_general_met": 2,
      "sla_report_general_n": 9,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 72,
      "sla_met": 2,
      "sla_not_met": 7
    },
    {
      "month": "Feb",
      "month_num": 2,
      "case_count": 12,
      "case_count_rtc": 0,
      "case_count_general": 12,
      "total_fees": 6976.04,
      "ave_fees": 581,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 2.3,
      "ave_days_creation_to_update_general": 2.3,
      "ave_days_stmt_to_report": 9.4,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 9.4,
      "sla_ack_pct": 100,
      "sla_ack_met": 12,
      "sla_ack_n": 12,
      "sla_contact_pct": 100,
      "sla_contact_met": 12,
      "sla_contact_n": 12,
      "sla_update_pct": 89,
      "sla_update_met": 8,
      "sla_update_n": 9,
      "sla_report_general_pct": 22,
      "sla_report_general_met": 2,
      "sla_report_general_n": 9,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 78,
      "sla_met": 2,
      "sla_not_met": 7
    },
    {
      "month": "Mar",
      "month_num": 3,
      "case_count": 13,
      "case_count_rtc": 0,
      "case_count_general": 13,
      "total_fees": 8335,
      "ave_fees": 641,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 8.4,
      "ave_days_creation_to_update_general": 8.4,
      "ave_days_stmt_to_report": 13.1,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 13.1,
      "sla_ack_pct": 100,
      "sla_ack_met": 13,
      "sla_ack_n": 13,
      "sla_contact_pct": 100,
      "sla_contact_met": 13,
      "sla_contact_n": 13,
      "sla_update_pct": 67,
      "sla_update_met": 8,
      "sla_update_n": 12,
      "sla_report_general_pct": 18,
      "sla_report_general_met": 2,
      "sla_report_general_n": 11,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 71,
      "sla_met": 2,
      "sla_not_met": 9
    },
    {
      "month": "Apr",
      "month_num": 4,
      "case_count": 6,
      "case_count_rtc": 0,
      "case_count_general": 6,
      "total_fees": 2085,
      "ave_fees": 348,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 9,
      "ave_days_creation_to_update_general": 9,
      "ave_days_stmt_to_report": 13,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 13,
      "sla_ack_pct": 100,
      "sla_ack_met": 6,
      "sla_ack_n": 6,
      "sla_contact_pct": 100,
      "sla_contact_met": 6,
      "sla_contact_n": 6,
      "sla_update_pct": 25,
      "sla_update_met": 1,
      "sla_update_n": 4,
      "sla_report_general_pct": 0,
      "sla_report_general_met": 0,
      "sla_report_general_n": 3,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 56,
      "sla_met": 0,
      "sla_not_met": 3
    },
    {
      "month": "May",
      "month_num": 5,
      "case_count": 8,
      "case_count_rtc": 0,
      "case_count_general": 8,
      "total_fees": 1150,
      "ave_fees": 144,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 1.7,
      "ave_days_creation_to_update_general": 1.7,
      "ave_days_stmt_to_report": 8.5,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 8.5,
      "sla_ack_pct": 100,
      "sla_ack_met": 8,
      "sla_ack_n": 8,
      "sla_contact_pct": 100,
      "sla_contact_met": 8,
      "sla_contact_n": 8,
      "sla_update_pct": 100,
      "sla_update_met": 3,
      "sla_update_n": 3,
      "sla_report_general_pct": 0,
      "sla_report_general_met": 0,
      "sla_report_general_n": 2,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 75,
      "sla_met": 0,
      "sla_not_met": 2
    },
    {
      "month": "Jun",
      "month_num": 6,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Jul",
      "month_num": 7,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Aug",
      "month_num": 8,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Sep",
      "month_num": 9,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Oct",
      "month_num": 10,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Nov",
      "month_num": 11,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Dec",
      "month_num": 12,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    }
  ],
  "cases": [
    {
      "ref": "1168105",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Appointment made",
      "created": "29 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1167505",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Appointment made",
      "created": "27 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1165205",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Await PH response / HUB done",
      "created": "19 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1163705",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Appointment made",
      "created": "14 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1162805",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "12 May 2026",
      "first_updated": "12 May 2026",
      "stmt_date": "20 May 2026",
      "report_sent": "1 Jun 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 12,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1161205",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Reviewed, signed off & sent",
      "created": "5 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 575,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1161105",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "HELIX TRIAGE",
      "created": "5 May 2026",
      "first_updated": "10 May 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 5,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1161005",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "5 May 2026",
      "first_updated": "5 May 2026",
      "stmt_date": "7 May 2026",
      "report_sent": "12 May 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 5,
      "invoice": 575,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1159804",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Appointment made",
      "created": "28 Apr 2026",
      "first_updated": "18 May 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 20,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1158104",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Statement obtained",
      "created": "21 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1157304",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "17 Apr 2026",
      "first_updated": "26 Apr 2026",
      "stmt_date": "4 May 2026",
      "report_sent": "11 May 2026",
      "days_creation_to_update": 9,
      "days_stmt_to_report": 7,
      "invoice": 575,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1155504",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "14 Apr 2026",
      "first_updated": "15 Apr 2026",
      "stmt_date": "20 Apr 2026",
      "report_sent": "1 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 11,
      "invoice": 575,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1155404",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "14 Apr 2026",
      "first_updated": "20 Apr 2026",
      "stmt_date": "23 Apr 2026",
      "report_sent": "14 May 2026",
      "days_creation_to_update": 6,
      "days_stmt_to_report": 21,
      "invoice": 935,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1152704",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Interview date / time TBC",
      "created": "8 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1148903",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "30 Mar 2026",
      "first_updated": "13 Apr 2026",
      "stmt_date": "21 Mar 2026",
      "report_sent": "27 Apr 2026",
      "days_creation_to_update": 14,
      "days_stmt_to_report": 37,
      "invoice": 675,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1148803",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "30 Mar 2026",
      "first_updated": "31 Mar 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 1,
      "days_stmt_to_report": null,
      "invoice": 575,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1148503",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "27 Mar 2026",
      "first_updated": "30 Mar 2026",
      "stmt_date": "20 Apr 2026",
      "report_sent": "1 May 2026",
      "days_creation_to_update": 3,
      "days_stmt_to_report": 11,
      "invoice": 735,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1148303",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "26 Mar 2026",
      "first_updated": "26 May 2026",
      "stmt_date": "11 May 2026",
      "report_sent": "13 May 2026",
      "days_creation_to_update": 61,
      "days_stmt_to_report": 2,
      "invoice": 535,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1147003",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "23 Mar 2026",
      "first_updated": "25 Mar 2026",
      "stmt_date": "7 Apr 2026",
      "report_sent": "22 Apr 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 15,
      "invoice": 575,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1146303",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "23 Mar 2026",
      "first_updated": "23 Mar 2026",
      "stmt_date": "30 Mar 2026",
      "report_sent": "7 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 8,
      "invoice": 775,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1146203",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "23 Mar 2026",
      "first_updated": "25 Mar 2026",
      "stmt_date": "7 Apr 2026",
      "report_sent": "10 Apr 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 3,
      "invoice": 1005,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1145903",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "19 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 200,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1145803",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "19 Mar 2026",
      "first_updated": "19 Mar 2026",
      "stmt_date": "24 Mar 2026",
      "report_sent": "1 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 8,
      "invoice": 450,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1144803",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "12 Mar 2026",
      "first_updated": "23 Mar 2026",
      "stmt_date": "25 Mar 2026",
      "report_sent": "23 Apr 2026",
      "days_creation_to_update": 11,
      "days_stmt_to_report": 29,
      "invoice": 815,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1143003",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "6 Mar 2026",
      "first_updated": "12 Mar 2026",
      "stmt_date": "24 Mar 2026",
      "report_sent": "30 Mar 2026",
      "days_creation_to_update": 6,
      "days_stmt_to_report": 6,
      "invoice": 610,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1142703",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "5 Mar 2026",
      "first_updated": "6 Mar 2026",
      "stmt_date": "17 Mar 2026",
      "report_sent": "23 Mar 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 6,
      "invoice": 450,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1142403",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "4 Mar 2026",
      "first_updated": "4 Mar 2026",
      "stmt_date": "12 Mar 2026",
      "report_sent": "31 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 19,
      "invoice": 935,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1141602",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "27 Feb 2026",
      "first_updated": "2 Mar 2026",
      "stmt_date": "3 Mar 2026",
      "report_sent": "25 Mar 2026",
      "days_creation_to_update": 3,
      "days_stmt_to_report": 22,
      "invoice": 675,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1140402",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "20 Feb 2026",
      "first_updated": "25 Feb 2026",
      "stmt_date": "3 Mar 2026",
      "report_sent": "6 Mar 2026",
      "days_creation_to_update": 5,
      "days_stmt_to_report": 3,
      "invoice": 855,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1140302",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "19 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1139902",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "19 Feb 2026",
      "first_updated": "19 Feb 2026",
      "stmt_date": "3 Mar 2026",
      "report_sent": "9 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 6,
      "invoice": 575,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1139402",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "18 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 300,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1139102",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "18 Feb 2026",
      "first_updated": "18 Feb 2026",
      "stmt_date": "3 Mar 2026",
      "report_sent": "13 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 10,
      "invoice": 615,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1139002",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "18 Feb 2026",
      "first_updated": "18 Feb 2026",
      "stmt_date": "27 Feb 2026",
      "report_sent": "16 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 17,
      "invoice": 575,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1138002",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "13 Feb 2026",
      "first_updated": "16 Feb 2026",
      "stmt_date": "17 Feb 2026",
      "report_sent": "24 Feb 2026",
      "days_creation_to_update": 3,
      "days_stmt_to_report": 7,
      "invoice": 730,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1136702",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "10 Feb 2026",
      "first_updated": "10 Feb 2026",
      "stmt_date": "6 Mar 2026",
      "report_sent": "17 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 11,
      "invoice": 575,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1136202",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "6 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1135102",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "4 Feb 2026",
      "first_updated": "8 Feb 2026",
      "stmt_date": "8 Feb 2026",
      "report_sent": "10 Feb 2026",
      "days_creation_to_update": 4,
      "days_stmt_to_report": 2,
      "invoice": 655,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1134702",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "3 Feb 2026",
      "first_updated": "9 Feb 2026",
      "stmt_date": "13 Feb 2026",
      "report_sent": "20 Feb 2026",
      "days_creation_to_update": 6,
      "days_stmt_to_report": 7,
      "invoice": 1261.04,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1133901",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "29 Jan 2026",
      "first_updated": "6 Feb 2026",
      "stmt_date": "17 Mar 2026",
      "report_sent": "25 Mar 2026",
      "days_creation_to_update": 8,
      "days_stmt_to_report": 8,
      "invoice": 1329.68,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1133801",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Interview date / time TBC",
      "created": "28 Jan 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 80,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1133301",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "23 Jan 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 80,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1133001",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Witness stmnt being obtained",
      "created": "22 Jan 2026",
      "first_updated": "30 Jan 2026",
      "stmt_date": "4 Feb 2026",
      "report_sent": "12 Feb 2026",
      "days_creation_to_update": 8,
      "days_stmt_to_report": 8,
      "invoice": 650,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1132701",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Other statement obtained",
      "created": "21 Jan 2026",
      "first_updated": "22 Jan 2026",
      "stmt_date": "7 Feb 2026",
      "report_sent": "20 Feb 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 13,
      "invoice": 735,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1131901",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "16 Jan 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 120,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1131801",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "15 Jan 2026",
      "first_updated": "16 Jan 2026",
      "stmt_date": "12 May 2026",
      "report_sent": "19 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 7,
      "invoice": 735,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1131701",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "15 Jan 2026",
      "first_updated": "26 Feb 2026",
      "stmt_date": "28 Jan 2026",
      "report_sent": "4 Feb 2026",
      "days_creation_to_update": 42,
      "days_stmt_to_report": 7,
      "invoice": 675,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1131301",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "13 Jan 2026",
      "first_updated": "15 Jan 2026",
      "stmt_date": "9 Feb 2026",
      "report_sent": "10 Feb 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 1,
      "invoice": 575,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1130801",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "12 Jan 2026",
      "first_updated": "12 Jan 2026",
      "stmt_date": "20 Jan 2026",
      "report_sent": "26 Jan 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 6,
      "invoice": 450,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1129801",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "7 Jan 2026",
      "first_updated": "8 Jan 2026",
      "stmt_date": "13 Jan 2026",
      "report_sent": "19 Jan 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 6,
      "invoice": 655,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1129701",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "6 Jan 2026",
      "first_updated": "6 Jan 2026",
      "stmt_date": "13 Jan 2026",
      "report_sent": "16 Jan 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 3,
      "invoice": 655,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1129101",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Interview date / time TBC",
      "created": "2 Jan 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 800,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    }
  ]
};
