// ============================================================
// DLB INVESTIGATIONS LTD — CLIENT DATA FILE
// Client:       Transportation Claims Ltd
// Access Code:  TRANSPORT26
// Last Updated: 6 March 2026
// AUTO-GENERATED — do not edit manually
// ============================================================

var DLB_CLIENT_DATA = {
  client_name:   "Transportation Claims Ltd",
  report_period: "2026 Full Year",
  last_updated:  "6 March 2026",

  monthly: [
    { month:"Jan", month_num:1, total_fees:576, ave_fees:96, ave_days:0, case_count:6, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Feb", month_num:2, total_fees:852, ave_fees:94.67, ave_days:0, case_count:9, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Mar", month_num:3, total_fees:96, ave_fees:24, ave_days:0, case_count:4, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Apr", month_num:4, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"May", month_num:5, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Jun", month_num:6, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Jul", month_num:7, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Aug", month_num:8, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Sep", month_num:9, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Oct", month_num:10, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Nov", month_num:11, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 },
    { month:"Dec", month_num:12, total_fees:0, ave_fees:0, ave_days:0, case_count:0, sla_compliance_pct:0, sla1_compliance_pct:0, sla2_compliance_pct:0 }
  ],

  cases: [
    { month:"Mar", case_number:"1142503", reference:"1121942", case_type:"Intelligence Report", case_status:"KYC REPORT ONLY", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"05/03/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Mar", case_number:"1142103", reference:"A1123087", case_type:"Intelligence Report", case_status:"KYC REPORT ONLY", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"04/03/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Mar", case_number:"1142003", reference:"A0001181.AWC/JMJ", case_type:"Employers Liability", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"04/03/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Mar", case_number:"1141703", reference:"B1110372", case_type:"Intelligence Report", case_status:"Closed", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"02/03/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Feb", case_number:"1141502", reference:"B1053174", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"27/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Feb", case_number:"1139502", reference:"1119291", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"19/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Feb", case_number:"1138402", reference:"A1118689", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"16/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Feb", case_number:"1138102", reference:"B1116152", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"16/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Feb", case_number:"1137602", reference:"A1061199", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"12/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Feb", case_number:"1137002", reference:"Trace Results", case_type:"Trace and Locate only", case_status:"Invoiced", invoice_total:24, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"11/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Feb", case_number:"1135702", reference:"B1090518CC", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"06/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Feb", case_number:"1135502", reference:"", case_type:"Trace and Locate only", case_status:"Invoiced", invoice_total:252, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"05/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Feb", case_number:"1135402", reference:"", case_type:"Trace and Locate only", case_status:"Invoice Paid", invoice_total:0, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"05/02/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"" },
    { month:"Jan", case_number:"1134001", reference:"A1107825", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"29/01/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Jan", case_number:"1133701", reference:"A1109753", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"28/01/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Jan", case_number:"1132501", reference:"A1083567", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"20/01/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Jan", case_number:"1131201", reference:"A1092459", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"13/01/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Jan", case_number:"1130901", reference:"A0830151", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"12/01/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" },
    { month:"Jan", case_number:"1130301", reference:"A1045437", case_type:"Intelligence Report", case_status:"Invoiced", invoice_total:96, total_days:null, within_10_days:false, offer_appt_3_days:true, contact_within_3_days:true, date_created:"08/01/2026", date_first_update:"", date_statement:"", date_report:"", sla1_days:null, sla1_pass:null, sla2_days:null, sla2_pass:null, cold_call:"N/A", complaint:false, complaint_details:"", investigator:"Dale, Lesley" }
  ]
};
