// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  Transportation Claims Ltd
// File:    transportation.js
// Period:  Jan–May 2026
// Updated: 3 Jun 2026
// GENERATED AUTOMATICALLY FROM TrackOps CSV — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {
  "client_name": "Transportation Claims Ltd",
  "report_period": "Jan–May 2026",
  "last_updated": "3 Jun 2026",
  "is_rtc_client": false,
  "total_cases": 36,
  "avg_days_creation_to_update": 0,
  "avg_days_creation_to_update_general": 0,
  "avg_days_stmt_to_report": 0,
  "avg_days_stmt_to_report_rtc": 0,
  "avg_days_stmt_to_report_general": 0,
  "sla_ack_pct": 100,
  "sla_contact_pct": 100,
  "sla_update_pct": null,
  "sla_report_general_pct": null,
  "sla_report_rtc_pct": null,
  "has_rtc_cases": false,
  "has_general_cases": true,
  "sla_compliance_pct": 100,
  "sla_met": 0,
  "sla_not_met": 0,
  "avg_fee_rtc": 0,
  "avg_fee_general": 110,
  "total_fees_rtc": 0,
  "total_fees_general": 3960,
  "rtc_case_count": 0,
  "general_case_count": 36,
  "fees_by_type": [
    {
      "type": "Intelligence Report",
      "is_rtc": false,
      "case_count": 27,
      "total_fees": 2304,
      "avg_fee": 85.33
    },
    {
      "type": "Trace and Locate only",
      "is_rtc": false,
      "case_count": 6,
      "total_fees": 1464,
      "avg_fee": 244
    },
    {
      "type": "Surveillance",
      "is_rtc": false,
      "case_count": 1,
      "total_fees": 96,
      "avg_fee": 96
    },
    {
      "type": "Employers Liability",
      "is_rtc": false,
      "case_count": 1,
      "total_fees": 96,
      "avg_fee": 96
    },
    {
      "type": "Motor Fraud",
      "is_rtc": false,
      "case_count": 1,
      "total_fees": 0,
      "avg_fee": 0
    }
  ],
  "total_invoiced_lineitems": 3060,
  "total_lineitem_count": 28,
  "fees_by_item": [
    {
      "item": "Intelligence Report Only",
      "is_rtc": false,
      "count": 23,
      "total": 1840,
      "avg": 80
    },
    {
      "item": "Address checks & validation",
      "is_rtc": false,
      "count": 5,
      "total": 1220,
      "avg": 244
    }
  ],
  "monthly": [
    {
      "month": "Jan",
      "month_num": 1,
      "case_count": 6,
      "case_count_rtc": 0,
      "case_count_general": 6,
      "total_fees": 576,
      "ave_fees": 96,
      "total_fees_rtc": 0,
      "total_fees_general": 576,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": 100,
      "sla_ack_met": 6,
      "sla_ack_n": 6,
      "sla_contact_pct": 100,
      "sla_contact_met": 6,
      "sla_contact_n": 6,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 100,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Feb",
      "month_num": 2,
      "case_count": 9,
      "case_count_rtc": 0,
      "case_count_general": 9,
      "total_fees": 852,
      "ave_fees": 95,
      "total_fees_rtc": 0,
      "total_fees_general": 852,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": 100,
      "sla_ack_met": 9,
      "sla_ack_n": 9,
      "sla_contact_pct": 100,
      "sla_contact_met": 9,
      "sla_contact_n": 9,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 100,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Mar",
      "month_num": 3,
      "case_count": 8,
      "case_count_rtc": 0,
      "case_count_general": 8,
      "total_fees": 876,
      "ave_fees": 110,
      "total_fees_rtc": 0,
      "total_fees_general": 876,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": 100,
      "sla_ack_met": 8,
      "sla_ack_n": 8,
      "sla_contact_pct": 100,
      "sla_contact_met": 8,
      "sla_contact_n": 8,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 100,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Apr",
      "month_num": 4,
      "case_count": 5,
      "case_count_rtc": 0,
      "case_count_general": 5,
      "total_fees": 1176,
      "ave_fees": 235,
      "total_fees_rtc": 0,
      "total_fees_general": 1176,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": 100,
      "sla_ack_met": 5,
      "sla_ack_n": 5,
      "sla_contact_pct": 100,
      "sla_contact_met": 5,
      "sla_contact_n": 5,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 100,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "May",
      "month_num": 5,
      "case_count": 8,
      "case_count_rtc": 0,
      "case_count_general": 8,
      "total_fees": 480,
      "ave_fees": 60,
      "total_fees_rtc": 0,
      "total_fees_general": 480,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": 100,
      "sla_ack_met": 8,
      "sla_ack_n": 8,
      "sla_contact_pct": 100,
      "sla_contact_met": 8,
      "sla_contact_n": 8,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 100,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Jun",
      "month_num": 6,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Jul",
      "month_num": 7,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Aug",
      "month_num": 8,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Sep",
      "month_num": 9,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Oct",
      "month_num": 10,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Nov",
      "month_num": 11,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Dec",
      "month_num": 12,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    }
  ],
  "cases": [
    {
      "ref": "1168005",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "KYC REPORT ONLY",
      "created": "29 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1167905",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Closed",
      "created": "28 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1167805",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Reviewed, signed off & sent",
      "created": "28 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1167605",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoiced",
      "created": "28 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1166505",
      "client_ref": null,
      "type": "Surveillance",
      "status": "Invoiced",
      "created": "23 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1166405",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoiced",
      "created": "22 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1162605",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoiced",
      "created": "11 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1162505",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoiced",
      "created": "11 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1160204",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoiced",
      "created": "29 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1156304",
      "client_ref": null,
      "type": "Trace and Locate only",
      "status": "Invoiced",
      "created": "16 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 792,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1154004",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoiced",
      "created": "10 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1150504",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoiced",
      "created": "2 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1150404",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoiced",
      "created": "2 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1149303",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoiced",
      "created": "31 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1147103",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "23 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1143203",
      "client_ref": null,
      "type": "Trace and Locate only",
      "status": "Invoiced",
      "created": "10 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 384,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1143103",
      "client_ref": null,
      "type": "Trace and Locate only",
      "status": "Invoiced",
      "created": "9 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 12,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1142503",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "5 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1142103",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "4 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1142003",
      "client_ref": null,
      "type": "Employers Liability",
      "status": "Invoice Paid",
      "created": "4 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1141703",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Closed",
      "created": "2 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1141502",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "27 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1139502",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "19 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1138402",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "16 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1138102",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "16 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1137602",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "12 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1137002",
      "client_ref": null,
      "type": "Trace and Locate only",
      "status": "Invoiced",
      "created": "11 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 24,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1135702",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "6 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1135502",
      "client_ref": null,
      "type": "Trace and Locate only",
      "status": "Invoiced",
      "created": "5 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 252,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1135402",
      "client_ref": null,
      "type": "Trace and Locate only",
      "status": "Invoice Paid",
      "created": "5 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1134001",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "29 Jan 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1133701",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "28 Jan 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1132501",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "20 Jan 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1131201",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "13 Jan 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1130901",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "12 Jan 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1130301",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "8 Jan 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 96,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    }
  ]
};
