// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  Trinity Claims
// File:    trinity.js
// Period:  Jan–May 2026
// Updated: 31 May 2026
// GENERATED AUTOMATICALLY FROM TrackOps CSV — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {
  "client_name": "Trinity Claims",
  "report_period": "Jan–May 2026",
  "last_updated": "31 May 2026",
  "is_rtc_client": false,
  "total_cases": 46,
  "avg_days_creation_to_update": -1.3,
  "avg_days_creation_to_update_general": -1.3,
  "avg_days_stmt_to_report": -5,
  "avg_days_stmt_to_report_rtc": 0,
  "avg_days_stmt_to_report_general": -5,
  "sla_ack_pct": 100,
  "sla_contact_pct": 100,
  "sla_update_pct": 86,
  "sla_report_general_pct": 41,
  "sla_report_rtc_pct": null,
  "has_rtc_cases": false,
  "has_general_cases": true,
  "sla_compliance_pct": 82,
  "sla_met": 13,
  "sla_not_met": 19,
  "avg_fee_rtc": 0,
  "avg_fee_general": 318.74,
  "total_fees_rtc": 0,
  "total_fees_general": 14661.88,
  "rtc_case_count": 0,
  "general_case_count": 46,
  "fees_by_type": [
    {
      "type": "Motor Fraud",
      "is_rtc": false,
      "case_count": 15,
      "total_fees": 5879,
      "avg_fee": 391.93
    },
    {
      "type": "Household fraud claim",
      "is_rtc": false,
      "case_count": 14,
      "total_fees": 4985,
      "avg_fee": 356.07
    },
    {
      "type": "Motor Liability",
      "is_rtc": false,
      "case_count": 10,
      "total_fees": 2510,
      "avg_fee": 251
    },
    {
      "type": "Large Loss",
      "is_rtc": false,
      "case_count": 3,
      "total_fees": 1207.88,
      "avg_fee": 402.63
    },
    {
      "type": "Intelligence Report",
      "is_rtc": false,
      "case_count": 1,
      "total_fees": 80,
      "avg_fee": 80
    },
    {
      "type": "Surveillance",
      "is_rtc": false,
      "case_count": 2,
      "total_fees": 0,
      "avg_fee": 0
    },
    {
      "type": "Public Liability",
      "is_rtc": false,
      "case_count": 1,
      "total_fees": 0,
      "avg_fee": 0
    }
  ],
  "total_invoiced_lineitems": 14661.88,
  "total_lineitem_count": 55,
  "fees_by_item": [
    {
      "item": "Stage 1 Investigation",
      "is_rtc": false,
      "count": 20,
      "total": 9240,
      "avg": 462
    },
    {
      "item": "Motor Liability Investigation",
      "is_rtc": false,
      "count": 9,
      "total": 2075,
      "avg": 230.56
    },
    {
      "item": "Miscellanoeus",
      "is_rtc": false,
      "count": 8,
      "total": 720,
      "avg": 90
    },
    {
      "item": "Motor Theft Investigation",
      "is_rtc": false,
      "count": 1,
      "total": 400,
      "avg": 400
    },
    {
      "item": "Stage 2 Investigation",
      "is_rtc": false,
      "count": 2,
      "total": 400,
      "avg": 200
    },
    {
      "item": "Interpreter (1/2 day)",
      "is_rtc": false,
      "count": 2,
      "total": 370,
      "avg": 185
    },
    {
      "item": "Police Report",
      "is_rtc": false,
      "count": 2,
      "total": 362.88,
      "avg": 181.44
    },
    {
      "item": "Interpreter (full day)",
      "is_rtc": false,
      "count": 1,
      "total": 300,
      "avg": 300
    },
    {
      "item": "Cold Calls",
      "is_rtc": false,
      "count": 4,
      "total": 300,
      "avg": 75
    },
    {
      "item": "Intelligence Report Only",
      "is_rtc": false,
      "count": 2,
      "total": 200,
      "avg": 100
    },
    {
      "item": "Translation services",
      "is_rtc": false,
      "count": 1,
      "total": 114,
      "avg": 114
    },
    {
      "item": "Locus Report",
      "is_rtc": false,
      "count": 1,
      "total": 100,
      "avg": 100
    },
    {
      "item": "Failed Appointment",
      "is_rtc": false,
      "count": 2,
      "total": 80,
      "avg": 40
    }
  ],
  "monthly": [
    {
      "month": "Jan",
      "month_num": 1,
      "case_count": 8,
      "case_count_rtc": 0,
      "case_count_general": 8,
      "total_fees": 4697.88,
      "ave_fees": 587,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": -13.8,
      "ave_days_creation_to_update_general": -13.8,
      "ave_days_stmt_to_report": -39,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": -39,
      "sla_ack_pct": 100,
      "sla_ack_met": 8,
      "sla_ack_n": 8,
      "sla_contact_pct": 100,
      "sla_contact_met": 8,
      "sla_contact_n": 8,
      "sla_update_pct": 100,
      "sla_update_met": 8,
      "sla_update_n": 8,
      "sla_report_general_pct": 38,
      "sla_report_general_met": 3,
      "sla_report_general_n": 8,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 85,
      "sla_met": 3,
      "sla_not_met": 5
    },
    {
      "month": "Feb",
      "month_num": 2,
      "case_count": 13,
      "case_count_rtc": 0,
      "case_count_general": 13,
      "total_fees": 4055,
      "ave_fees": 312,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 3.9,
      "ave_days_creation_to_update_general": 3.9,
      "ave_days_stmt_to_report": 5.3,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 5.3,
      "sla_ack_pct": 100,
      "sla_ack_met": 13,
      "sla_ack_n": 13,
      "sla_contact_pct": 100,
      "sla_contact_met": 13,
      "sla_contact_n": 13,
      "sla_update_pct": 80,
      "sla_update_met": 8,
      "sla_update_n": 10,
      "sla_report_general_pct": 56,
      "sla_report_general_met": 5,
      "sla_report_general_n": 9,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 84,
      "sla_met": 5,
      "sla_not_met": 4
    },
    {
      "month": "Mar",
      "month_num": 3,
      "case_count": 14,
      "case_count_rtc": 0,
      "case_count_general": 14,
      "total_fees": 4659,
      "ave_fees": 333,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 3.4,
      "ave_days_creation_to_update_general": 3.4,
      "ave_days_stmt_to_report": 9.1,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 9.1,
      "sla_ack_pct": 100,
      "sla_ack_met": 14,
      "sla_ack_n": 14,
      "sla_contact_pct": 100,
      "sla_contact_met": 14,
      "sla_contact_n": 14,
      "sla_update_pct": 89,
      "sla_update_met": 8,
      "sla_update_n": 9,
      "sla_report_general_pct": 25,
      "sla_report_general_met": 2,
      "sla_report_general_n": 8,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 79,
      "sla_met": 2,
      "sla_not_met": 6
    },
    {
      "month": "Apr",
      "month_num": 4,
      "case_count": 7,
      "case_count_rtc": 0,
      "case_count_general": 7,
      "total_fees": 1000,
      "ave_fees": 143,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 3.2,
      "ave_days_creation_to_update_general": 3.2,
      "ave_days_stmt_to_report": 4.2,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 4.2,
      "sla_ack_pct": 100,
      "sla_ack_met": 7,
      "sla_ack_n": 7,
      "sla_contact_pct": 100,
      "sla_contact_met": 7,
      "sla_contact_n": 7,
      "sla_update_pct": 60,
      "sla_update_met": 3,
      "sla_update_n": 5,
      "sla_report_general_pct": 60,
      "sla_report_general_met": 3,
      "sla_report_general_n": 5,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 80,
      "sla_met": 3,
      "sla_not_met": 2
    },
    {
      "month": "May",
      "month_num": 5,
      "case_count": 4,
      "case_count_rtc": 0,
      "case_count_general": 4,
      "total_fees": 250,
      "ave_fees": 62,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": -7.7,
      "ave_days_creation_to_update_general": -7.7,
      "ave_days_stmt_to_report": 5.5,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 5.5,
      "sla_ack_pct": 100,
      "sla_ack_met": 4,
      "sla_ack_n": 4,
      "sla_contact_pct": 100,
      "sla_contact_met": 4,
      "sla_contact_n": 4,
      "sla_update_pct": 100,
      "sla_update_met": 3,
      "sla_update_n": 3,
      "sla_report_general_pct": 0,
      "sla_report_general_met": 0,
      "sla_report_general_n": 2,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 75,
      "sla_met": 0,
      "sla_not_met": 2
    },
    {
      "month": "Jun",
      "month_num": 6,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Jul",
      "month_num": 7,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Aug",
      "month_num": 8,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Sep",
      "month_num": 9,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Oct",
      "month_num": 10,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Nov",
      "month_num": 11,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Dec",
      "month_num": 12,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    }
  ],
  "cases": [
    {
      "ref": "1165505",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Statement obtained",
      "created": "20 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1163205",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "12 May 2026",
      "first_updated": "18 Apr 2026",
      "stmt_date": "27 May 2026",
      "report_sent": "1 Jun 2026",
      "days_creation_to_update": -24,
      "days_stmt_to_report": 5,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1162405",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Awaiting further advises",
      "created": "11 May 2026",
      "first_updated": "11 May 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 0,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1161805",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoiced",
      "created": "7 May 2026",
      "first_updated": "8 May 2026",
      "stmt_date": "20 May 2026",
      "report_sent": "26 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 6,
      "invoice": 250,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1157404",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Enquiries ongoing",
      "created": "17 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1156904",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Witness stmnt being obtained",
      "created": "16 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1156404",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Reviewed, signed off & sent",
      "created": "16 Apr 2026",
      "first_updated": "22 Apr 2026",
      "stmt_date": "26 May 2026",
      "report_sent": "3 Jun 2026",
      "days_creation_to_update": 6,
      "days_stmt_to_report": 8,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1154204",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "10 Apr 2026",
      "first_updated": "10 Apr 2026",
      "stmt_date": "21 Apr 2026",
      "report_sent": "23 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 2,
      "invoice": 285,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1152904",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "8 Apr 2026",
      "first_updated": "10 Apr 2026",
      "stmt_date": "20 Apr 2026",
      "report_sent": "22 Apr 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 2,
      "invoice": 225,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1151304",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "7 Apr 2026",
      "first_updated": "7 Apr 2026",
      "stmt_date": "14 Apr 2026",
      "report_sent": "17 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 3,
      "invoice": 225,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1149404",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "1 Apr 2026",
      "first_updated": "9 Apr 2026",
      "stmt_date": "25 Apr 2026",
      "report_sent": "1 May 2026",
      "days_creation_to_update": 8,
      "days_stmt_to_report": 6,
      "invoice": 265,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1147903",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoiced",
      "created": "25 Mar 2026",
      "first_updated": "26 Mar 2026",
      "stmt_date": "18 May 2026",
      "report_sent": "19 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 1,
      "invoice": 260,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1147703",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "25 Mar 2026",
      "first_updated": "24 Mar 2026",
      "stmt_date": "",
      "report_sent": "1 Apr 2026",
      "days_creation_to_update": -1,
      "days_stmt_to_report": 8,
      "invoice": 100,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": true,
      "sla_report_target_days": 3
    },
    {
      "ref": "1147603",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "25 Mar 2026",
      "first_updated": "25 Apr 2026",
      "stmt_date": "13 Apr 2026",
      "report_sent": "29 Apr 2026",
      "days_creation_to_update": 31,
      "days_stmt_to_report": 16,
      "invoice": 500,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1146603",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoice Paid",
      "created": "23 Mar 2026",
      "first_updated": "23 Mar 2026",
      "stmt_date": "13 Apr 2026",
      "report_sent": "16 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 3,
      "invoice": 460,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1146503",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "23 Mar 2026",
      "first_updated": "23 Mar 2026",
      "stmt_date": "26 Mar 2026",
      "report_sent": "2 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 7,
      "invoice": 500,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1145603",
      "client_ref": null,
      "type": "Surveillance",
      "status": "Invoice Paid",
      "created": "17 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1145503",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "17 Mar 2026",
      "first_updated": "17 Mar 2026",
      "stmt_date": "23 Apr 2026",
      "report_sent": "13 May 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 20,
      "invoice": 685,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1145303",
      "client_ref": null,
      "type": "Intelligence Report",
      "status": "Invoice Paid",
      "created": "16 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 80,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1145103",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "13 Mar 2026",
      "first_updated": "13 Mar 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 0,
      "days_stmt_to_report": null,
      "invoice": 674,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1144903",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoiced",
      "created": "12 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 120,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1144603",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "12 Mar 2026",
      "first_updated": "12 Mar 2026",
      "stmt_date": "17 Mar 2026",
      "report_sent": "31 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 14,
      "invoice": 700,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1144303",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoice Paid",
      "created": "12 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 120,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1143303",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoice Paid",
      "created": "10 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1142803",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoice Paid",
      "created": "6 Mar 2026",
      "first_updated": "6 Mar 2026",
      "stmt_date": "13 Mar 2026",
      "report_sent": "17 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 4,
      "invoice": 460,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1141102",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "25 Feb 2026",
      "first_updated": "27 Jan 2026",
      "stmt_date": "28 Feb 2026",
      "report_sent": "19 Mar 2026",
      "days_creation_to_update": -29,
      "days_stmt_to_report": 19,
      "invoice": 500,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1140102",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoice Paid",
      "created": "19 Feb 2026",
      "first_updated": "19 Feb 2026",
      "stmt_date": "26 Feb 2026",
      "report_sent": "10 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 12,
      "invoice": 460,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1140002",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "19 Feb 2026",
      "first_updated": "19 Feb 2026",
      "stmt_date": "23 Feb 2026",
      "report_sent": "24 Feb 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 1,
      "invoice": 500,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1139302",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "18 Feb 2026",
      "first_updated": "17 Mar 2026",
      "stmt_date": "2 Apr 2026",
      "report_sent": "2 Apr 2026",
      "days_creation_to_update": 27,
      "days_stmt_to_report": 0,
      "invoice": 340,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1138602",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "17 Feb 2026",
      "first_updated": "19 Feb 2026",
      "stmt_date": "9 Mar 2026",
      "report_sent": "9 Mar 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 0,
      "invoice": 250,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1138302",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "16 Feb 2026",
      "first_updated": "17 Feb 2026",
      "stmt_date": "26 Feb 2026",
      "report_sent": "4 Mar 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 6,
      "invoice": 620,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1137802",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoice Paid",
      "created": "13 Feb 2026",
      "first_updated": "18 Mar 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 33,
      "days_stmt_to_report": null,
      "invoice": 240,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1137702",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "12 Feb 2026",
      "first_updated": "17 Feb 2026",
      "stmt_date": "24 Feb 2026",
      "report_sent": "26 Feb 2026",
      "days_creation_to_update": 5,
      "days_stmt_to_report": 2,
      "invoice": 400,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1137102",
      "client_ref": null,
      "type": "Surveillance",
      "status": "Reviewed, signed off & sent",
      "created": "11 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "13 Mar 2026",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1136302",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "9 Feb 2026",
      "first_updated": "9 Feb 2026",
      "stmt_date": "16 Feb 2026",
      "report_sent": "18 Feb 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 2,
      "invoice": 225,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1135902",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoice Paid",
      "created": "6 Feb 2026",
      "first_updated": "6 Feb 2026",
      "stmt_date": "26 Feb 2026",
      "report_sent": "4 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 6,
      "invoice": 460,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1134902",
      "client_ref": null,
      "type": "Public Liability",
      "status": "Invoice Paid",
      "created": "3 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1134402",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "2 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 60,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1134101",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "30 Jan 2026",
      "first_updated": "4 Jan 2026",
      "stmt_date": "8 Feb 2026",
      "report_sent": "9 Feb 2026",
      "days_creation_to_update": -26,
      "days_stmt_to_report": 1,
      "invoice": 225,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1133201",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoice Paid",
      "created": "23 Jan 2026",
      "first_updated": "27 Jan 2026",
      "stmt_date": "11 Feb 2026",
      "report_sent": "16 Feb 2026",
      "days_creation_to_update": 4,
      "days_stmt_to_report": 5,
      "invoice": 720,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1117701",
      "client_ref": null,
      "type": "Large Loss",
      "status": "Invoiced",
      "created": "14 Jan 2026",
      "first_updated": "5 Nov 2025",
      "stmt_date": "20 Nov 2025",
      "report_sent": "28 Nov 2025",
      "days_creation_to_update": -70,
      "days_stmt_to_report": 8,
      "invoice": 862.88,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1131601",
      "client_ref": null,
      "type": "Motor Liability",
      "status": "Invoice Paid",
      "created": "14 Jan 2026",
      "first_updated": "14 Jan 2026",
      "stmt_date": "13 Feb 2026",
      "report_sent": "13 Feb 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 0,
      "invoice": 285,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1131401",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoice Paid",
      "created": "13 Jan 2026",
      "first_updated": "13 Jan 2026",
      "stmt_date": "22 Jan 2026",
      "report_sent": "29 Jan 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 7,
      "invoice": 825,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1131001",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "13 Jan 2026",
      "first_updated": "26 Dec 2025",
      "stmt_date": "28 Jan 2026",
      "report_sent": "4 Feb 2026",
      "days_creation_to_update": -18,
      "days_stmt_to_report": 7,
      "invoice": 800,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1130601",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoice Paid",
      "created": "12 Jan 2026",
      "first_updated": "12 Jan 2026",
      "stmt_date": "15 Jan 2026",
      "report_sent": "22 Jan 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 7,
      "invoice": 520,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1130501",
      "client_ref": null,
      "type": "Household fraud claim",
      "status": "Invoice Paid",
      "created": "12 Jan 2026",
      "first_updated": "12 Jan 2026",
      "stmt_date": "19 Jan 2026",
      "report_sent": "6 Feb 2025",
      "days_creation_to_update": 0,
      "days_stmt_to_report": -347,
      "invoice": 460,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    }
  ]
};
