// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  Trinity
// File:    trinity.js
// Period:  Jan–Dec 2026
// Updated: 2 Jul 2026
// GENERATED AUTOMATICALLY — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {

  client_name:                  "Trinity",
  report_period:                "Jan–Dec 2026",
  last_updated:                 "2 Jul 2026",
  is_rtc_client:                false,
  total_cases:                  51,

  avg_days_creation_to_update:         4.9,
  avg_days_creation_to_update_general: 4.9,
  avg_days_stmt_to_report:             5.8,
  avg_days_stmt_to_report_rtc:         0,
  avg_days_stmt_to_report_general:     5.8,

  sla_ack_pct:                  100,
  sla_contact_pct:              100,
  sla_update_pct:               82,
  sla_report_general_pct:       42,
  sla_report_rtc_pct:           null,
  has_rtc_cases:                false,
  has_general_cases:            true,
  sla_compliance_pct:           82,
  sla_met:                      15,
  sla_not_met:                  21,

  avg_fee_rtc:                  0,
  avg_fee_general:              491.09,
  total_fees_rtc:               0,
  total_fees_general:           25045.68,
  rtc_case_count:               0,
  general_case_count:           51,
  fees_by_type: [
    { type:"Motor Fraud", is_rtc:false, case_count:18, total_fees:10042.8, avg_fee:557.93 },
    { type:"Household fraud claim", is_rtc:false, case_count:15, total_fees:6534, avg_fee:435.6 },
    { type:"Surveillance", is_rtc:false, case_count:2, total_fees:3840, avg_fee:1920 },
    { type:"Motor Liability", is_rtc:false, case_count:10, total_fees:3012, avg_fee:301.2 },
    { type:"Large Loss", is_rtc:false, case_count:3, total_fees:1376.88, avg_fee:458.96 },
    { type:"Intelligence Report", is_rtc:false, case_count:2, total_fees:240, avg_fee:120 },
    { type:"Public Liability", is_rtc:false, case_count:1, total_fees:0, avg_fee:0 }
  ],

  // Line-item-driven revenue (from TrackOps invoice details export)
  total_invoiced_lineitems:     21740.18,
  total_lineitem_count:         80,
  fees_by_item: [
    { item:"Stage 1 Investigation", is_rtc:false, count:28, total:13200, avg:471.43 },
    { item:"Motor Liability Investigation", is_rtc:false, count:13, total:2950, avg:226.92 },
    { item:"Stage 2 Investigation", is_rtc:false, count:6, total:1250, avg:208.33 },
    { item:"Cold Calls", is_rtc:false, count:8, total:720, avg:90 },
    { item:"Miscellanoeus", is_rtc:false, count:8, total:720, avg:90 },
    { item:"Interpreter (full day)", is_rtc:false, count:2, total:600, avg:300 },
    { item:"Interpreter (1/2 day)", is_rtc:false, count:3, total:555, avg:185 },
    { item:"Police Report", is_rtc:false, count:3, total:551.18, avg:183.73 },
    { item:"Motor Theft Investigation", is_rtc:false, count:1, total:400, avg:400 },
    { item:"Intelligence Report Only", is_rtc:false, count:3, total:320, avg:106.67 },
    { item:"Translation services", is_rtc:false, count:2, total:294, avg:147 },
    { item:"Locus Report", is_rtc:false, count:1, total:100, avg:100 },
    { item:"Failed Appointment", is_rtc:false, count:2, total:80, avg:40 }
  ],

  monthly: [
    { month:"Jan", month_num:1, case_count:8, case_count_rtc:0, case_count_general:8, total_fees:5564.88, ave_fees:695.61, total_fees_rtc:0, total_fees_general:5564.88, ave_days_creation_to_update:0.8, ave_days_creation_to_update_general:0.8, ave_days_stmt_to_report:5, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:5, sla_ack_pct:100, sla_ack_met:8, sla_ack_n:8, sla_contact_pct:100, sla_contact_met:8, sla_contact_n:8, sla_update_pct:100, sla_update_met:5, sla_update_n:5, sla_report_general_pct:38, sla_report_general_met:3, sla_report_general_n:8, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:83, sla_met:3, sla_not_met:5 },
    { month:"Feb", month_num:2, case_count:13, case_count_rtc:0, case_count_general:13, total_fees:8706, ave_fees:669.69, total_fees_rtc:0, total_fees_general:8706, ave_days_creation_to_update:7.6, ave_days_creation_to_update_general:7.6, ave_days_stmt_to_report:5.3, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:5.3, sla_ack_pct:100, sla_ack_met:11, sla_ack_n:11, sla_contact_pct:100, sla_contact_met:11, sla_contact_n:11, sla_update_pct:78, sla_update_met:7, sla_update_n:9, sla_report_general_pct:56, sla_report_general_met:5, sla_report_general_n:9, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:85, sla_met:5, sla_not_met:4 },
    { month:"Mar", month_num:3, case_count:14, case_count_rtc:0, case_count_general:14, total_fees:5590.8, ave_fees:399.34, total_fees_rtc:0, total_fees_general:5590.8, ave_days_creation_to_update:4, ave_days_creation_to_update_general:4, ave_days_stmt_to_report:9.3, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:9.3, sla_ack_pct:100, sla_ack_met:9, sla_ack_n:9, sla_contact_pct:100, sla_contact_met:9, sla_contact_n:9, sla_update_pct:88, sla_update_met:7, sla_update_n:8, sla_report_general_pct:25, sla_report_general_met:2, sla_report_general_n:8, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:79, sla_met:2, sla_not_met:6 },
    { month:"Apr", month_num:4, case_count:7, case_count_rtc:0, case_count_general:7, total_fees:2808, ave_fees:401.14, total_fees_rtc:0, total_fees_general:2808, ave_days_creation_to_update:8.7, ave_days_creation_to_update_general:8.7, ave_days_stmt_to_report:3.7, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:3.7, sla_ack_pct:100, sla_ack_met:6, sla_ack_n:6, sla_contact_pct:100, sla_contact_met:6, sla_contact_n:6, sla_update_pct:50, sla_update_met:3, sla_update_n:6, sla_report_general_pct:67, sla_report_general_met:4, sla_report_general_n:6, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:79, sla_met:4, sla_not_met:2 },
    { month:"May", month_num:5, case_count:4, case_count_rtc:0, case_count_general:4, total_fees:1632, ave_fees:408, total_fees_rtc:0, total_fees_general:1632, ave_days_creation_to_update:0.7, ave_days_creation_to_update_general:0.7, ave_days_stmt_to_report:6.7, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:6.7, sla_ack_pct:100, sla_ack_met:4, sla_ack_n:4, sla_contact_pct:100, sla_contact_met:4, sla_contact_n:4, sla_update_pct:100, sla_update_met:3, sla_update_n:3, sla_report_general_pct:0, sla_report_general_met:0, sla_report_general_n:3, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:79, sla_met:0, sla_not_met:3 },
    { month:"Jun", month_num:6, case_count:5, case_count_rtc:0, case_count_general:5, total_fees:744, ave_fees:148.8, total_fees_rtc:0, total_fees_general:744, ave_days_creation_to_update:1.5, ave_days_creation_to_update_general:1.5, ave_days_stmt_to_report:3.5, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:3.5, sla_ack_pct:100, sla_ack_met:2, sla_ack_n:2, sla_contact_pct:100, sla_contact_met:2, sla_contact_n:2, sla_update_pct:100, sla_update_met:2, sla_update_n:2, sla_report_general_pct:50, sla_report_general_met:1, sla_report_general_n:2, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:88, sla_met:1, sla_not_met:1 },
    { month:"Jul", month_num:7, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Aug", month_num:8, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Sep", month_num:9, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Oct", month_num:10, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Nov", month_num:11, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Dec", month_num:12, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 }
  ],

  cases: [
    { ref:"1117701", client_ref:"TPEH00443059", type:"Large Loss", status:"Invoiced", created:"14 Jan 2026", first_updated:"5 Nov 2025", stmt_date:"20 Nov 2025", report_sent:"28 Nov 2025", days_creation_to_update:null, days_stmt_to_report:8, invoice:962.88, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1130501", client_ref:"TPEH00450990", type:"Household fraud claim", status:"Invoice Paid", created:"12 Jan 2026", first_updated:"12 Jan 2026", stmt_date:"19 Jan 2026", report_sent:"6 Feb 2025", days_creation_to_update:0, days_stmt_to_report:null, invoice:552, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:true, sla_report_target_days:3 },
    { ref:"1130601", client_ref:"TPEH00453503", type:"Household fraud claim", status:"Invoice Paid", created:"12 Jan 2026", first_updated:"12 Jan 2026", stmt_date:"15 Jan 2026", report_sent:"22 Jan 2026", days_creation_to_update:0, days_stmt_to_report:7, invoice:624, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1131001", client_ref:"B00015610", type:"Motor Fraud", status:"Invoice Paid", created:"13 Jan 2026", first_updated:"26 Dec 2025", stmt_date:"28 Jan 2026", report_sent:"4 Feb 2026", days_creation_to_update:null, days_stmt_to_report:7, invoice:960, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1131401", client_ref:"TPEH00456418", type:"Household fraud claim", status:"Invoice Paid", created:"13 Jan 2026", first_updated:"13 Jan 2026", stmt_date:"22 Jan 2026", report_sent:"29 Jan 2026", days_creation_to_update:0, days_stmt_to_report:7, invoice:990, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1131601", client_ref:"B00016381", type:"Motor Liability", status:"Enquiries ongoing", created:"14 Jan 2026", first_updated:"14 Jan 2026", stmt_date:"13 Feb 2026", report_sent:"13 Feb 2026", days_creation_to_update:0, days_stmt_to_report:0, invoice:342, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1133201", client_ref:"TPEH00447286", type:"Household fraud claim", status:"Invoice Paid", created:"23 Jan 2026", first_updated:"27 Jan 2026", stmt_date:"11 Feb 2026", report_sent:"16 Feb 2026", days_creation_to_update:4, days_stmt_to_report:5, invoice:864, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1134101", client_ref:"B00016308", type:"Motor Liability", status:"Invoice Paid", created:"30 Jan 2026", first_updated:"4 Jan 2026", stmt_date:"8 Feb 2026", report_sent:"9 Feb 2026", days_creation_to_update:null, days_stmt_to_report:1, invoice:270, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1134402", client_ref:"B00013862", type:"Motor Fraud", status:"Invoice Paid", created:"2 Feb 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:72, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1134902", client_ref:"", type:"Public Liability", status:"Invoice Paid", created:"3 Feb 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1135902", client_ref:"TPEH00433544", type:"Household fraud claim", status:"Invoice Paid", created:"6 Feb 2026", first_updated:"6 Feb 2026", stmt_date:"26 Feb 2026", report_sent:"4 Mar 2026", days_creation_to_update:0, days_stmt_to_report:6, invoice:552, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1136302", client_ref:"B00016706", type:"Motor Liability", status:"Invoice Paid", created:"9 Feb 2026", first_updated:"9 Feb 2026", stmt_date:"16 Feb 2026", report_sent:"18 Feb 2026", days_creation_to_update:0, days_stmt_to_report:2, invoice:270, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1137102", client_ref:"STM300104300", type:"Surveillance", status:"Invoiced", created:"11 Feb 2026", first_updated:"", stmt_date:"", report_sent:"13 Mar 2026", days_creation_to_update:null, days_stmt_to_report:null, invoice:3840, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1137702", client_ref:"B00016246", type:"Motor Liability", status:"Invoice Paid", created:"12 Feb 2026", first_updated:"17 Feb 2026", stmt_date:"24 Feb 2026", report_sent:"26 Feb 2026", days_creation_to_update:5, days_stmt_to_report:2, invoice:480, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1137802", client_ref:"TPEH00461277", type:"Household fraud claim", status:"Invoice Paid", created:"13 Feb 2026", first_updated:"18 Mar 2026", stmt_date:"", report_sent:"", days_creation_to_update:33, days_stmt_to_report:null, invoice:288, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1138302", client_ref:"B00017544", type:"Motor Fraud", status:"Invoice Paid", created:"16 Feb 2026", first_updated:"17 Feb 2026", stmt_date:"26 Feb 2026", report_sent:"4 Mar 2026", days_creation_to_update:1, days_stmt_to_report:6, invoice:744, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1138602", client_ref:"B00015075", type:"Motor Liability", status:"Invoice Paid", created:"17 Feb 2026", first_updated:"19 Feb 2026", stmt_date:"9 Mar 2026", report_sent:"9 Mar 2026", days_creation_to_update:2, days_stmt_to_report:0, invoice:300, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1139302", client_ref:"B00016094", type:"Motor Fraud", status:"Invoice Paid", created:"18 Feb 2026", first_updated:"17 Mar 2026", stmt_date:"2 Apr 2026", report_sent:"2 Apr 2026", days_creation_to_update:27, days_stmt_to_report:0, invoice:408, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1140002", client_ref:"STM400100702", type:"Motor Fraud", status:"Invoice Paid", created:"19 Feb 2026", first_updated:"19 Feb 2026", stmt_date:"23 Feb 2026", report_sent:"24 Feb 2026", days_creation_to_update:0, days_stmt_to_report:1, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1140102", client_ref:"TPEH00455169", type:"Household fraud claim", status:"Invoice Paid", created:"19 Feb 2026", first_updated:"19 Feb 2026", stmt_date:"26 Feb 2026", report_sent:"10 Mar 2026", days_creation_to_update:0, days_stmt_to_report:12, invoice:552, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1141102", client_ref:"B00017869", type:"Motor Fraud", status:"Invoice Paid", created:"25 Feb 2026", first_updated:"27 Jan 2026", stmt_date:"28 Feb 2026", report_sent:"19 Mar 2026", days_creation_to_update:null, days_stmt_to_report:19, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1142803", client_ref:"TPEH00460922", type:"Household fraud claim", status:"Invoice Paid", created:"6 Mar 2026", first_updated:"6 Mar 2026", stmt_date:"13 Mar 2026", report_sent:"17 Mar 2026", days_creation_to_update:0, days_stmt_to_report:4, invoice:552, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1143303", client_ref:"TPEH00346845", type:"Household fraud claim", status:"Invoice Paid", created:"10 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1144303", client_ref:"STM300089429", type:"Large Loss", status:"Invoice Paid", created:"12 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:144, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1144603", client_ref:"B00019008", type:"Motor Fraud", status:"Invoice Paid", created:"12 Mar 2026", first_updated:"12 Mar 2026", stmt_date:"17 Mar 2026", report_sent:"31 Mar 2026", days_creation_to_update:0, days_stmt_to_report:14, invoice:840, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1144903", client_ref:"TPEH00458551", type:"Household fraud claim", status:"Invoice Paid", created:"12 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:144, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1145103", client_ref:"B00019307", type:"Motor Fraud", status:"Invoice Paid", created:"13 Mar 2026", first_updated:"13 Mar 2026", stmt_date:"", report_sent:"", days_creation_to_update:0, days_stmt_to_report:null, invoice:808.8, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1145303", client_ref:"STM300071599", type:"Intelligence Report", status:"Invoice Paid", created:"16 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:96, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1145503", client_ref:"A00013199", type:"Motor Fraud", status:"Invoice Paid", created:"17 Mar 2026", first_updated:"17 Mar 2026", stmt_date:"23 Apr 2026", report_sent:"13 May 2026", days_creation_to_update:0, days_stmt_to_report:20, invoice:822, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1145603", client_ref:"STM200035976", type:"Surveillance", status:"Invoice Paid", created:"17 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1146503", client_ref:"STM300103623", type:"Motor Fraud", status:"Invoice Paid", created:"23 Mar 2026", first_updated:"23 Mar 2026", stmt_date:"26 Mar 2026", report_sent:"2 Apr 2026", days_creation_to_update:0, days_stmt_to_report:7, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1146603", client_ref:"TPEH00464746", type:"Household fraud claim", status:"Invoice Paid", created:"23 Mar 2026", first_updated:"23 Mar 2026", stmt_date:"13 Apr 2026", report_sent:"16 Apr 2026", days_creation_to_update:0, days_stmt_to_report:3, invoice:552, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1147603", client_ref:"B00019244", type:"Motor Fraud", status:"Invoice Paid", created:"25 Mar 2026", first_updated:"25 Apr 2026", stmt_date:"13 Apr 2026", report_sent:"29 Apr 2026", days_creation_to_update:31, days_stmt_to_report:16, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1147703", client_ref:"B00020728", type:"Motor Liability", status:"Invoice Paid", created:"25 Mar 2026", first_updated:"24 Mar 2026", stmt_date:"", report_sent:"1 Apr 2026", days_creation_to_update:null, days_stmt_to_report:null, invoice:120, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:true, sla_report_target_days:3 },
    { ref:"1147903", client_ref:"TPEH00463048", type:"Household fraud claim", status:"Invoice Paid", created:"25 Mar 2026", first_updated:"26 Mar 2026", stmt_date:"18 May 2026", report_sent:"19 May 2026", days_creation_to_update:1, days_stmt_to_report:1, invoice:312, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1149404", client_ref:"B00020569", type:"Motor Liability", status:"Invoice Paid", created:"1 Apr 2026", first_updated:"9 Apr 2026", stmt_date:"25 Apr 2026", report_sent:"1 May 2026", days_creation_to_update:8, days_stmt_to_report:6, invoice:318, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1151304", client_ref:"B00021618", type:"Large Loss", status:"Invoice Paid", created:"7 Apr 2026", first_updated:"7 Apr 2026", stmt_date:"14 Apr 2026", report_sent:"17 Apr 2026", days_creation_to_update:0, days_stmt_to_report:3, invoice:270, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1152904", client_ref:"B00020257", type:"Motor Liability", status:"Invoice Paid", created:"8 Apr 2026", first_updated:"10 Apr 2026", stmt_date:"20 Apr 2026", report_sent:"22 Apr 2026", days_creation_to_update:2, days_stmt_to_report:2, invoice:270, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1154204", client_ref:"B00020709", type:"Motor Liability", status:"Invoice Paid", created:"10 Apr 2026", first_updated:"10 Apr 2026", stmt_date:"21 Apr 2026", report_sent:"23 Apr 2026", days_creation_to_update:0, days_stmt_to_report:2, invoice:342, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1156404", client_ref:"B00020933", type:"Motor Fraud", status:"Invoiced", created:"16 Apr 2026", first_updated:"22 Apr 2026", stmt_date:"26 May 2026", report_sent:"3 Jun 2026", days_creation_to_update:6, days_stmt_to_report:8, invoice:1398, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1156904", client_ref:"STM300105544", type:"Motor Fraud", status:"Invoiced", created:"16 Apr 2026", first_updated:"22 May 2026", stmt_date:"29 Jun 2026", report_sent:"30 Jun 2026", days_creation_to_update:36, days_stmt_to_report:1, invoice:210, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1157404", client_ref:"B00021629", type:"Motor Fraud", status:"Enquiries ongoing", created:"17 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1161805", client_ref:"B00022617", type:"Motor Liability", status:"Invoiced", created:"7 May 2026", first_updated:"8 May 2026", stmt_date:"20 May 2026", report_sent:"26 May 2026", days_creation_to_update:1, days_stmt_to_report:6, invoice:300, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1162405", client_ref:"TPEH00454378", type:"Household fraud claim", status:"Interview date / time TBC", created:"11 May 2026", first_updated:"11 May 2026", stmt_date:"", report_sent:"", days_creation_to_update:0, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1163205", client_ref:"B00022512", type:"Motor Fraud", status:"Invoiced", created:"12 May 2026", first_updated:"18 Apr 2026", stmt_date:"27 May 2026", report_sent:"1 Jun 2026", days_creation_to_update:null, days_stmt_to_report:5, invoice:780, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1165505", client_ref:"TPEH00467039", type:"Household fraud claim", status:"Invoice Paid", created:"20 May 2026", first_updated:"21 May 2026", stmt_date:"1 Jun 2026", report_sent:"10 Jun 2026", days_creation_to_update:1, days_stmt_to_report:9, invoice:552, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1168306", client_ref:"STM300101288", type:"Motor Fraud", status:"Awaiting further advises", created:"1 Jun 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1168406", client_ref:"TPEH00476081", type:"Household fraud claim", status:"Reviewed, signed off & sent", created:"1 Jun 2026", first_updated:"1 Jun 2026", stmt_date:"3 Jun 2026", report_sent:"8 Jun 2026", days_creation_to_update:0, days_stmt_to_report:5, invoice:0, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1170306", client_ref:"B00024854", type:"Motor Fraud", status:"Appointment made", created:"5 Jun 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1171806", client_ref:"B00025446", type:"Motor Fraud", status:"Invoiced", created:"12 Jun 2026", first_updated:"15 Jun 2026", stmt_date:"22 Jun 2026", report_sent:"24 Jun 2026", days_creation_to_update:3, days_stmt_to_report:2, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1175006", client_ref:"TPEH00448088", type:"Intelligence Report", status:"Invoiced", created:"26 Jun 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:144, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 }
  ]

};
