// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  Trinity
// File:    trinity.js
// Period:  Jan–Dec 2026
// Updated: 11 May 2026
// GENERATED AUTOMATICALLY — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {

  client_name:                  "Trinity",
  report_period:                "Jan–Dec 2026",
  last_updated:                 "11 May 2026",
  is_rtc_client:                false,
  total_cases:                  42,

  avg_days_creation_to_update:         4.5,
  avg_days_creation_to_update_general: 4.5,
  avg_days_stmt_to_report:             5.6,
  avg_days_stmt_to_report_rtc:         0,
  avg_days_stmt_to_report_general:     5.6,

  sla_ack_pct:                  100,
  sla_contact_pct:              100,
  sla_update_pct:               84,
  sla_report_general_pct:       44,
  sla_report_rtc_pct:           null,
  has_rtc_cases:                false,
  has_general_cases:            true,
  sla_compliance_pct:           83,
  sla_met:                      12,
  sla_not_met:                  15,

  avg_fee_rtc:                  0,
  avg_fee_general:              368.75,
  total_fees_rtc:               0,
  total_fees_general:           15487.68,
  rtc_case_count:               0,
  general_case_count:           42,
  fees_by_type: [
    { type:"Motor Fraud", is_rtc:false, case_count:14, total_fees:6232.8, avg_fee:445.2 },
    { type:"Household fraud claim", is_rtc:false, case_count:12, total_fees:5670, avg_fee:472.5 },
    { type:"Motor Liability", is_rtc:false, case_count:9, total_fees:2712, avg_fee:301.33 },
    { type:"Large Loss", is_rtc:false, case_count:3, total_fees:776.88, avg_fee:258.96 },
    { type:"Intelligence Report", is_rtc:false, case_count:1, total_fees:96, avg_fee:96 },
    { type:"Surveillance", is_rtc:false, case_count:2, total_fees:0, avg_fee:0 },
    { type:"Public Liability", is_rtc:false, case_count:1, total_fees:0, avg_fee:0 }
  ],

  monthly: [
    { month:"Jan", month_num:1, case_count:8, case_count_rtc:0, case_count_general:8, total_fees:4964.88, ave_fees:620.61, total_fees_rtc:0, total_fees_general:4964.88, ave_days_creation_to_update:0.8, ave_days_creation_to_update_general:0.8, ave_days_stmt_to_report:5, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:5, sla_ack_pct:100, sla_ack_met:8, sla_ack_n:8, sla_contact_pct:100, sla_contact_met:8, sla_contact_n:8, sla_update_pct:100, sla_update_met:5, sla_update_n:5, sla_report_general_pct:38, sla_report_general_met:3, sla_report_general_n:8, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:83, sla_met:3, sla_not_met:5 },
    { month:"Feb", month_num:2, case_count:13, case_count_rtc:0, case_count_general:13, total_fees:4866, ave_fees:374.31, total_fees_rtc:0, total_fees_general:4866, ave_days_creation_to_update:7.6, ave_days_creation_to_update_general:7.6, ave_days_stmt_to_report:5.3, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:5.3, sla_ack_pct:100, sla_ack_met:11, sla_ack_n:11, sla_contact_pct:100, sla_contact_met:11, sla_contact_n:11, sla_update_pct:78, sla_update_met:7, sla_update_n:9, sla_report_general_pct:56, sla_report_general_met:5, sla_report_general_n:9, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:85, sla_met:5, sla_not_met:4 },
    { month:"Mar", month_num:3, case_count:14, case_count_rtc:0, case_count_general:14, total_fees:4456.8, ave_fees:318.34, total_fees_rtc:0, total_fees_general:4456.8, ave_days_creation_to_update:4.4, ave_days_creation_to_update_general:4.4, ave_days_stmt_to_report:8.8, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:8.8, sla_ack_pct:100, sla_ack_met:8, sla_ack_n:8, sla_contact_pct:100, sla_contact_met:8, sla_contact_n:8, sla_update_pct:86, sla_update_met:6, sla_update_n:7, sla_report_general_pct:17, sla_report_general_met:1, sla_report_general_n:6, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:79, sla_met:1, sla_not_met:5 },
    { month:"Apr", month_num:4, case_count:7, case_count_rtc:0, case_count_general:7, total_fees:1200, ave_fees:171.43, total_fees_rtc:0, total_fees_general:1200, ave_days_creation_to_update:2.5, ave_days_creation_to_update_general:2.5, ave_days_stmt_to_report:3.3, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:3.3, sla_ack_pct:100, sla_ack_met:4, sla_ack_n:4, sla_contact_pct:100, sla_contact_met:4, sla_contact_n:4, sla_update_pct:75, sla_update_met:3, sla_update_n:4, sla_report_general_pct:75, sla_report_general_met:3, sla_report_general_n:4, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:88, sla_met:3, sla_not_met:1 },
    { month:"May", month_num:5, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Jun", month_num:6, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Jul", month_num:7, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Aug", month_num:8, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Sep", month_num:9, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Oct", month_num:10, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Nov", month_num:11, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Dec", month_num:12, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 }
  ],

  cases: [
    { ref:"1117701", client_ref:"TPEH00443059", type:"Large Loss", status:"Other statement obtained", created:"14 Jan 2026", first_updated:"5 Nov 2025", stmt_date:"20 Nov 2025", report_sent:"28 Nov 2025", days_creation_to_update:null, days_stmt_to_report:8, invoice:362.88, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1130501", client_ref:"TPEH00450990", type:"Household fraud claim", status:"Invoice Paid", created:"12 Jan 2026", first_updated:"12 Jan 2026", stmt_date:"19 Jan 2026", report_sent:"6 Feb 2025", days_creation_to_update:0, days_stmt_to_report:null, invoice:552, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:true, sla_report_target_days:3 },
    { ref:"1130601", client_ref:"TPEH00453503", type:"Household fraud claim", status:"Invoice Paid", created:"12 Jan 2026", first_updated:"12 Jan 2026", stmt_date:"15 Jan 2026", report_sent:"22 Jan 2026", days_creation_to_update:0, days_stmt_to_report:7, invoice:624, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1131001", client_ref:"B00015610", type:"Motor Fraud", status:"Invoice Paid", created:"13 Jan 2026", first_updated:"26 Dec 2025", stmt_date:"28 Jan 2026", report_sent:"4 Feb 2026", days_creation_to_update:null, days_stmt_to_report:7, invoice:960, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1131401", client_ref:"TPEH00456418", type:"Household fraud claim", status:"Invoice Paid", created:"13 Jan 2026", first_updated:"13 Jan 2026", stmt_date:"22 Jan 2026", report_sent:"29 Jan 2026", days_creation_to_update:0, days_stmt_to_report:7, invoice:990, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1131601", client_ref:"B00016381", type:"Motor Liability", status:"Invoice Paid", created:"14 Jan 2026", first_updated:"14 Jan 2026", stmt_date:"13 Feb 2026", report_sent:"13 Feb 2026", days_creation_to_update:0, days_stmt_to_report:0, invoice:342, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1133201", client_ref:"TPEH00447286", type:"Household fraud claim", status:"Invoice Paid", created:"23 Jan 2026", first_updated:"27 Jan 2026", stmt_date:"11 Feb 2026", report_sent:"16 Feb 2026", days_creation_to_update:4, days_stmt_to_report:5, invoice:864, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1134101", client_ref:"B00016308", type:"Motor Liability", status:"Invoice Paid", created:"30 Jan 2026", first_updated:"4 Jan 2026", stmt_date:"8 Feb 2026", report_sent:"9 Feb 2026", days_creation_to_update:null, days_stmt_to_report:1, invoice:270, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1134402", client_ref:"B00013862", type:"Motor Fraud", status:"Invoice Paid", created:"2 Feb 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:72, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1134902", client_ref:"", type:"Public Liability", status:"Invoice Paid", created:"3 Feb 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1135902", client_ref:"TPEH00433544", type:"Household fraud claim", status:"Invoice Paid", created:"6 Feb 2026", first_updated:"6 Feb 2026", stmt_date:"26 Feb 2026", report_sent:"4 Mar 2026", days_creation_to_update:0, days_stmt_to_report:6, invoice:552, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1136302", client_ref:"B00016706", type:"Motor Liability", status:"Invoice Paid", created:"9 Feb 2026", first_updated:"9 Feb 2026", stmt_date:"16 Feb 2026", report_sent:"18 Feb 2026", days_creation_to_update:0, days_stmt_to_report:2, invoice:270, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1137102", client_ref:"STM300104300", type:"Surveillance", status:"Reviewed, signed off & sent", created:"11 Feb 2026", first_updated:"", stmt_date:"", report_sent:"13 Mar 2026", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1137702", client_ref:"B00016246", type:"Motor Liability", status:"Invoice Paid", created:"12 Feb 2026", first_updated:"17 Feb 2026", stmt_date:"24 Feb 2026", report_sent:"26 Feb 2026", days_creation_to_update:5, days_stmt_to_report:2, invoice:480, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1137802", client_ref:"TPEH00461277", type:"Household fraud claim", status:"Invoice Paid", created:"13 Feb 2026", first_updated:"18 Mar 2026", stmt_date:"", report_sent:"", days_creation_to_update:33, days_stmt_to_report:null, invoice:288, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1138302", client_ref:"B00017544", type:"Motor Fraud", status:"Invoice Paid", created:"16 Feb 2026", first_updated:"17 Feb 2026", stmt_date:"26 Feb 2026", report_sent:"4 Mar 2026", days_creation_to_update:1, days_stmt_to_report:6, invoice:744, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1138602", client_ref:"B00015075", type:"Motor Liability", status:"Invoice Paid", created:"17 Feb 2026", first_updated:"19 Feb 2026", stmt_date:"9 Mar 2026", report_sent:"9 Mar 2026", days_creation_to_update:2, days_stmt_to_report:0, invoice:300, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1139302", client_ref:"B00016094", type:"Motor Fraud", status:"Invoiced", created:"18 Feb 2026", first_updated:"17 Mar 2026", stmt_date:"2 Apr 2026", report_sent:"2 Apr 2026", days_creation_to_update:27, days_stmt_to_report:0, invoice:408, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1140002", client_ref:"STM400100702", type:"Motor Fraud", status:"Invoice Paid", created:"19 Feb 2026", first_updated:"19 Feb 2026", stmt_date:"23 Feb 2026", report_sent:"24 Feb 2026", days_creation_to_update:0, days_stmt_to_report:1, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1140102", client_ref:"TPEH00455169", type:"Household fraud claim", status:"Invoice Paid", created:"19 Feb 2026", first_updated:"19 Feb 2026", stmt_date:"26 Feb 2026", report_sent:"10 Mar 2026", days_creation_to_update:0, days_stmt_to_report:12, invoice:552, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1141102", client_ref:"B00017869", type:"Motor Fraud", status:"Invoiced", created:"25 Feb 2026", first_updated:"27 Jan 2026", stmt_date:"28 Feb 2026", report_sent:"19 Mar 2026", days_creation_to_update:null, days_stmt_to_report:19, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1142803", client_ref:"TPEH00460922", type:"Household fraud claim", status:"Invoice Paid", created:"6 Mar 2026", first_updated:"6 Mar 2026", stmt_date:"13 Mar 2026", report_sent:"17 Mar 2026", days_creation_to_update:0, days_stmt_to_report:4, invoice:552, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1143303", client_ref:"TPEH00346845", type:"Household fraud claim", status:"Invoice Paid", created:"10 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1144303", client_ref:"STM300089429", type:"Large Loss", status:"Invoiced", created:"12 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:144, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1144603", client_ref:"B00019008", type:"Motor Fraud", status:"Invoiced", created:"12 Mar 2026", first_updated:"12 Mar 2026", stmt_date:"17 Mar 2026", report_sent:"31 Mar 2026", days_creation_to_update:0, days_stmt_to_report:14, invoice:840, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1144903", client_ref:"TPEH00458551", type:"Household fraud claim", status:"Awaiting further advises", created:"12 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:144, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1145103", client_ref:"B00019307", type:"Motor Fraud", status:"Invoice Paid", created:"13 Mar 2026", first_updated:"13 Mar 2026", stmt_date:"", report_sent:"", days_creation_to_update:0, days_stmt_to_report:null, invoice:808.8, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1145303", client_ref:"STM300071599", type:"Intelligence Report", status:"Invoiced", created:"16 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:96, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1145503", client_ref:"A00013199", type:"Motor Fraud", status:"Documents Submitted", created:"17 Mar 2026", first_updated:"17 Mar 2026", stmt_date:"", report_sent:"", days_creation_to_update:0, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1145603", client_ref:"STM200035976", type:"Surveillance", status:"Invoice Paid", created:"17 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1146503", client_ref:"STM300103623", type:"Motor Fraud", status:"Invoice Paid", created:"23 Mar 2026", first_updated:"23 Mar 2026", stmt_date:"26 Mar 2026", report_sent:"2 Apr 2026", days_creation_to_update:0, days_stmt_to_report:7, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1146603", client_ref:"TPEH00464746", type:"Household fraud claim", status:"Invoice Paid", created:"23 Mar 2026", first_updated:"23 Mar 2026", stmt_date:"13 Apr 2026", report_sent:"16 Apr 2026", days_creation_to_update:0, days_stmt_to_report:3, invoice:552, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1147603", client_ref:"B00019244", type:"Motor Fraud", status:"Invoice Paid", created:"25 Mar 2026", first_updated:"25 Apr 2026", stmt_date:"13 Apr 2026", report_sent:"29 Apr 2026", days_creation_to_update:31, days_stmt_to_report:16, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1147703", client_ref:"B00020728", type:"Motor Liability", status:"Invoice Paid", created:"25 Mar 2026", first_updated:"24 Mar 2026", stmt_date:"", report_sent:"1 Apr 2026", days_creation_to_update:null, days_stmt_to_report:null, invoice:120, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:true, sla_report_target_days:3 },
    { ref:"1147903", client_ref:"TPEH00463048", type:"Household fraud claim", status:"Statement obtained", created:"25 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1149404", client_ref:"B00020569", type:"Motor Liability", status:"Invoiced", created:"1 Apr 2026", first_updated:"9 Apr 2026", stmt_date:"25 Apr 2026", report_sent:"1 May 2026", days_creation_to_update:8, days_stmt_to_report:6, invoice:318, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1151304", client_ref:"B00021618", type:"Large Loss", status:"Invoice Paid", created:"7 Apr 2026", first_updated:"7 Apr 2026", stmt_date:"14 Apr 2026", report_sent:"17 Apr 2026", days_creation_to_update:0, days_stmt_to_report:3, invoice:270, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1152904", client_ref:"B00020257", type:"Motor Liability", status:"Invoiced", created:"8 Apr 2026", first_updated:"10 Apr 2026", stmt_date:"20 Apr 2026", report_sent:"22 Apr 2026", days_creation_to_update:2, days_stmt_to_report:2, invoice:270, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1154204", client_ref:"B00020709", type:"Motor Liability", status:"Invoiced", created:"10 Apr 2026", first_updated:"10 Apr 2026", stmt_date:"21 Apr 2026", report_sent:"23 Apr 2026", days_creation_to_update:0, days_stmt_to_report:2, invoice:342, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1156404", client_ref:"B00020933", type:"Motor Fraud", status:"Appointment made", created:"16 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1156904", client_ref:"STM300105544", type:"Motor Fraud", status:"Await PH response / HUB done", created:"16 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1157404", client_ref:"B00021629", type:"Motor Fraud", status:"Enquiries ongoing", created:"17 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 }
  ]

};
