// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  Zego Insurance
// File:    zego.js
// Period:  Jan–Dec 2026
// Updated: 11 May 2026
// GENERATED AUTOMATICALLY — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {

  client_name:                  "Zego Insurance",
  report_period:                "Jan–Dec 2026",
  last_updated:                 "11 May 2026",
  is_rtc_client:                true,
  total_cases:                  58,

  avg_days_creation_to_update:         2.5,
  avg_days_creation_to_update_general: 3.2,
  avg_days_stmt_to_report:             4.5,
  avg_days_stmt_to_report_rtc:         1.7,
  avg_days_stmt_to_report_general:     8.6,

  sla_ack_pct:                  100,
  sla_contact_pct:              100,
  sla_update_pct:               82,
  sla_report_general_pct:       18,
  sla_report_rtc_pct:           86,
  has_rtc_cases:                true,
  has_general_cases:            true,
  sla_compliance_pct:           86,
  sla_met:                      21,
  sla_not_met:                  17,

  avg_fee_rtc:                  173.33,
  avg_fee_general:              557.6,
  total_fees_rtc:               6240,
  total_fees_general:           12267.12,
  rtc_case_count:               36,
  general_case_count:           22,
  fees_by_type: [
    { type:"Motor Fraud", is_rtc:false, case_count:15, total_fees:6672, avg_fee:444.8 },
    { type:"RTC", is_rtc:true, case_count:36, total_fees:6240, avg_fee:173.33 },
    { type:"Motor Theft", is_rtc:false, case_count:7, total_fees:5595.12, avg_fee:799.3 }
  ],

  monthly: [
    { month:"Jan", month_num:1, case_count:4, case_count_rtc:0, case_count_general:4, total_fees:4299.12, ave_fees:1074.78, total_fees_rtc:0, total_fees_general:4299.12, ave_days_creation_to_update:3.5, ave_days_creation_to_update_general:3.5, ave_days_stmt_to_report:6, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:6, sla_ack_pct:100, sla_ack_met:4, sla_ack_n:4, sla_contact_pct:100, sla_contact_met:4, sla_contact_n:4, sla_update_pct:75, sla_update_met:3, sla_update_n:4, sla_report_general_pct:25, sla_report_general_met:1, sla_report_general_n:4, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:75, sla_met:1, sla_not_met:3 },
    { month:"Feb", month_num:2, case_count:8, case_count_rtc:0, case_count_general:8, total_fees:2976, ave_fees:372, total_fees_rtc:0, total_fees_general:2976, ave_days_creation_to_update:4.3, ave_days_creation_to_update_general:4.3, ave_days_stmt_to_report:13, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:13, sla_ack_pct:100, sla_ack_met:6, sla_ack_n:6, sla_contact_pct:100, sla_contact_met:6, sla_contact_n:6, sla_update_pct:83, sla_update_met:5, sla_update_n:6, sla_report_general_pct:17, sla_report_general_met:1, sla_report_general_n:6, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:75, sla_met:1, sla_not_met:5 },
    { month:"Mar", month_num:3, case_count:7, case_count_rtc:1, case_count_general:6, total_fees:3144, ave_fees:449.14, total_fees_rtc:192, total_fees_general:2952, ave_days_creation_to_update:0.8, ave_days_creation_to_update_general:0.5, ave_days_stmt_to_report:5.2, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:6.5, sla_ack_pct:100, sla_ack_met:5, sla_ack_n:5, sla_contact_pct:100, sla_contact_met:5, sla_contact_n:5, sla_update_pct:100, sla_update_met:4, sla_update_n:4, sla_report_general_pct:25, sla_report_general_met:1, sla_report_general_n:4, sla_report_rtc_pct:100, sla_report_rtc_met:1, sla_report_rtc_n:1, sla_compliance_pct:84, sla_met:2, sla_not_met:3 },
    { month:"Apr", month_num:4, case_count:39, case_count_rtc:35, case_count_general:4, total_fees:8088, ave_fees:207.38, total_fees_rtc:6048, total_fees_general:2040, ave_days_creation_to_update:2.3, ave_days_creation_to_update_general:4.3, ave_days_stmt_to_report:2.9, ave_days_stmt_to_report_rtc:1.8, ave_days_stmt_to_report_general:10.3, sla_ack_pct:100, sla_ack_met:27, sla_ack_n:27, sla_contact_pct:100, sla_contact_met:27, sla_contact_n:27, sla_update_pct:67, sla_update_met:2, sla_update_n:3, sla_report_general_pct:0, sla_report_general_met:0, sla_report_general_n:3, sla_report_rtc_pct:85, sla_report_rtc_met:17, sla_report_rtc_n:20, sla_compliance_pct:91, sla_met:17, sla_not_met:6 },
    { month:"May", month_num:5, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Jun", month_num:6, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Jul", month_num:7, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Aug", month_num:8, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Sep", month_num:9, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Oct", month_num:10, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Nov", month_num:11, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 },
    { month:"Dec", month_num:12, case_count:0, case_count_rtc:0, case_count_general:0, total_fees:0, ave_fees:0, total_fees_rtc:0, total_fees_general:0, ave_days_creation_to_update:0, ave_days_creation_to_update_general:0, ave_days_stmt_to_report:0, ave_days_stmt_to_report_rtc:0, ave_days_stmt_to_report_general:0, sla_ack_pct:null, sla_ack_met:0, sla_ack_n:0, sla_contact_pct:null, sla_contact_met:0, sla_contact_n:0, sla_update_pct:null, sla_update_met:0, sla_update_n:0, sla_report_general_pct:null, sla_report_general_met:0, sla_report_general_n:0, sla_report_rtc_pct:null, sla_report_rtc_met:0, sla_report_rtc_n:0, sla_compliance_pct:0, sla_met:0, sla_not_met:0 }
  ],

  cases: [
    { ref:"1129201", client_ref:"25.732470-1", type:"Motor Theft", status:"Invoice Paid", created:"5 Jan 2026", first_updated:"6 Jan 2026", stmt_date:"14 Jan 2026", report_sent:"19 Jan 2026", days_creation_to_update:1, days_stmt_to_report:5, invoice:1374.42, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1130001", client_ref:"25.817981-1", type:"Motor Theft", status:"Invoice Paid", created:"8 Jan 2026", first_updated:"9 Jan 2026", stmt_date:"15 Jan 2026", report_sent:"22 Jan 2026", days_creation_to_update:1, days_stmt_to_report:7, invoice:1292.7, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1131101", client_ref:"25.813951-2", type:"Motor Fraud", status:"Invoice Paid", created:"13 Jan 2026", first_updated:"14 Jan 2026", stmt_date:"20 Jan 2026", report_sent:"29 Jan 2026", days_creation_to_update:1, days_stmt_to_report:9, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1133501", client_ref:"26.822805-1", type:"Motor Fraud", status:"Invoiced", created:"26 Jan 2026", first_updated:"6 Feb 2026", stmt_date:"17 Mar 2026", report_sent:"20 Mar 2026", days_creation_to_update:11, days_stmt_to_report:3, invoice:1032, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1135602", client_ref:"26.837204-2", type:"Motor Fraud", status:"Invoice Paid", created:"5 Feb 2026", first_updated:"6 Feb 2026", stmt_date:"", report_sent:"16 Mar 2026", days_creation_to_update:1, days_stmt_to_report:null, invoice:144, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:true, sla_report_target_days:3 },
    { ref:"1135802", client_ref:"26.829455-1", type:"Motor Theft", status:"Invoiced", created:"6 Feb 2026", first_updated:"10 Feb 2026", stmt_date:"14 Mar 2026", report_sent:"8 Apr 2026", days_creation_to_update:4, days_stmt_to_report:25, invoice:1104, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1136102", client_ref:"25.805841-1", type:"Motor Fraud", status:"Invoiced", created:"6 Feb 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:72, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1136502", client_ref:"25.785615-1", type:"Motor Fraud", status:"On Hold", created:"9 Feb 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1136902", client_ref:"25.773372-1", type:"Motor Fraud", status:"Invoice Paid", created:"10 Feb 2026", first_updated:"25 Feb 2026", stmt_date:"3 Mar 2026", report_sent:"5 Mar 2026", days_creation_to_update:15, days_stmt_to_report:2, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1137902", client_ref:"26.830280-2", type:"Motor Fraud", status:"Invoice Paid", created:"13 Feb 2026", first_updated:"14 Feb 2026", stmt_date:"", report_sent:"6 Mar 2026", days_creation_to_update:1, days_stmt_to_report:null, invoice:360, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:true, sla_report_target_days:3 },
    { ref:"1140602", client_ref:"26.840666-2", type:"Motor Fraud", status:"Invoice Paid", created:"23 Feb 2026", first_updated:"25 Feb 2026", stmt_date:"", report_sent:"6 Mar 2026", days_creation_to_update:2, days_stmt_to_report:null, invoice:72, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:true, sla_report_target_days:3 },
    { ref:"1141402", client_ref:"26.835330-1", type:"Motor Theft", status:"Invoice Paid", created:"27 Feb 2026", first_updated:"2 Mar 2026", stmt_date:"12 Mar 2026", report_sent:"24 Mar 2026", days_creation_to_update:3, days_stmt_to_report:12, invoice:624, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1143503", client_ref:"26.848789-1", type:"Motor Fraud", status:"Invoice Paid", created:"10 Mar 2026", first_updated:"11 Mar 2026", stmt_date:"1 Apr 2026", report_sent:"1 Apr 2026", days_creation_to_update:1, days_stmt_to_report:0, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:true, report_proxy:false, sla_report_target_days:3 },
    { ref:"1144003", client_ref:"26.836619-2", type:"Motor Fraud", status:"Invoiced", created:"11 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:72, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1144503", client_ref:"26.850533-1", type:"Motor Theft", status:"Closed", created:"12 Mar 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1144703", client_ref:"26.822780-2", type:"Motor Fraud", status:"Invoiced", created:"12 Mar 2026", first_updated:"13 Mar 2026", stmt_date:"17 Mar 2026", report_sent:"25 Mar 2026", days_creation_to_update:1, days_stmt_to_report:8, invoice:960, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1145203", client_ref:"26.851350-2", type:"Motor Fraud", status:"Invoice Paid", created:"13 Mar 2026", first_updated:"13 Mar 2026", stmt_date:"19 Mar 2026", report_sent:"27 Mar 2026", days_creation_to_update:0, days_stmt_to_report:8, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1146003", client_ref:"26.844372-1", type:"Motor Theft", status:"Invoice Paid", created:"19 Mar 2026", first_updated:"19 Mar 2026", stmt_date:"23 Mar 2026", report_sent:"2 Apr 2026", days_creation_to_update:0, days_stmt_to_report:10, invoice:720, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1149103", client_ref:"26.863087-1", type:"RTC", status:"Invoice Paid", created:"31 Mar 2026", first_updated:"2 Apr 2026", stmt_date:"3 Apr 2026", report_sent:"3 Apr 2026", days_creation_to_update:2, days_stmt_to_report:0, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1150004", client_ref:"26.861759-1", type:"RTC", status:"Invoice Paid", created:"1 Apr 2026", first_updated:"2 Apr 2026", stmt_date:"16 Apr 2026", report_sent:"21 Apr 2026", days_creation_to_update:1, days_stmt_to_report:5, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:2 },
    { ref:"1150104", client_ref:"26.861604-1", type:"Motor Theft", status:"Invoiced", created:"1 Apr 2026", first_updated:"2 Apr 2026", stmt_date:"7 Apr 2026", report_sent:"24 Apr 2026", days_creation_to_update:1, days_stmt_to_report:17, invoice:672, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:2 },
    { ref:"1150204", client_ref:"26.864053-1", type:"Motor Theft", status:"Enquiries ongoing", created:"2 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:192, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1150304", client_ref:"26.826424-1", type:"Motor Fraud", status:"Invoiced", created:"2 Apr 2026", first_updated:"7 Apr 2026", stmt_date:"13 Apr 2026", report_sent:"28 Apr 2026", days_creation_to_update:5, days_stmt_to_report:15, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1152204", client_ref:"26.866609-1", type:"RTC", status:"Invoiced", created:"8 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:192, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1152304", client_ref:"26.864509-1", type:"RTC", status:"Invoice Paid", created:"8 Apr 2026", first_updated:"13 Apr 2026", stmt_date:"13 Apr 2026", report_sent:"13 Apr 2026", days_creation_to_update:5, days_stmt_to_report:0, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1152404", client_ref:"26.868710-1", type:"RTC", status:"Invoice Paid", created:"8 Apr 2026", first_updated:"13 Apr 2026", stmt_date:"16 Apr 2026", report_sent:"17 Apr 2026", days_creation_to_update:5, days_stmt_to_report:1, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1152504", client_ref:"26.868748-1", type:"RTC", status:"Invoice Paid", created:"8 Apr 2026", first_updated:"14 Apr 2026", stmt_date:"28 Apr 2026", report_sent:"29 Apr 2026", days_creation_to_update:6, days_stmt_to_report:1, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1152604", client_ref:"26.867909-1", type:"RTC", status:"Invoice Paid", created:"8 Apr 2026", first_updated:"16 Apr 2026", stmt_date:"21 Apr 2026", report_sent:"22 Apr 2026", days_creation_to_update:8, days_stmt_to_report:1, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1152804", client_ref:"26.867683-1", type:"RTC", status:"Invoice Paid", created:"8 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:192, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1153004", client_ref:"26.867709-1", type:"RTC", status:"Awaiting further advises", created:"8 Apr 2026", first_updated:"10 Apr 2026", stmt_date:"13 Apr 2026", report_sent:"13 Apr 2026", days_creation_to_update:2, days_stmt_to_report:0, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1153404", client_ref:"26.844610-1", type:"RTC", status:"Invoiced", created:"8 Apr 2026", first_updated:"9 Apr 2026", stmt_date:"13 Apr 2026", report_sent:"13 Apr 2026", days_creation_to_update:1, days_stmt_to_report:0, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1153604", client_ref:"26.868891-1", type:"RTC", status:"Invoiced", created:"9 Apr 2026", first_updated:"21 Apr 2026", stmt_date:"27 Apr 2026", report_sent:"28 Apr 2026", days_creation_to_update:12, days_stmt_to_report:1, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1153904", client_ref:"26.846550-1", type:"RTC", status:"PH unresponsive", created:"9 Apr 2026", first_updated:"10 Apr 2026", stmt_date:"", report_sent:"", days_creation_to_update:1, days_stmt_to_report:null, invoice:0, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1154304", client_ref:"26.869470-1", type:"RTC", status:"Invoiced", created:"10 Apr 2026", first_updated:"", stmt_date:"24 Apr 2026", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:192, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1154404", client_ref:"26.843410-1", type:"RTC", status:"Invoice Paid", created:"13 Apr 2026", first_updated:"14 Apr 2026", stmt_date:"16 Apr 2026", report_sent:"17 Apr 2026", days_creation_to_update:1, days_stmt_to_report:1, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1154504", client_ref:"26.828172-1", type:"Motor Fraud", status:"Invoiced", created:"13 Apr 2026", first_updated:"20 Apr 2026", stmt_date:"22 Apr 2026", report_sent:"28 Apr 2026", days_creation_to_update:7, days_stmt_to_report:6, invoice:600, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:false, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1154604", client_ref:"26.843359-1", type:"Motor Theft", status:"Invoiced", created:"13 Apr 2026", first_updated:"14 Apr 2026", stmt_date:"21 Apr 2026", report_sent:"1 May 2026", days_creation_to_update:1, days_stmt_to_report:10, invoice:480, is_rtc_case:false, sla_ack:true, sla_contact:true, sla_update:true, sla_report:false, report_proxy:false, sla_report_target_days:3 },
    { ref:"1154704", client_ref:"26.870142-1", type:"RTC", status:"Invoice Paid", created:"13 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:192, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1154904", client_ref:"26.869653-1", type:"RTC", status:"Closed", created:"13 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1155304", client_ref:"26.870939", type:"RTC", status:"Invoiced", created:"14 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:192, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1155904", client_ref:"26.871939-1", type:"RTC", status:"On Hold", created:"15 Apr 2026", first_updated:"15 Apr 2026", stmt_date:"", report_sent:"", days_creation_to_update:0, days_stmt_to_report:null, invoice:0, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1156504", client_ref:"26.865547-1", type:"RTC", status:"Invoice Paid", created:"16 Apr 2026", first_updated:"16 Apr 2026", stmt_date:"16 Apr 2026", report_sent:"16 Apr 2026", days_creation_to_update:0, days_stmt_to_report:0, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1157104", client_ref:"26.870807-1", type:"RTC", status:"Invoiced", created:"17 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:192, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1157704", client_ref:"26.873523-1", type:"RTC", status:"Awaiting further advises", created:"20 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1157804", client_ref:"26.872921-1", type:"RTC", status:"Invoice Paid", created:"20 Apr 2026", first_updated:"21 Apr 2026", stmt_date:"21 Apr 2026", report_sent:"22 Apr 2026", days_creation_to_update:1, days_stmt_to_report:1, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1158404", client_ref:"26.875322-1", type:"RTC", status:"Invoiced", created:"23 Apr 2026", first_updated:"23 Apr 2026", stmt_date:"24 Apr 2026", report_sent:"27 Apr 2026", days_creation_to_update:0, days_stmt_to_report:3, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:false, report_proxy:false, sla_report_target_days:2 },
    { ref:"1158504", client_ref:"26.845157-1", type:"Motor Fraud", status:"Invoiced", created:"23 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:360, is_rtc_case:false, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:3 },
    { ref:"1158604", client_ref:"26.875091-1", type:"RTC", status:"Invoice Paid", created:"24 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:0, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1158704", client_ref:"26.867146", type:"RTC", status:"Invoiced", created:"24 Apr 2026", first_updated:"24 Apr 2026", stmt_date:"5 May 2026", report_sent:"6 May 2026", days_creation_to_update:0, days_stmt_to_report:1, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1158904", client_ref:"26.835990-1", type:"RTC", status:"Invoice Paid", created:"27 Apr 2026", first_updated:"27 Apr 2026", stmt_date:"29 Apr 2026", report_sent:"29 Apr 2026", days_creation_to_update:0, days_stmt_to_report:0, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1159104", client_ref:"26.876178-1", type:"RTC", status:"Invoiced", created:"28 Apr 2026", first_updated:"29 Apr 2026", stmt_date:"29 Apr 2026", report_sent:"1 May 2026", days_creation_to_update:1, days_stmt_to_report:2, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1159204", client_ref:"26.876410-1", type:"RTC", status:"Invoiced", created:"28 Apr 2026", first_updated:"29 Apr 2026", stmt_date:"29 Apr 2026", report_sent:"30 Apr 2026", days_creation_to_update:1, days_stmt_to_report:1, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1159304", client_ref:"26.876628-1", type:"RTC", status:"Invoiced", created:"28 Apr 2026", first_updated:"", stmt_date:"", report_sent:"", days_creation_to_update:null, days_stmt_to_report:null, invoice:192, is_rtc_case:true, sla_ack:null, sla_contact:null, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1159404", client_ref:"26.876985-1", type:"RTC", status:"Invoiced", created:"28 Apr 2026", first_updated:"29 Apr 2026", stmt_date:"1 May 2026", report_sent:"1 May 2026", days_creation_to_update:1, days_stmt_to_report:0, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1159504", client_ref:"26.877001-1", type:"RTC", status:"Invoiced", created:"28 Apr 2026", first_updated:"29 Apr 2026", stmt_date:"", report_sent:"", days_creation_to_update:1, days_stmt_to_report:null, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 },
    { ref:"1159604", client_ref:"26.877103-1", type:"RTC", status:"Invoiced", created:"28 Apr 2026", first_updated:"29 Apr 2026", stmt_date:"6 May 2026", report_sent:"7 May 2026", days_creation_to_update:1, days_stmt_to_report:1, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1159704", client_ref:"26.877268-1", type:"RTC", status:"Invoiced", created:"28 Apr 2026", first_updated:"29 Apr 2026", stmt_date:"30 Apr 2026", report_sent:"30 Apr 2026", days_creation_to_update:1, days_stmt_to_report:0, invoice:192, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:true, report_proxy:false, sla_report_target_days:2 },
    { ref:"1159904", client_ref:"26.828245-1", type:"RTC", status:"Invoice Paid", created:"29 Apr 2026", first_updated:"29 Apr 2026", stmt_date:"", report_sent:"", days_creation_to_update:0, days_stmt_to_report:null, invoice:0, is_rtc_case:true, sla_ack:true, sla_contact:true, sla_update:null, sla_report:null, report_proxy:false, sla_report_target_days:2 }
  ]

};
