// ============================================================
// DLB Investigations Ltd — MI Portal Client Data
// Client:  Zego
// File:    zego.js
// Period:  Jan–May 2026
// Updated: 31 May 2026
// GENERATED AUTOMATICALLY FROM TrackOps CSV — DO NOT EDIT MANUALLY
// ============================================================

var DLB_CLIENT_DATA = {
  "client_name": "Zego",
  "report_period": "Jan–May 2026",
  "last_updated": "31 May 2026",
  "is_rtc_client": true,
  "total_cases": 87,
  "avg_days_creation_to_update": 2.5,
  "avg_days_creation_to_update_general": 3.6,
  "avg_days_stmt_to_report": 5.7,
  "avg_days_stmt_to_report_rtc": 2.1,
  "avg_days_stmt_to_report_general": 10.8,
  "sla_ack_pct": 100,
  "sla_contact_pct": 100,
  "sla_update_pct": 79,
  "sla_report_general_pct": 21,
  "sla_report_rtc_pct": 85,
  "has_rtc_cases": true,
  "has_general_cases": true,
  "sla_compliance_pct": 59,
  "sla_met": 27,
  "sla_not_met": 19,
  "avg_fee_rtc": 119.14,
  "avg_fee_general": 369.06,
  "total_fees_rtc": 6910.0,
  "total_fees_general": 10702.6,
  "rtc_case_count": 58,
  "general_case_count": 29,
  "fees_by_type": [
    {
      "type": "RTC",
      "is_rtc": true,
      "case_count": 58,
      "total_fees": 6910.0,
      "avg_fee": 119.14
    },
    {
      "type": "Motor Fraud",
      "is_rtc": false,
      "case_count": 20,
      "total_fees": 5560.0,
      "avg_fee": 278.0
    },
    {
      "type": "Motor Theft",
      "is_rtc": false,
      "case_count": 9,
      "total_fees": 5142.6,
      "avg_fee": 571.4
    }
  ],
  "total_invoiced_lineitems": 17612.6,
  "total_lineitem_count": 82,
  "fees_by_item": [
    {
      "item": "RTC",
      "is_rtc": true,
      "count": 46,
      "total": 7360.0,
      "avg": 160.0
    },
    {
      "item": "Stage 1 Investigation",
      "is_rtc": false,
      "count": 9,
      "total": 4300.0,
      "avg": 477.78
    },
    {
      "item": "Motor Theft Investigation",
      "is_rtc": false,
      "count": 6,
      "total": 2400.0,
      "avg": 400.0
    },
    {
      "item": "Interpreter (full day)",
      "is_rtc": false,
      "count": 3,
      "total": 900.0,
      "avg": 300.0
    },
    {
      "item": "Translation services",
      "is_rtc": false,
      "count": 2,
      "total": 762.6,
      "avg": 381.3
    },
    {
      "item": "Cold Calls",
      "is_rtc": false,
      "count": 8,
      "total": 720.0,
      "avg": 90.0
    },
    {
      "item": "Stage 2 Investigation",
      "is_rtc": false,
      "count": 2,
      "total": 600.0,
      "avg": 300.0
    },
    {
      "item": "Miscellanoeus",
      "is_rtc": false,
      "count": 3,
      "total": 300.0,
      "avg": 100.0
    },
    {
      "item": "Failed Appointment",
      "is_rtc": false,
      "count": 3,
      "total": 270.0,
      "avg": 90.0
    }
  ],
  "monthly": [
    {
      "month": "Jan",
      "month_num": 1,
      "case_count": 4,
      "case_count_rtc": 0,
      "case_count_general": 4,
      "total_fees": 3582.6,
      "ave_fees": 896,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 3.5,
      "ave_days_creation_to_update_general": 3.5,
      "ave_days_stmt_to_report": 6.0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 6.0,
      "sla_ack_pct": 100,
      "sla_ack_met": 4,
      "sla_ack_n": 4,
      "sla_contact_pct": 100,
      "sla_contact_met": 4,
      "sla_contact_n": 4,
      "sla_update_pct": 75,
      "sla_update_met": 3,
      "sla_update_n": 4,
      "sla_report_general_pct": 25,
      "sla_report_general_met": 1,
      "sla_report_general_n": 4,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 25,
      "sla_met": 1,
      "sla_not_met": 3
    },
    {
      "month": "Feb",
      "month_num": 2,
      "case_count": 8,
      "case_count_rtc": 0,
      "case_count_general": 8,
      "total_fees": 2480.0,
      "ave_fees": 310,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 4.3,
      "ave_days_creation_to_update_general": 4.3,
      "ave_days_stmt_to_report": 17.7,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 17.7,
      "sla_ack_pct": 100,
      "sla_ack_met": 8,
      "sla_ack_n": 8,
      "sla_contact_pct": 100,
      "sla_contact_met": 8,
      "sla_contact_n": 8,
      "sla_update_pct": 83,
      "sla_update_met": 5,
      "sla_update_n": 6,
      "sla_report_general_pct": 17,
      "sla_report_general_met": 1,
      "sla_report_general_n": 6,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 17,
      "sla_met": 1,
      "sla_not_met": 5
    },
    {
      "month": "Mar",
      "month_num": 3,
      "case_count": 7,
      "case_count_rtc": 1,
      "case_count_general": 6,
      "total_fees": 2620.0,
      "ave_fees": 374,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0.8,
      "ave_days_creation_to_update_general": 0.8,
      "ave_days_stmt_to_report": 5.2,
      "ave_days_stmt_to_report_rtc": 0.0,
      "ave_days_stmt_to_report_general": 6.5,
      "sla_ack_pct": 100,
      "sla_ack_met": 7,
      "sla_ack_n": 7,
      "sla_contact_pct": 100,
      "sla_contact_met": 7,
      "sla_contact_n": 7,
      "sla_update_pct": 100,
      "sla_update_met": 4,
      "sla_update_n": 4,
      "sla_report_general_pct": 25,
      "sla_report_general_met": 1,
      "sla_report_general_n": 4,
      "sla_report_rtc_pct": 100,
      "sla_report_rtc_met": 1,
      "sla_report_rtc_n": 1,
      "sla_compliance_pct": 62,
      "sla_met": 2,
      "sla_not_met": 3
    },
    {
      "month": "Apr",
      "month_num": 4,
      "case_count": 39,
      "case_count_rtc": 33,
      "case_count_general": 6,
      "total_fees": 6530.0,
      "ave_fees": 167,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 2.6,
      "ave_days_creation_to_update_general": 2.6,
      "ave_days_stmt_to_report": 3.8,
      "ave_days_stmt_to_report_rtc": 2.3,
      "ave_days_stmt_to_report_general": 9.8,
      "sla_ack_pct": 100,
      "sla_ack_met": 39,
      "sla_ack_n": 39,
      "sla_contact_pct": 100,
      "sla_contact_met": 39,
      "sla_contact_n": 39,
      "sla_update_pct": 60,
      "sla_update_met": 3,
      "sla_update_n": 5,
      "sla_report_general_pct": 20,
      "sla_report_general_met": 1,
      "sla_report_general_n": 5,
      "sla_report_rtc_pct": 86,
      "sla_report_rtc_met": 18,
      "sla_report_rtc_n": 21,
      "sla_compliance_pct": 53,
      "sla_met": 19,
      "sla_not_met": 7
    },
    {
      "month": "May",
      "month_num": 5,
      "case_count": 29,
      "case_count_rtc": 24,
      "case_count_general": 5,
      "total_fees": 2400.0,
      "ave_fees": 83,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0.6,
      "ave_days_creation_to_update_general": 0.6,
      "ave_days_stmt_to_report": 1.6,
      "ave_days_stmt_to_report_rtc": 1.6,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": 100,
      "sla_ack_met": 29,
      "sla_ack_n": 29,
      "sla_contact_pct": 100,
      "sla_contact_met": 29,
      "sla_contact_n": 29,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": 80,
      "sla_report_rtc_met": 4,
      "sla_report_rtc_n": 5,
      "sla_compliance_pct": 80,
      "sla_met": 4,
      "sla_not_met": 1
    },
    {
      "month": "Jun",
      "month_num": 6,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0.0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Jul",
      "month_num": 7,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0.0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Aug",
      "month_num": 8,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0.0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Sep",
      "month_num": 9,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0.0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Oct",
      "month_num": 10,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0.0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Nov",
      "month_num": 11,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0.0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    },
    {
      "month": "Dec",
      "month_num": 12,
      "case_count": 0,
      "case_count_rtc": 0,
      "case_count_general": 0,
      "total_fees": 0.0,
      "ave_fees": 0,
      "total_fees_rtc": 0,
      "total_fees_general": 0,
      "ave_days_creation_to_update": 0,
      "ave_days_creation_to_update_general": 0,
      "ave_days_stmt_to_report": 0,
      "ave_days_stmt_to_report_rtc": 0,
      "ave_days_stmt_to_report_general": 0,
      "sla_ack_pct": null,
      "sla_ack_met": 0,
      "sla_ack_n": 0,
      "sla_contact_pct": null,
      "sla_contact_met": 0,
      "sla_contact_n": 0,
      "sla_update_pct": null,
      "sla_update_met": 0,
      "sla_update_n": 0,
      "sla_report_general_pct": null,
      "sla_report_general_met": 0,
      "sla_report_general_n": 0,
      "sla_report_rtc_pct": null,
      "sla_report_rtc_met": 0,
      "sla_report_rtc_n": 0,
      "sla_compliance_pct": 0,
      "sla_met": 0,
      "sla_not_met": 0
    }
  ],
  "cases": [
    {
      "ref": "1167705",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "28 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1167405",
      "client_ref": null,
      "type": "RTC",
      "status": "Awaiting signed statements",
      "created": "27 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1167205",
      "client_ref": null,
      "type": "RTC",
      "status": "Reviewed, signed off & sent",
      "created": "27 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1167105",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Cold Calls being undertaken",
      "created": "26 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1167005",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "26 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1166905",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "26 May 2026",
      "first_updated": "27 May 2026",
      "stmt_date": "26 May 2026",
      "report_sent": "2 Jun 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 7,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1166805",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "26 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1166705",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Appointment made",
      "created": "26 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1166005",
      "client_ref": null,
      "type": "RTC",
      "status": "RTC contact text sent",
      "created": "21 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1165905",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "21 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1165405",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Statement obtained",
      "created": "20 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1165305",
      "client_ref": null,
      "type": "RTC",
      "status": "Awaiting further advises",
      "created": "20 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1165105",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "19 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1164005",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "15 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1163905",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "15 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1163805",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Await PH response / HUB done",
      "created": "15 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1163605",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "14 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1163505",
      "client_ref": null,
      "type": "RTC",
      "status": "Closed",
      "created": "14 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1163405",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "14 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1163305",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "13 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1163105",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "12 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1163005",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "12 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1162905",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "12 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1162705",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "12 May 2026",
      "first_updated": "12 May 2026",
      "stmt_date": "14 May 2026",
      "report_sent": "15 May 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 1,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1162105",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "8 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1161305",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Appointment made",
      "created": "5 May 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1160905",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "5 May 2026",
      "first_updated": "6 May 2026",
      "stmt_date": "7 May 2026",
      "report_sent": "7 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1160805",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "5 May 2026",
      "first_updated": "5 May 2026",
      "stmt_date": "6 May 2026",
      "report_sent": "6 May 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1160705",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "5 May 2026",
      "first_updated": "6 May 2026",
      "stmt_date": "7 May 2026",
      "report_sent": "7 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1159904",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "29 Apr 2026",
      "first_updated": "29 Apr 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 0,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1159704",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "28 Apr 2026",
      "first_updated": "29 Apr 2026",
      "stmt_date": "30 Apr 2026",
      "report_sent": "30 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1159604",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "28 Apr 2026",
      "first_updated": "29 Apr 2026",
      "stmt_date": "6 May 2026",
      "report_sent": "7 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 1,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1159504",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "28 Apr 2026",
      "first_updated": "29 Apr 2026",
      "stmt_date": "30 Apr 2026",
      "report_sent": "30 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 30,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1159404",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "28 Apr 2026",
      "first_updated": "29 Apr 2026",
      "stmt_date": "1 May 2026",
      "report_sent": "1 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1159304",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "28 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1159204",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "28 Apr 2026",
      "first_updated": "29 Apr 2026",
      "stmt_date": "29 Apr 2026",
      "report_sent": "30 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 1,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1159104",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "28 Apr 2026",
      "first_updated": "29 Apr 2026",
      "stmt_date": "29 Apr 2026",
      "report_sent": "1 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 2,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1158904",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "27 Apr 2026",
      "first_updated": "27 Apr 2026",
      "stmt_date": "29 Apr 2026",
      "report_sent": "29 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1158704",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "24 Apr 2026",
      "first_updated": "24 Apr 2026",
      "stmt_date": "5 May 2026",
      "report_sent": "6 May 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 1,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1158604",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "24 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1158504",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "23 Apr 2026",
      "first_updated": "5 May 2026",
      "stmt_date": "6 May 2026",
      "report_sent": "7 May 2026",
      "days_creation_to_update": 12,
      "days_stmt_to_report": 1,
      "invoice": 300.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1158404",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "23 Apr 2026",
      "first_updated": "23 Apr 2026",
      "stmt_date": "24 Apr 2026",
      "report_sent": "27 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 3,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1157804",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "20 Apr 2026",
      "first_updated": "21 Apr 2026",
      "stmt_date": "21 Apr 2026",
      "report_sent": "22 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 1,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1157704",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "20 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1157104",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "17 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1156504",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "16 Apr 2026",
      "first_updated": "16 Apr 2026",
      "stmt_date": "16 Apr 2026",
      "report_sent": "16 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1155904",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "15 Apr 2026",
      "first_updated": "15 Apr 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 0,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1155304",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "14 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1154904",
      "client_ref": null,
      "type": "RTC",
      "status": "Closed",
      "created": "13 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1154704",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "13 Apr 2026",
      "first_updated": "13 Apr 2026",
      "stmt_date": "14 Apr 2026",
      "report_sent": "14 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1154604",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "13 Apr 2026",
      "first_updated": "14 Apr 2026",
      "stmt_date": "21 Apr 2026",
      "report_sent": "1 May 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 10,
      "invoice": 160.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1154504",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "13 Apr 2026",
      "first_updated": "20 Apr 2026",
      "stmt_date": "22 Apr 2026",
      "report_sent": "28 Apr 2026",
      "days_creation_to_update": 7,
      "days_stmt_to_report": 6,
      "invoice": 500.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1154404",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "13 Apr 2026",
      "first_updated": "14 Apr 2026",
      "stmt_date": "16 Apr 2026",
      "report_sent": "17 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 1,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1154304",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "10 Apr 2026",
      "first_updated": "",
      "stmt_date": "24 Apr 2026",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1153904",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "9 Apr 2026",
      "first_updated": "10 Apr 2026",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": 1,
      "days_stmt_to_report": null,
      "invoice": 30.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1153604",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "9 Apr 2026",
      "first_updated": "21 Apr 2026",
      "stmt_date": "27 Apr 2026",
      "report_sent": "28 Apr 2026",
      "days_creation_to_update": 12,
      "days_stmt_to_report": 1,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1153404",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoiced",
      "created": "8 Apr 2026",
      "first_updated": "9 Apr 2026",
      "stmt_date": "13 Apr 2026",
      "report_sent": "13 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1153004",
      "client_ref": null,
      "type": "RTC",
      "status": "Awaiting further advises",
      "created": "8 Apr 2026",
      "first_updated": "10 Apr 2026",
      "stmt_date": "13 Apr 2026",
      "report_sent": "13 Apr 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1152804",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "8 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1152604",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "8 Apr 2026",
      "first_updated": "16 Apr 2026",
      "stmt_date": "21 Apr 2026",
      "report_sent": "22 Apr 2026",
      "days_creation_to_update": 8,
      "days_stmt_to_report": 1,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1152504",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "8 Apr 2026",
      "first_updated": "14 Apr 2026",
      "stmt_date": "28 Apr 2026",
      "report_sent": "29 Apr 2026",
      "days_creation_to_update": 6,
      "days_stmt_to_report": 1,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1152404",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "8 Apr 2026",
      "first_updated": "13 Apr 2026",
      "stmt_date": "16 Apr 2026",
      "report_sent": "17 Apr 2026",
      "days_creation_to_update": 5,
      "days_stmt_to_report": 1,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1152304",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "8 Apr 2026",
      "first_updated": "13 Apr 2026",
      "stmt_date": "13 Apr 2026",
      "report_sent": "13 Apr 2026",
      "days_creation_to_update": 5,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1152204",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "8 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1150304",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "2 Apr 2026",
      "first_updated": "7 Apr 2026",
      "stmt_date": "13 Apr 2026",
      "report_sent": "28 Apr 2026",
      "days_creation_to_update": 5,
      "days_stmt_to_report": 15,
      "invoice": 500.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1150204",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Enquiries ongoing",
      "created": "2 Apr 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 160.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1150104",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoiced",
      "created": "1 Apr 2026",
      "first_updated": "2 Apr 2026",
      "stmt_date": "7 Apr 2026",
      "report_sent": "24 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 17,
      "invoice": 560.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1150004",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "1 Apr 2026",
      "first_updated": "2 Apr 2026",
      "stmt_date": "16 Apr 2026",
      "report_sent": "21 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 5,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1149103",
      "client_ref": null,
      "type": "RTC",
      "status": "Invoice Paid",
      "created": "31 Mar 2026",
      "first_updated": "2 Apr 2026",
      "stmt_date": "3 Apr 2026",
      "report_sent": "3 Apr 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 0,
      "invoice": 160.0,
      "is_rtc_case": true,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 2
    },
    {
      "ref": "1146003",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "19 Mar 2026",
      "first_updated": "19 Mar 2026",
      "stmt_date": "23 Mar 2026",
      "report_sent": "2 Apr 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 10,
      "invoice": 600.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1145203",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "13 Mar 2026",
      "first_updated": "13 Mar 2026",
      "stmt_date": "19 Mar 2026",
      "report_sent": "27 Mar 2026",
      "days_creation_to_update": 0,
      "days_stmt_to_report": 8,
      "invoice": 500.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1144703",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "12 Mar 2026",
      "first_updated": "13 Mar 2026",
      "stmt_date": "17 Mar 2026",
      "report_sent": "25 Mar 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 8,
      "invoice": 800.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1144503",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Closed",
      "created": "12 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1144003",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "11 Mar 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 60.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1143503",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "10 Mar 2026",
      "first_updated": "11 Mar 2026",
      "stmt_date": "1 Apr 2026",
      "report_sent": "1 Apr 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 0,
      "invoice": 500.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1141402",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "27 Feb 2026",
      "first_updated": "2 Mar 2026",
      "stmt_date": "12 Mar 2026",
      "report_sent": "24 Mar 2026",
      "days_creation_to_update": 3,
      "days_stmt_to_report": 12,
      "invoice": 520.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1140602",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "23 Feb 2026",
      "first_updated": "25 Feb 2026",
      "stmt_date": "",
      "report_sent": "6 Mar 2026",
      "days_creation_to_update": 2,
      "days_stmt_to_report": 9,
      "invoice": 60.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": true,
      "sla_report_target_days": 3
    },
    {
      "ref": "1137902",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "13 Feb 2026",
      "first_updated": "14 Feb 2026",
      "stmt_date": "",
      "report_sent": "6 Mar 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 20,
      "invoice": 300.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": true,
      "sla_report_target_days": 3
    },
    {
      "ref": "1136902",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "10 Feb 2026",
      "first_updated": "25 Feb 2026",
      "stmt_date": "3 Mar 2026",
      "report_sent": "5 Mar 2026",
      "days_creation_to_update": 15,
      "days_stmt_to_report": 2,
      "invoice": 500.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1136502",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "On Hold",
      "created": "9 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 0.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1136102",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "6 Feb 2026",
      "first_updated": "",
      "stmt_date": "",
      "report_sent": "",
      "days_creation_to_update": null,
      "days_stmt_to_report": null,
      "invoice": 60.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": null,
      "sla_report": null,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1135802",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoiced",
      "created": "6 Feb 2026",
      "first_updated": "10 Feb 2026",
      "stmt_date": "14 Mar 2026",
      "report_sent": "8 Apr 2026",
      "days_creation_to_update": 4,
      "days_stmt_to_report": 25,
      "invoice": 920.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1135602",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "5 Feb 2026",
      "first_updated": "6 Feb 2026",
      "stmt_date": "",
      "report_sent": "16 Mar 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 38,
      "invoice": 120.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": true,
      "sla_report_target_days": 3
    },
    {
      "ref": "1133501",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoiced",
      "created": "26 Jan 2026",
      "first_updated": "6 Feb 2026",
      "stmt_date": "17 Mar 2026",
      "report_sent": "20 Mar 2026",
      "days_creation_to_update": 11,
      "days_stmt_to_report": 3,
      "invoice": 860.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": false,
      "sla_report": true,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1131101",
      "client_ref": null,
      "type": "Motor Fraud",
      "status": "Invoice Paid",
      "created": "13 Jan 2026",
      "first_updated": "14 Jan 2026",
      "stmt_date": "20 Jan 2026",
      "report_sent": "29 Jan 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 9,
      "invoice": 500.0,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1130001",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "8 Jan 2026",
      "first_updated": "9 Jan 2026",
      "stmt_date": "15 Jan 2026",
      "report_sent": "22 Jan 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 7,
      "invoice": 1077.25,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    },
    {
      "ref": "1129201",
      "client_ref": null,
      "type": "Motor Theft",
      "status": "Invoice Paid",
      "created": "5 Jan 2026",
      "first_updated": "6 Jan 2026",
      "stmt_date": "14 Jan 2026",
      "report_sent": "19 Jan 2026",
      "days_creation_to_update": 1,
      "days_stmt_to_report": 5,
      "invoice": 1145.35,
      "is_rtc_case": false,
      "sla_ack": true,
      "sla_contact": true,
      "sla_update": true,
      "sla_report": false,
      "report_proxy": false,
      "sla_report_target_days": 3
    }
  ]
};
